// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="forward_substitution_forward_substitution,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100ti-csg324-1L,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.860000,HLS_SYN_LAT=91,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=690,HLS_SYN_LUT=344,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module forward_substitution (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        b_address0,
        b_ce0,
        b_q0,
        x_address0,
        x_ce0,
        x_we0,
        x_d0
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_state8 = 9'd128;
parameter    ap_ST_fsm_state9 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] b_address0;
output   b_ce0;
input  [31:0] b_q0;
output  [3:0] x_address0;
output   x_ce0;
output   x_we0;
output  [31:0] x_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state9;
reg   [0:0] icmp_ln12_reg_329;
reg    ap_condition_exit_pp0_iter0_stage8;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [3:0] p_ZL5L_row_0_address0;
wire   [15:0] p_ZL5L_row_0_q0;
wire   [3:0] p_ZL5L_row_1_address0;
wire   [15:0] p_ZL5L_row_1_q0;
wire   [3:0] p_ZL5L_row_2_address0;
wire   [15:0] p_ZL5L_row_2_q0;
wire   [63:0] zext_ln12_fu_161_p1;
reg   [63:0] zext_ln12_reg_304;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln12_fu_175_p2;
reg   [15:0] p_ZL5L_row_0_load_reg_333;
wire    ap_CS_fsm_state2;
reg   [15:0] p_ZL5L_row_1_load_reg_338;
reg   [31:0] b_load_reg_343;
reg   [15:0] p_ZL5L_row_2_load_reg_348;
wire  signed [47:0] sext_ln20_fu_189_p1;
wire    ap_CS_fsm_state3;
wire  signed [47:0] sext_ln20_1_fu_193_p1;
wire  signed [47:0] sext_ln20_2_fu_201_p1;
wire    ap_CS_fsm_state4;
wire  signed [47:0] sext_ln20_3_fu_205_p1;
reg   [31:0] tmp_reg_373;
wire   [47:0] grp_fu_135_p2;
reg   [47:0] mul_ln20_1_reg_378;
wire    ap_CS_fsm_state5;
wire   [32:0] sub_ln23_fu_254_p2;
reg  signed [32:0] sub_ln23_reg_383;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
reg   [31:0] window_5_reg_398;
wire    ap_CS_fsm_state8;
reg   [3:0] i_fu_58;
wire   [3:0] i_3_fu_169_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_i_1;
reg   [31:0] window_fu_62;
reg   [31:0] window_1_fu_66;
reg    p_ZL5L_row_0_ce0_local;
reg    p_ZL5L_row_1_ce0_local;
reg    b_ce0_local;
reg    p_ZL5L_row_2_ce0_local;
reg    x_we0_local;
reg    x_ce0_local;
reg  signed [15:0] grp_fu_135_p0;
reg  signed [31:0] grp_fu_135_p1;
wire   [15:0] grp_fu_139_p1;
wire  signed [31:0] sext_ln20_1_fu_193_p0;
wire  signed [31:0] sext_ln20_3_fu_205_p0;
wire   [47:0] shl_ln_fu_225_p3;
wire   [47:0] add_ln20_fu_232_p2;
wire   [31:0] trunc_ln_fu_237_p4;
wire  signed [32:0] sext_ln23_fu_247_p1;
wire  signed [32:0] sext_ln23_1_fu_250_p1;
wire   [47:0] grp_fu_139_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [8:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [47:0] grp_fu_139_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
#0 i_fu_58 = 4'd0;
#0 window_fu_62 = 32'd0;
#0 window_1_fu_66 = 32'd0;
#0 ap_done_reg = 1'b0;
end

forward_substitution_p_ZL5L_row_0_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
p_ZL5L_row_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL5L_row_0_address0),
    .ce0(p_ZL5L_row_0_ce0_local),
    .q0(p_ZL5L_row_0_q0)
);

forward_substitution_p_ZL5L_row_1_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
p_ZL5L_row_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL5L_row_1_address0),
    .ce0(p_ZL5L_row_1_ce0_local),
    .q0(p_ZL5L_row_1_q0)
);

forward_substitution_p_ZL5L_row_2_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
p_ZL5L_row_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL5L_row_2_address0),
    .ce0(p_ZL5L_row_2_ce0_local),
    .q0(p_ZL5L_row_2_q0)
);

forward_substitution_mul_16s_32s_48_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 48 ))
mul_16s_32s_48_2_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_135_p0),
    .din1(grp_fu_135_p1),
    .ce(1'b1),
    .dout(grp_fu_135_p2)
);

forward_substitution_mul_33s_16ns_48_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 33 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 48 ))
mul_33s_16ns_48_2_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sub_ln23_reg_383),
    .din1(grp_fu_139_p1),
    .ce(1'b1),
    .dout(grp_fu_139_p2)
);

forward_substitution_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage8),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_58 <= i_3_fu_169_p2;
    end
end

always @ (posedge ap_clk) begin
if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
    window_1_fu_66 <= 32'd0;
end else if ((1'b1 == ap_CS_fsm_state9)) begin
    window_1_fu_66 <= window_5_reg_398;
end
end

always @ (posedge ap_clk) begin
if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
    window_fu_62 <= 32'd0;
end else if ((1'b1 == ap_CS_fsm_state4)) begin
    window_fu_62 <= window_1_fu_66;
end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        b_load_reg_343 <= b_q0;
        p_ZL5L_row_0_load_reg_333 <= p_ZL5L_row_0_q0;
        p_ZL5L_row_1_load_reg_338 <= p_ZL5L_row_1_q0;
        p_ZL5L_row_2_load_reg_348 <= p_ZL5L_row_2_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        icmp_ln12_reg_329 <= icmp_ln12_fu_175_p2;
        zext_ln12_reg_304[3 : 0] <= zext_ln12_fu_161_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        mul_ln20_1_reg_378 <= grp_fu_135_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        sub_ln23_reg_383 <= sub_ln23_fu_254_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        tmp_reg_373 <= {{grp_fu_135_p2[47:16]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        window_5_reg_398 <= {{grp_fu_139_p2[47:16]}};
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln12_reg_329 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_condition_exit_pp0_iter0_stage8 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage8 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 4'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_58;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        b_ce0_local = 1'b1;
    end else begin
        b_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_135_p0 = sext_ln20_2_fu_201_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_135_p0 = sext_ln20_fu_189_p1;
    end else begin
        grp_fu_135_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_135_p1 = sext_ln20_3_fu_205_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_135_p1 = sext_ln20_1_fu_193_p1;
    end else begin
        grp_fu_135_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL5L_row_0_ce0_local = 1'b1;
    end else begin
        p_ZL5L_row_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL5L_row_1_ce0_local = 1'b1;
    end else begin
        p_ZL5L_row_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL5L_row_2_ce0_local = 1'b1;
    end else begin
        p_ZL5L_row_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        x_ce0_local = 1'b1;
    end else begin
        x_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        x_we0_local = 1'b1;
    end else begin
        x_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln20_fu_232_p2 = (shl_ln_fu_225_p3 + mul_ln20_1_reg_378);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage8;

assign ap_ready = ap_ready_sig;

assign b_address0 = zext_ln12_fu_161_p1;

assign b_ce0 = b_ce0_local;

assign grp_fu_139_p1 = grp_fu_139_p10;

assign grp_fu_139_p10 = p_ZL5L_row_2_load_reg_348;

assign i_3_fu_169_p2 = (ap_sig_allocacmp_i_1 + 4'd1);

assign icmp_ln12_fu_175_p2 = ((ap_sig_allocacmp_i_1 == 4'd9) ? 1'b1 : 1'b0);

assign p_ZL5L_row_0_address0 = zext_ln12_fu_161_p1;

assign p_ZL5L_row_1_address0 = zext_ln12_fu_161_p1;

assign p_ZL5L_row_2_address0 = zext_ln12_fu_161_p1;

assign sext_ln20_1_fu_193_p0 = window_fu_62;

assign sext_ln20_1_fu_193_p1 = sext_ln20_1_fu_193_p0;

assign sext_ln20_2_fu_201_p1 = $signed(p_ZL5L_row_1_load_reg_338);

assign sext_ln20_3_fu_205_p0 = window_1_fu_66;

assign sext_ln20_3_fu_205_p1 = sext_ln20_3_fu_205_p0;

assign sext_ln20_fu_189_p1 = $signed(p_ZL5L_row_0_load_reg_333);

assign sext_ln23_1_fu_250_p1 = $signed(trunc_ln_fu_237_p4);

assign sext_ln23_fu_247_p1 = $signed(b_load_reg_343);

assign shl_ln_fu_225_p3 = {{tmp_reg_373}, {16'd0}};

assign sub_ln23_fu_254_p2 = ($signed(sext_ln23_fu_247_p1) - $signed(sext_ln23_1_fu_250_p1));

assign trunc_ln_fu_237_p4 = {{add_ln20_fu_232_p2[47:16]}};

assign x_address0 = zext_ln12_reg_304;

assign x_ce0 = x_ce0_local;

assign x_d0 = {{grp_fu_139_p2[47:16]}};

assign x_we0 = x_we0_local;

assign zext_ln12_fu_161_p1 = ap_sig_allocacmp_i_1;

always @ (posedge ap_clk) begin
    zext_ln12_reg_304[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
end

endmodule //forward_substitution
