-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ADMM_solver_forward_substitution is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    x_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    x_ce0 : OUT STD_LOGIC;
    x_we0 : OUT STD_LOGIC;
    x_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    b_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    b_ce0 : OUT STD_LOGIC;
    b_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_397_p_din0 : OUT STD_LOGIC_VECTOR (21 downto 0);
    grp_fu_397_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_397_p_dout0 : IN STD_LOGIC_VECTOR (53 downto 0);
    grp_fu_397_p_ce : OUT STD_LOGIC;
    grp_fu_401_p_din0 : OUT STD_LOGIC_VECTOR (21 downto 0);
    grp_fu_401_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_401_p_dout0 : IN STD_LOGIC_VECTOR (52 downto 0);
    grp_fu_401_p_ce : OUT STD_LOGIC;
    grp_fu_405_p_din0 : OUT STD_LOGIC_VECTOR (22 downto 0);
    grp_fu_405_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_405_p_dout0 : IN STD_LOGIC_VECTOR (53 downto 0);
    grp_fu_405_p_ce : OUT STD_LOGIC;
    grp_fu_409_p_din0 : OUT STD_LOGIC_VECTOR (24 downto 0);
    grp_fu_409_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_409_p_dout0 : IN STD_LOGIC_VECTOR (55 downto 0);
    grp_fu_409_p_ce : OUT STD_LOGIC;
    grp_fu_413_p_din0 : OUT STD_LOGIC_VECTOR (24 downto 0);
    grp_fu_413_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_413_p_dout0 : IN STD_LOGIC_VECTOR (55 downto 0);
    grp_fu_413_p_ce : OUT STD_LOGIC;
    grp_fu_417_p_din0 : OUT STD_LOGIC_VECTOR (24 downto 0);
    grp_fu_417_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_417_p_dout0 : IN STD_LOGIC_VECTOR (55 downto 0);
    grp_fu_417_p_ce : OUT STD_LOGIC;
    grp_fu_421_p_din0 : OUT STD_LOGIC_VECTOR (25 downto 0);
    grp_fu_421_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_421_p_dout0 : IN STD_LOGIC_VECTOR (56 downto 0);
    grp_fu_421_p_ce : OUT STD_LOGIC;
    grp_fu_425_p_din0 : OUT STD_LOGIC_VECTOR (25 downto 0);
    grp_fu_425_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_425_p_dout0 : IN STD_LOGIC_VECTOR (56 downto 0);
    grp_fu_425_p_ce : OUT STD_LOGIC;
    grp_fu_429_p_din0 : OUT STD_LOGIC_VECTOR (26 downto 0);
    grp_fu_429_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_429_p_dout0 : IN STD_LOGIC_VECTOR (57 downto 0);
    grp_fu_429_p_ce : OUT STD_LOGIC;
    grp_fu_433_p_din0 : OUT STD_LOGIC_VECTOR (26 downto 0);
    grp_fu_433_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_433_p_dout0 : IN STD_LOGIC_VECTOR (57 downto 0);
    grp_fu_433_p_ce : OUT STD_LOGIC;
    grp_fu_437_p_din0 : OUT STD_LOGIC_VECTOR (26 downto 0);
    grp_fu_437_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_437_p_dout0 : IN STD_LOGIC_VECTOR (57 downto 0);
    grp_fu_437_p_ce : OUT STD_LOGIC;
    grp_fu_441_p_din0 : OUT STD_LOGIC_VECTOR (32 downto 0);
    grp_fu_441_p_din1 : OUT STD_LOGIC_VECTOR (19 downto 0);
    grp_fu_441_p_dout0 : IN STD_LOGIC_VECTOR (52 downto 0);
    grp_fu_441_p_ce : OUT STD_LOGIC;
    grp_fu_445_p_din0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    grp_fu_445_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_445_p_dout0 : IN STD_LOGIC_VECTOR (47 downto 0);
    grp_fu_445_p_ce : OUT STD_LOGIC;
    grp_fu_449_p_din0 : OUT STD_LOGIC_VECTOR (19 downto 0);
    grp_fu_449_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_449_p_dout0 : IN STD_LOGIC_VECTOR (50 downto 0);
    grp_fu_449_p_ce : OUT STD_LOGIC;
    grp_fu_453_p_din0 : OUT STD_LOGIC_VECTOR (20 downto 0);
    grp_fu_453_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_453_p_dout0 : IN STD_LOGIC_VECTOR (51 downto 0);
    grp_fu_453_p_ce : OUT STD_LOGIC );
end;


architecture behav of ADMM_solver_forward_substitution is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_ap_start : STD_LOGIC;
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_ap_done : STD_LOGIC;
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_ap_idle : STD_LOGIC;
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_ap_ready : STD_LOGIC;
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_x_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_x_ce0 : STD_LOGIC;
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_x_we0 : STD_LOGIC;
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_x_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_b_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_b_ce0 : STD_LOGIC;
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_90_p_din0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_90_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_90_p_ce : STD_LOGIC;
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_94_p_din0 : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_94_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_94_p_ce : STD_LOGIC;
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_98_p_din0 : STD_LOGIC_VECTOR (20 downto 0);
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_98_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_98_p_ce : STD_LOGIC;
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_102_p_din0 : STD_LOGIC_VECTOR (21 downto 0);
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_102_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_102_p_ce : STD_LOGIC;
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_106_p_din0 : STD_LOGIC_VECTOR (21 downto 0);
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_106_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_106_p_ce : STD_LOGIC;
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_110_p_din0 : STD_LOGIC_VECTOR (22 downto 0);
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_110_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_110_p_ce : STD_LOGIC;
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_114_p_din0 : STD_LOGIC_VECTOR (24 downto 0);
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_114_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_114_p_ce : STD_LOGIC;
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_118_p_din0 : STD_LOGIC_VECTOR (24 downto 0);
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_118_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_118_p_ce : STD_LOGIC;
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_122_p_din0 : STD_LOGIC_VECTOR (24 downto 0);
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_122_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_122_p_ce : STD_LOGIC;
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_126_p_din0 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_126_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_126_p_ce : STD_LOGIC;
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_130_p_din0 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_130_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_130_p_ce : STD_LOGIC;
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_134_p_din0 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_134_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_134_p_ce : STD_LOGIC;
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_138_p_din0 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_138_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_138_p_ce : STD_LOGIC;
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_142_p_din0 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_142_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_142_p_ce : STD_LOGIC;
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_146_p_din0 : STD_LOGIC_VECTOR (32 downto 0);
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_146_p_din1 : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_146_p_ce : STD_LOGIC;
    signal grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_fu_90_ce : STD_LOGIC;
    signal grp_fu_94_ce : STD_LOGIC;
    signal grp_fu_98_ce : STD_LOGIC;
    signal grp_fu_102_ce : STD_LOGIC;
    signal grp_fu_106_ce : STD_LOGIC;
    signal grp_fu_110_ce : STD_LOGIC;
    signal grp_fu_114_ce : STD_LOGIC;
    signal grp_fu_118_ce : STD_LOGIC;
    signal grp_fu_122_ce : STD_LOGIC;
    signal grp_fu_126_ce : STD_LOGIC;
    signal grp_fu_130_ce : STD_LOGIC;
    signal grp_fu_134_ce : STD_LOGIC;
    signal grp_fu_138_ce : STD_LOGIC;
    signal grp_fu_142_ce : STD_LOGIC;
    signal grp_fu_146_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ADMM_solver_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        x_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        x_ce0 : OUT STD_LOGIC;
        x_we0 : OUT STD_LOGIC;
        x_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        b_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        b_ce0 : OUT STD_LOGIC;
        b_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_90_p_din0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        grp_fu_90_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_90_p_dout0 : IN STD_LOGIC_VECTOR (47 downto 0);
        grp_fu_90_p_ce : OUT STD_LOGIC;
        grp_fu_94_p_din0 : OUT STD_LOGIC_VECTOR (19 downto 0);
        grp_fu_94_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_94_p_dout0 : IN STD_LOGIC_VECTOR (50 downto 0);
        grp_fu_94_p_ce : OUT STD_LOGIC;
        grp_fu_98_p_din0 : OUT STD_LOGIC_VECTOR (20 downto 0);
        grp_fu_98_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_98_p_dout0 : IN STD_LOGIC_VECTOR (51 downto 0);
        grp_fu_98_p_ce : OUT STD_LOGIC;
        grp_fu_102_p_din0 : OUT STD_LOGIC_VECTOR (21 downto 0);
        grp_fu_102_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_102_p_dout0 : IN STD_LOGIC_VECTOR (53 downto 0);
        grp_fu_102_p_ce : OUT STD_LOGIC;
        grp_fu_106_p_din0 : OUT STD_LOGIC_VECTOR (21 downto 0);
        grp_fu_106_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_106_p_dout0 : IN STD_LOGIC_VECTOR (52 downto 0);
        grp_fu_106_p_ce : OUT STD_LOGIC;
        grp_fu_110_p_din0 : OUT STD_LOGIC_VECTOR (22 downto 0);
        grp_fu_110_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_110_p_dout0 : IN STD_LOGIC_VECTOR (53 downto 0);
        grp_fu_110_p_ce : OUT STD_LOGIC;
        grp_fu_114_p_din0 : OUT STD_LOGIC_VECTOR (24 downto 0);
        grp_fu_114_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_114_p_dout0 : IN STD_LOGIC_VECTOR (55 downto 0);
        grp_fu_114_p_ce : OUT STD_LOGIC;
        grp_fu_118_p_din0 : OUT STD_LOGIC_VECTOR (24 downto 0);
        grp_fu_118_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_118_p_dout0 : IN STD_LOGIC_VECTOR (55 downto 0);
        grp_fu_118_p_ce : OUT STD_LOGIC;
        grp_fu_122_p_din0 : OUT STD_LOGIC_VECTOR (24 downto 0);
        grp_fu_122_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_122_p_dout0 : IN STD_LOGIC_VECTOR (55 downto 0);
        grp_fu_122_p_ce : OUT STD_LOGIC;
        grp_fu_126_p_din0 : OUT STD_LOGIC_VECTOR (25 downto 0);
        grp_fu_126_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_126_p_dout0 : IN STD_LOGIC_VECTOR (56 downto 0);
        grp_fu_126_p_ce : OUT STD_LOGIC;
        grp_fu_130_p_din0 : OUT STD_LOGIC_VECTOR (25 downto 0);
        grp_fu_130_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_130_p_dout0 : IN STD_LOGIC_VECTOR (56 downto 0);
        grp_fu_130_p_ce : OUT STD_LOGIC;
        grp_fu_134_p_din0 : OUT STD_LOGIC_VECTOR (26 downto 0);
        grp_fu_134_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_134_p_dout0 : IN STD_LOGIC_VECTOR (57 downto 0);
        grp_fu_134_p_ce : OUT STD_LOGIC;
        grp_fu_138_p_din0 : OUT STD_LOGIC_VECTOR (26 downto 0);
        grp_fu_138_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_138_p_dout0 : IN STD_LOGIC_VECTOR (57 downto 0);
        grp_fu_138_p_ce : OUT STD_LOGIC;
        grp_fu_142_p_din0 : OUT STD_LOGIC_VECTOR (26 downto 0);
        grp_fu_142_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_142_p_dout0 : IN STD_LOGIC_VECTOR (57 downto 0);
        grp_fu_142_p_ce : OUT STD_LOGIC;
        grp_fu_146_p_din0 : OUT STD_LOGIC_VECTOR (32 downto 0);
        grp_fu_146_p_din1 : OUT STD_LOGIC_VECTOR (19 downto 0);
        grp_fu_146_p_dout0 : IN STD_LOGIC_VECTOR (52 downto 0);
        grp_fu_146_p_ce : OUT STD_LOGIC );
    end component;


    component ADMM_solver_mul_16s_32s_48_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (47 downto 0) );
    end component;


    component ADMM_solver_mul_20s_32s_51_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (19 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (50 downto 0) );
    end component;


    component ADMM_solver_mul_21s_32s_52_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (20 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (51 downto 0) );
    end component;


    component ADMM_solver_mul_22ns_32s_54_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (21 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (53 downto 0) );
    end component;


    component ADMM_solver_mul_22s_32s_53_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (21 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (52 downto 0) );
    end component;


    component ADMM_solver_mul_23s_32s_54_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (22 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (53 downto 0) );
    end component;


    component ADMM_solver_mul_25s_32s_56_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (24 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (55 downto 0) );
    end component;


    component ADMM_solver_mul_26s_32s_57_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (25 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (56 downto 0) );
    end component;


    component ADMM_solver_mul_27s_32s_58_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (26 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (57 downto 0) );
    end component;


    component ADMM_solver_mul_33s_20ns_53_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (32 downto 0);
        din1 : IN STD_LOGIC_VECTOR (19 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (52 downto 0) );
    end component;



begin
    grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44 : component ADMM_solver_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_ap_start,
        ap_done => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_ap_done,
        ap_idle => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_ap_idle,
        ap_ready => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_ap_ready,
        x_address0 => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_x_address0,
        x_ce0 => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_x_ce0,
        x_we0 => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_x_we0,
        x_d0 => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_x_d0,
        b_address0 => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_b_address0,
        b_ce0 => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_b_ce0,
        b_q0 => b_q0,
        grp_fu_90_p_din0 => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_90_p_din0,
        grp_fu_90_p_din1 => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_90_p_din1,
        grp_fu_90_p_dout0 => grp_fu_445_p_dout0,
        grp_fu_90_p_ce => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_90_p_ce,
        grp_fu_94_p_din0 => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_94_p_din0,
        grp_fu_94_p_din1 => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_94_p_din1,
        grp_fu_94_p_dout0 => grp_fu_449_p_dout0,
        grp_fu_94_p_ce => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_94_p_ce,
        grp_fu_98_p_din0 => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_98_p_din0,
        grp_fu_98_p_din1 => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_98_p_din1,
        grp_fu_98_p_dout0 => grp_fu_453_p_dout0,
        grp_fu_98_p_ce => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_98_p_ce,
        grp_fu_102_p_din0 => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_102_p_din0,
        grp_fu_102_p_din1 => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_102_p_din1,
        grp_fu_102_p_dout0 => grp_fu_397_p_dout0,
        grp_fu_102_p_ce => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_102_p_ce,
        grp_fu_106_p_din0 => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_106_p_din0,
        grp_fu_106_p_din1 => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_106_p_din1,
        grp_fu_106_p_dout0 => grp_fu_401_p_dout0,
        grp_fu_106_p_ce => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_106_p_ce,
        grp_fu_110_p_din0 => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_110_p_din0,
        grp_fu_110_p_din1 => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_110_p_din1,
        grp_fu_110_p_dout0 => grp_fu_405_p_dout0,
        grp_fu_110_p_ce => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_110_p_ce,
        grp_fu_114_p_din0 => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_114_p_din0,
        grp_fu_114_p_din1 => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_114_p_din1,
        grp_fu_114_p_dout0 => grp_fu_409_p_dout0,
        grp_fu_114_p_ce => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_114_p_ce,
        grp_fu_118_p_din0 => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_118_p_din0,
        grp_fu_118_p_din1 => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_118_p_din1,
        grp_fu_118_p_dout0 => grp_fu_413_p_dout0,
        grp_fu_118_p_ce => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_118_p_ce,
        grp_fu_122_p_din0 => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_122_p_din0,
        grp_fu_122_p_din1 => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_122_p_din1,
        grp_fu_122_p_dout0 => grp_fu_417_p_dout0,
        grp_fu_122_p_ce => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_122_p_ce,
        grp_fu_126_p_din0 => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_126_p_din0,
        grp_fu_126_p_din1 => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_126_p_din1,
        grp_fu_126_p_dout0 => grp_fu_421_p_dout0,
        grp_fu_126_p_ce => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_126_p_ce,
        grp_fu_130_p_din0 => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_130_p_din0,
        grp_fu_130_p_din1 => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_130_p_din1,
        grp_fu_130_p_dout0 => grp_fu_425_p_dout0,
        grp_fu_130_p_ce => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_130_p_ce,
        grp_fu_134_p_din0 => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_134_p_din0,
        grp_fu_134_p_din1 => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_134_p_din1,
        grp_fu_134_p_dout0 => grp_fu_429_p_dout0,
        grp_fu_134_p_ce => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_134_p_ce,
        grp_fu_138_p_din0 => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_138_p_din0,
        grp_fu_138_p_din1 => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_138_p_din1,
        grp_fu_138_p_dout0 => grp_fu_433_p_dout0,
        grp_fu_138_p_ce => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_138_p_ce,
        grp_fu_142_p_din0 => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_142_p_din0,
        grp_fu_142_p_din1 => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_142_p_din1,
        grp_fu_142_p_dout0 => grp_fu_437_p_dout0,
        grp_fu_142_p_ce => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_142_p_ce,
        grp_fu_146_p_din0 => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_146_p_din0,
        grp_fu_146_p_din1 => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_146_p_din1,
        grp_fu_146_p_dout0 => grp_fu_441_p_dout0,
        grp_fu_146_p_ce => grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_146_p_ce);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_ap_ready = ap_const_logic_1)) then 
                    grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_ap_done, ap_CS_fsm_state2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_ap_done)
    begin
        if ((grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_ap_done, ap_CS_fsm_state2)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_ap_done, ap_CS_fsm_state2)
    begin
        if (((grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    b_address0 <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_b_address0;
    b_ce0 <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_b_ce0;
    grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_ap_start <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_ap_start_reg;

    grp_fu_102_ce_assign_proc : process(grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_102_p_ce, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_102_ce <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_102_p_ce;
        else 
            grp_fu_102_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_106_ce_assign_proc : process(grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_106_p_ce, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_106_ce <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_106_p_ce;
        else 
            grp_fu_106_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_110_ce_assign_proc : process(grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_110_p_ce, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_110_ce <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_110_p_ce;
        else 
            grp_fu_110_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_114_ce_assign_proc : process(grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_114_p_ce, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_114_ce <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_114_p_ce;
        else 
            grp_fu_114_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_118_ce_assign_proc : process(grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_118_p_ce, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_118_ce <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_118_p_ce;
        else 
            grp_fu_118_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_122_ce_assign_proc : process(grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_122_p_ce, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_122_ce <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_122_p_ce;
        else 
            grp_fu_122_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_126_ce_assign_proc : process(grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_126_p_ce, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_126_ce <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_126_p_ce;
        else 
            grp_fu_126_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_130_ce_assign_proc : process(grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_130_p_ce, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_130_ce <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_130_p_ce;
        else 
            grp_fu_130_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_134_ce_assign_proc : process(grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_134_p_ce, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_134_ce <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_134_p_ce;
        else 
            grp_fu_134_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_138_ce_assign_proc : process(grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_138_p_ce, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_138_ce <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_138_p_ce;
        else 
            grp_fu_138_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_142_ce_assign_proc : process(grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_142_p_ce, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_142_ce <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_142_p_ce;
        else 
            grp_fu_142_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_146_ce_assign_proc : process(grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_146_p_ce, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_146_ce <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_146_p_ce;
        else 
            grp_fu_146_ce <= ap_const_logic_1;
        end if; 
    end process;

    grp_fu_397_p_ce <= grp_fu_102_ce;
    grp_fu_397_p_din0 <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_102_p_din0;
    grp_fu_397_p_din1 <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_102_p_din1;
    grp_fu_401_p_ce <= grp_fu_106_ce;
    grp_fu_401_p_din0 <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_106_p_din0;
    grp_fu_401_p_din1 <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_106_p_din1;
    grp_fu_405_p_ce <= grp_fu_110_ce;
    grp_fu_405_p_din0 <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_110_p_din0;
    grp_fu_405_p_din1 <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_110_p_din1;
    grp_fu_409_p_ce <= grp_fu_114_ce;
    grp_fu_409_p_din0 <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_114_p_din0;
    grp_fu_409_p_din1 <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_114_p_din1;
    grp_fu_413_p_ce <= grp_fu_118_ce;
    grp_fu_413_p_din0 <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_118_p_din0;
    grp_fu_413_p_din1 <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_118_p_din1;
    grp_fu_417_p_ce <= grp_fu_122_ce;
    grp_fu_417_p_din0 <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_122_p_din0;
    grp_fu_417_p_din1 <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_122_p_din1;
    grp_fu_421_p_ce <= grp_fu_126_ce;
    grp_fu_421_p_din0 <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_126_p_din0;
    grp_fu_421_p_din1 <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_126_p_din1;
    grp_fu_425_p_ce <= grp_fu_130_ce;
    grp_fu_425_p_din0 <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_130_p_din0;
    grp_fu_425_p_din1 <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_130_p_din1;
    grp_fu_429_p_ce <= grp_fu_134_ce;
    grp_fu_429_p_din0 <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_134_p_din0;
    grp_fu_429_p_din1 <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_134_p_din1;
    grp_fu_433_p_ce <= grp_fu_138_ce;
    grp_fu_433_p_din0 <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_138_p_din0;
    grp_fu_433_p_din1 <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_138_p_din1;
    grp_fu_437_p_ce <= grp_fu_142_ce;
    grp_fu_437_p_din0 <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_142_p_din0;
    grp_fu_437_p_din1 <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_142_p_din1;
    grp_fu_441_p_ce <= grp_fu_146_ce;
    grp_fu_441_p_din0 <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_146_p_din0;
    grp_fu_441_p_din1 <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_146_p_din1;
    grp_fu_445_p_ce <= grp_fu_90_ce;
    grp_fu_445_p_din0 <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_90_p_din0;
    grp_fu_445_p_din1 <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_90_p_din1;
    grp_fu_449_p_ce <= grp_fu_94_ce;
    grp_fu_449_p_din0 <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_94_p_din0;
    grp_fu_449_p_din1 <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_94_p_din1;
    grp_fu_453_p_ce <= grp_fu_98_ce;
    grp_fu_453_p_din0 <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_98_p_din0;
    grp_fu_453_p_din1 <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_98_p_din1;

    grp_fu_90_ce_assign_proc : process(grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_90_p_ce, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_90_ce <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_90_p_ce;
        else 
            grp_fu_90_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_94_ce_assign_proc : process(grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_94_p_ce, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_94_ce <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_94_p_ce;
        else 
            grp_fu_94_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_98_ce_assign_proc : process(grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_98_p_ce, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_98_ce <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_grp_fu_98_p_ce;
        else 
            grp_fu_98_ce <= ap_const_logic_1;
        end if; 
    end process;

    x_address0 <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_x_address0;
    x_ce0 <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_x_ce0;
    x_d0 <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_x_d0;
    x_we0 <= grp_forward_substitution_Pipeline_FORW_SUBST_EXTERN_LOOP_fu_44_x_we0;
end behav;
