-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ADMM_solver_backward_substitution is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    b_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    b_ce0 : OUT STD_LOGIC;
    b_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    x_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    x_ce0 : OUT STD_LOGIC;
    x_we0 : OUT STD_LOGIC;
    x_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_477_p_din0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    grp_fu_477_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_477_p_dout0 : IN STD_LOGIC_VECTOR (41 downto 0);
    grp_fu_477_p_ce : OUT STD_LOGIC;
    grp_fu_413_p_din0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    grp_fu_413_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_413_p_dout0 : IN STD_LOGIC_VECTOR (42 downto 0);
    grp_fu_413_p_ce : OUT STD_LOGIC;
    grp_fu_417_p_din0 : OUT STD_LOGIC_VECTOR (21 downto 0);
    grp_fu_417_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_417_p_dout0 : IN STD_LOGIC_VECTOR (52 downto 0);
    grp_fu_417_p_ce : OUT STD_LOGIC;
    grp_fu_421_p_din0 : OUT STD_LOGIC_VECTOR (22 downto 0);
    grp_fu_421_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_421_p_dout0 : IN STD_LOGIC_VECTOR (53 downto 0);
    grp_fu_421_p_ce : OUT STD_LOGIC;
    grp_fu_425_p_din0 : OUT STD_LOGIC_VECTOR (22 downto 0);
    grp_fu_425_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_425_p_dout0 : IN STD_LOGIC_VECTOR (53 downto 0);
    grp_fu_425_p_ce : OUT STD_LOGIC;
    grp_fu_429_p_din0 : OUT STD_LOGIC_VECTOR (23 downto 0);
    grp_fu_429_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_429_p_dout0 : IN STD_LOGIC_VECTOR (54 downto 0);
    grp_fu_429_p_ce : OUT STD_LOGIC;
    grp_fu_433_p_din0 : OUT STD_LOGIC_VECTOR (24 downto 0);
    grp_fu_433_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_433_p_dout0 : IN STD_LOGIC_VECTOR (56 downto 0);
    grp_fu_433_p_ce : OUT STD_LOGIC;
    grp_fu_437_p_din0 : OUT STD_LOGIC_VECTOR (25 downto 0);
    grp_fu_437_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_437_p_dout0 : IN STD_LOGIC_VECTOR (56 downto 0);
    grp_fu_437_p_ce : OUT STD_LOGIC;
    grp_fu_441_p_din0 : OUT STD_LOGIC_VECTOR (25 downto 0);
    grp_fu_441_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_441_p_dout0 : IN STD_LOGIC_VECTOR (56 downto 0);
    grp_fu_441_p_ce : OUT STD_LOGIC;
    grp_fu_445_p_din0 : OUT STD_LOGIC_VECTOR (25 downto 0);
    grp_fu_445_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_445_p_dout0 : IN STD_LOGIC_VECTOR (56 downto 0);
    grp_fu_445_p_ce : OUT STD_LOGIC;
    grp_fu_449_p_din0 : OUT STD_LOGIC_VECTOR (25 downto 0);
    grp_fu_449_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_449_p_dout0 : IN STD_LOGIC_VECTOR (56 downto 0);
    grp_fu_449_p_ce : OUT STD_LOGIC;
    grp_fu_453_p_din0 : OUT STD_LOGIC_VECTOR (26 downto 0);
    grp_fu_453_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_453_p_dout0 : IN STD_LOGIC_VECTOR (57 downto 0);
    grp_fu_453_p_ce : OUT STD_LOGIC;
    grp_fu_457_p_din0 : OUT STD_LOGIC_VECTOR (29 downto 0);
    grp_fu_457_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_457_p_dout0 : IN STD_LOGIC_VECTOR (60 downto 0);
    grp_fu_457_p_ce : OUT STD_LOGIC;
    grp_fu_461_p_din0 : OUT STD_LOGIC_VECTOR (29 downto 0);
    grp_fu_461_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_461_p_dout0 : IN STD_LOGIC_VECTOR (60 downto 0);
    grp_fu_461_p_ce : OUT STD_LOGIC;
    grp_fu_465_p_din0 : OUT STD_LOGIC_VECTOR (29 downto 0);
    grp_fu_465_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_465_p_dout0 : IN STD_LOGIC_VECTOR (60 downto 0);
    grp_fu_465_p_ce : OUT STD_LOGIC;
    grp_fu_469_p_din0 : OUT STD_LOGIC_VECTOR (29 downto 0);
    grp_fu_469_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_469_p_dout0 : IN STD_LOGIC_VECTOR (60 downto 0);
    grp_fu_469_p_ce : OUT STD_LOGIC;
    grp_fu_473_p_din0 : OUT STD_LOGIC_VECTOR (32 downto 0);
    grp_fu_473_p_din1 : OUT STD_LOGIC_VECTOR (21 downto 0);
    grp_fu_473_p_dout0 : IN STD_LOGIC_VECTOR (54 downto 0);
    grp_fu_473_p_ce : OUT STD_LOGIC );
end;


architecture behav of ADMM_solver_backward_substitution is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_start : STD_LOGIC;
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_done : STD_LOGIC;
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_idle : STD_LOGIC;
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_ready : STD_LOGIC;
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_b_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_b_ce0 : STD_LOGIC;
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_x_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_x_ce0 : STD_LOGIC;
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_x_we0 : STD_LOGIC;
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_x_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_108_p_din0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_108_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_108_p_ce : STD_LOGIC;
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_112_p_din0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_112_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_112_p_ce : STD_LOGIC;
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_116_p_din0 : STD_LOGIC_VECTOR (21 downto 0);
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_116_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_116_p_ce : STD_LOGIC;
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_120_p_din0 : STD_LOGIC_VECTOR (22 downto 0);
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_120_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_120_p_ce : STD_LOGIC;
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_124_p_din0 : STD_LOGIC_VECTOR (22 downto 0);
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_124_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_124_p_ce : STD_LOGIC;
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_128_p_din0 : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_128_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_128_p_ce : STD_LOGIC;
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_132_p_din0 : STD_LOGIC_VECTOR (24 downto 0);
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_132_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_132_p_ce : STD_LOGIC;
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_136_p_din0 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_136_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_136_p_ce : STD_LOGIC;
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_140_p_din0 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_140_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_140_p_ce : STD_LOGIC;
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_144_p_din0 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_144_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_144_p_ce : STD_LOGIC;
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_148_p_din0 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_148_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_148_p_ce : STD_LOGIC;
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_152_p_din0 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_152_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_152_p_ce : STD_LOGIC;
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_156_p_din0 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_156_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_156_p_ce : STD_LOGIC;
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_160_p_din0 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_160_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_160_p_ce : STD_LOGIC;
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_164_p_din0 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_164_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_164_p_ce : STD_LOGIC;
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_168_p_din0 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_168_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_168_p_ce : STD_LOGIC;
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_172_p_din0 : STD_LOGIC_VECTOR (32 downto 0);
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_172_p_din1 : STD_LOGIC_VECTOR (21 downto 0);
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_172_p_ce : STD_LOGIC;
    signal grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_fu_108_ce : STD_LOGIC;
    signal grp_fu_112_ce : STD_LOGIC;
    signal grp_fu_116_ce : STD_LOGIC;
    signal grp_fu_120_ce : STD_LOGIC;
    signal grp_fu_124_ce : STD_LOGIC;
    signal grp_fu_128_ce : STD_LOGIC;
    signal grp_fu_132_ce : STD_LOGIC;
    signal grp_fu_136_ce : STD_LOGIC;
    signal grp_fu_140_ce : STD_LOGIC;
    signal grp_fu_144_ce : STD_LOGIC;
    signal grp_fu_148_ce : STD_LOGIC;
    signal grp_fu_152_ce : STD_LOGIC;
    signal grp_fu_156_ce : STD_LOGIC;
    signal grp_fu_160_ce : STD_LOGIC;
    signal grp_fu_164_ce : STD_LOGIC;
    signal grp_fu_168_ce : STD_LOGIC;
    signal grp_fu_172_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ADMM_solver_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        b_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        b_ce0 : OUT STD_LOGIC;
        b_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        x_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        x_ce0 : OUT STD_LOGIC;
        x_we0 : OUT STD_LOGIC;
        x_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_108_p_din0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        grp_fu_108_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_108_p_dout0 : IN STD_LOGIC_VECTOR (41 downto 0);
        grp_fu_108_p_ce : OUT STD_LOGIC;
        grp_fu_112_p_din0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        grp_fu_112_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_112_p_dout0 : IN STD_LOGIC_VECTOR (42 downto 0);
        grp_fu_112_p_ce : OUT STD_LOGIC;
        grp_fu_116_p_din0 : OUT STD_LOGIC_VECTOR (21 downto 0);
        grp_fu_116_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_116_p_dout0 : IN STD_LOGIC_VECTOR (52 downto 0);
        grp_fu_116_p_ce : OUT STD_LOGIC;
        grp_fu_120_p_din0 : OUT STD_LOGIC_VECTOR (22 downto 0);
        grp_fu_120_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_120_p_dout0 : IN STD_LOGIC_VECTOR (53 downto 0);
        grp_fu_120_p_ce : OUT STD_LOGIC;
        grp_fu_124_p_din0 : OUT STD_LOGIC_VECTOR (22 downto 0);
        grp_fu_124_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_124_p_dout0 : IN STD_LOGIC_VECTOR (53 downto 0);
        grp_fu_124_p_ce : OUT STD_LOGIC;
        grp_fu_128_p_din0 : OUT STD_LOGIC_VECTOR (23 downto 0);
        grp_fu_128_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_128_p_dout0 : IN STD_LOGIC_VECTOR (54 downto 0);
        grp_fu_128_p_ce : OUT STD_LOGIC;
        grp_fu_132_p_din0 : OUT STD_LOGIC_VECTOR (24 downto 0);
        grp_fu_132_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_132_p_dout0 : IN STD_LOGIC_VECTOR (56 downto 0);
        grp_fu_132_p_ce : OUT STD_LOGIC;
        grp_fu_136_p_din0 : OUT STD_LOGIC_VECTOR (25 downto 0);
        grp_fu_136_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_136_p_dout0 : IN STD_LOGIC_VECTOR (56 downto 0);
        grp_fu_136_p_ce : OUT STD_LOGIC;
        grp_fu_140_p_din0 : OUT STD_LOGIC_VECTOR (25 downto 0);
        grp_fu_140_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_140_p_dout0 : IN STD_LOGIC_VECTOR (56 downto 0);
        grp_fu_140_p_ce : OUT STD_LOGIC;
        grp_fu_144_p_din0 : OUT STD_LOGIC_VECTOR (25 downto 0);
        grp_fu_144_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_144_p_dout0 : IN STD_LOGIC_VECTOR (56 downto 0);
        grp_fu_144_p_ce : OUT STD_LOGIC;
        grp_fu_148_p_din0 : OUT STD_LOGIC_VECTOR (25 downto 0);
        grp_fu_148_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_148_p_dout0 : IN STD_LOGIC_VECTOR (56 downto 0);
        grp_fu_148_p_ce : OUT STD_LOGIC;
        grp_fu_152_p_din0 : OUT STD_LOGIC_VECTOR (26 downto 0);
        grp_fu_152_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_152_p_dout0 : IN STD_LOGIC_VECTOR (57 downto 0);
        grp_fu_152_p_ce : OUT STD_LOGIC;
        grp_fu_156_p_din0 : OUT STD_LOGIC_VECTOR (29 downto 0);
        grp_fu_156_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_156_p_dout0 : IN STD_LOGIC_VECTOR (60 downto 0);
        grp_fu_156_p_ce : OUT STD_LOGIC;
        grp_fu_160_p_din0 : OUT STD_LOGIC_VECTOR (29 downto 0);
        grp_fu_160_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_160_p_dout0 : IN STD_LOGIC_VECTOR (60 downto 0);
        grp_fu_160_p_ce : OUT STD_LOGIC;
        grp_fu_164_p_din0 : OUT STD_LOGIC_VECTOR (29 downto 0);
        grp_fu_164_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_164_p_dout0 : IN STD_LOGIC_VECTOR (60 downto 0);
        grp_fu_164_p_ce : OUT STD_LOGIC;
        grp_fu_168_p_din0 : OUT STD_LOGIC_VECTOR (29 downto 0);
        grp_fu_168_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_168_p_dout0 : IN STD_LOGIC_VECTOR (60 downto 0);
        grp_fu_168_p_ce : OUT STD_LOGIC;
        grp_fu_172_p_din0 : OUT STD_LOGIC_VECTOR (32 downto 0);
        grp_fu_172_p_din1 : OUT STD_LOGIC_VECTOR (21 downto 0);
        grp_fu_172_p_dout0 : IN STD_LOGIC_VECTOR (54 downto 0);
        grp_fu_172_p_ce : OUT STD_LOGIC );
    end component;


    component ADMM_solver_mul_10ns_32s_42_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (9 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (41 downto 0) );
    end component;


    component ADMM_solver_mul_11s_32s_43_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (10 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (42 downto 0) );
    end component;


    component ADMM_solver_mul_22s_32s_53_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (21 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (52 downto 0) );
    end component;


    component ADMM_solver_mul_23s_32s_54_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (22 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (53 downto 0) );
    end component;


    component ADMM_solver_mul_24s_32s_55_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (23 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (54 downto 0) );
    end component;


    component ADMM_solver_mul_25ns_32s_57_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (24 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (56 downto 0) );
    end component;


    component ADMM_solver_mul_26s_32s_57_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (25 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (56 downto 0) );
    end component;


    component ADMM_solver_mul_27s_32s_58_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (26 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (57 downto 0) );
    end component;


    component ADMM_solver_mul_30s_32s_61_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (29 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (60 downto 0) );
    end component;


    component ADMM_solver_mul_33s_22ns_55_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (32 downto 0);
        din1 : IN STD_LOGIC_VECTOR (21 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (54 downto 0) );
    end component;



begin
    grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58 : component ADMM_solver_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_start,
        ap_done => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_done,
        ap_idle => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_idle,
        ap_ready => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_ready,
        b_address0 => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_b_address0,
        b_ce0 => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_b_ce0,
        b_q0 => b_q0,
        x_address0 => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_x_address0,
        x_ce0 => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_x_ce0,
        x_we0 => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_x_we0,
        x_d0 => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_x_d0,
        grp_fu_108_p_din0 => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_108_p_din0,
        grp_fu_108_p_din1 => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_108_p_din1,
        grp_fu_108_p_dout0 => grp_fu_477_p_dout0,
        grp_fu_108_p_ce => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_108_p_ce,
        grp_fu_112_p_din0 => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_112_p_din0,
        grp_fu_112_p_din1 => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_112_p_din1,
        grp_fu_112_p_dout0 => grp_fu_413_p_dout0,
        grp_fu_112_p_ce => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_112_p_ce,
        grp_fu_116_p_din0 => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_116_p_din0,
        grp_fu_116_p_din1 => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_116_p_din1,
        grp_fu_116_p_dout0 => grp_fu_417_p_dout0,
        grp_fu_116_p_ce => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_116_p_ce,
        grp_fu_120_p_din0 => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_120_p_din0,
        grp_fu_120_p_din1 => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_120_p_din1,
        grp_fu_120_p_dout0 => grp_fu_421_p_dout0,
        grp_fu_120_p_ce => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_120_p_ce,
        grp_fu_124_p_din0 => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_124_p_din0,
        grp_fu_124_p_din1 => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_124_p_din1,
        grp_fu_124_p_dout0 => grp_fu_425_p_dout0,
        grp_fu_124_p_ce => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_124_p_ce,
        grp_fu_128_p_din0 => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_128_p_din0,
        grp_fu_128_p_din1 => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_128_p_din1,
        grp_fu_128_p_dout0 => grp_fu_429_p_dout0,
        grp_fu_128_p_ce => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_128_p_ce,
        grp_fu_132_p_din0 => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_132_p_din0,
        grp_fu_132_p_din1 => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_132_p_din1,
        grp_fu_132_p_dout0 => grp_fu_433_p_dout0,
        grp_fu_132_p_ce => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_132_p_ce,
        grp_fu_136_p_din0 => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_136_p_din0,
        grp_fu_136_p_din1 => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_136_p_din1,
        grp_fu_136_p_dout0 => grp_fu_437_p_dout0,
        grp_fu_136_p_ce => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_136_p_ce,
        grp_fu_140_p_din0 => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_140_p_din0,
        grp_fu_140_p_din1 => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_140_p_din1,
        grp_fu_140_p_dout0 => grp_fu_441_p_dout0,
        grp_fu_140_p_ce => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_140_p_ce,
        grp_fu_144_p_din0 => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_144_p_din0,
        grp_fu_144_p_din1 => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_144_p_din1,
        grp_fu_144_p_dout0 => grp_fu_445_p_dout0,
        grp_fu_144_p_ce => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_144_p_ce,
        grp_fu_148_p_din0 => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_148_p_din0,
        grp_fu_148_p_din1 => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_148_p_din1,
        grp_fu_148_p_dout0 => grp_fu_449_p_dout0,
        grp_fu_148_p_ce => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_148_p_ce,
        grp_fu_152_p_din0 => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_152_p_din0,
        grp_fu_152_p_din1 => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_152_p_din1,
        grp_fu_152_p_dout0 => grp_fu_453_p_dout0,
        grp_fu_152_p_ce => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_152_p_ce,
        grp_fu_156_p_din0 => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_156_p_din0,
        grp_fu_156_p_din1 => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_156_p_din1,
        grp_fu_156_p_dout0 => grp_fu_457_p_dout0,
        grp_fu_156_p_ce => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_156_p_ce,
        grp_fu_160_p_din0 => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_160_p_din0,
        grp_fu_160_p_din1 => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_160_p_din1,
        grp_fu_160_p_dout0 => grp_fu_461_p_dout0,
        grp_fu_160_p_ce => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_160_p_ce,
        grp_fu_164_p_din0 => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_164_p_din0,
        grp_fu_164_p_din1 => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_164_p_din1,
        grp_fu_164_p_dout0 => grp_fu_465_p_dout0,
        grp_fu_164_p_ce => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_164_p_ce,
        grp_fu_168_p_din0 => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_168_p_din0,
        grp_fu_168_p_din1 => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_168_p_din1,
        grp_fu_168_p_dout0 => grp_fu_469_p_dout0,
        grp_fu_168_p_ce => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_168_p_ce,
        grp_fu_172_p_din0 => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_172_p_din0,
        grp_fu_172_p_din1 => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_172_p_din1,
        grp_fu_172_p_dout0 => grp_fu_473_p_dout0,
        grp_fu_172_p_ce => grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_172_p_ce);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_ready = ap_const_logic_1)) then 
                    grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_done, ap_CS_fsm_state2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_done)
    begin
        if ((grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_done, ap_CS_fsm_state2)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_done, ap_CS_fsm_state2)
    begin
        if (((grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    b_address0 <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_b_address0;
    b_ce0 <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_b_ce0;
    grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_start <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_start_reg;

    grp_fu_108_ce_assign_proc : process(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_108_p_ce, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_108_ce <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_108_p_ce;
        else 
            grp_fu_108_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_112_ce_assign_proc : process(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_112_p_ce, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_112_ce <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_112_p_ce;
        else 
            grp_fu_112_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_116_ce_assign_proc : process(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_116_p_ce, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_116_ce <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_116_p_ce;
        else 
            grp_fu_116_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_120_ce_assign_proc : process(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_120_p_ce, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_120_ce <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_120_p_ce;
        else 
            grp_fu_120_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_124_ce_assign_proc : process(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_124_p_ce, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_124_ce <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_124_p_ce;
        else 
            grp_fu_124_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_128_ce_assign_proc : process(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_128_p_ce, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_128_ce <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_128_p_ce;
        else 
            grp_fu_128_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_132_ce_assign_proc : process(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_132_p_ce, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_132_ce <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_132_p_ce;
        else 
            grp_fu_132_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_136_ce_assign_proc : process(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_136_p_ce, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_136_ce <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_136_p_ce;
        else 
            grp_fu_136_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_140_ce_assign_proc : process(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_140_p_ce, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_140_ce <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_140_p_ce;
        else 
            grp_fu_140_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_144_ce_assign_proc : process(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_144_p_ce, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_144_ce <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_144_p_ce;
        else 
            grp_fu_144_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_148_ce_assign_proc : process(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_148_p_ce, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_148_ce <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_148_p_ce;
        else 
            grp_fu_148_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_152_ce_assign_proc : process(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_152_p_ce, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_152_ce <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_152_p_ce;
        else 
            grp_fu_152_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_156_ce_assign_proc : process(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_156_p_ce, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_156_ce <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_156_p_ce;
        else 
            grp_fu_156_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_160_ce_assign_proc : process(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_160_p_ce, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_160_ce <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_160_p_ce;
        else 
            grp_fu_160_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_164_ce_assign_proc : process(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_164_p_ce, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_164_ce <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_164_p_ce;
        else 
            grp_fu_164_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_168_ce_assign_proc : process(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_168_p_ce, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_168_ce <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_168_p_ce;
        else 
            grp_fu_168_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_172_ce_assign_proc : process(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_172_p_ce, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_172_ce <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_172_p_ce;
        else 
            grp_fu_172_ce <= ap_const_logic_1;
        end if; 
    end process;

    grp_fu_413_p_ce <= grp_fu_112_ce;
    grp_fu_413_p_din0 <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_112_p_din0;
    grp_fu_413_p_din1 <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_112_p_din1;
    grp_fu_417_p_ce <= grp_fu_116_ce;
    grp_fu_417_p_din0 <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_116_p_din0;
    grp_fu_417_p_din1 <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_116_p_din1;
    grp_fu_421_p_ce <= grp_fu_120_ce;
    grp_fu_421_p_din0 <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_120_p_din0;
    grp_fu_421_p_din1 <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_120_p_din1;
    grp_fu_425_p_ce <= grp_fu_124_ce;
    grp_fu_425_p_din0 <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_124_p_din0;
    grp_fu_425_p_din1 <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_124_p_din1;
    grp_fu_429_p_ce <= grp_fu_128_ce;
    grp_fu_429_p_din0 <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_128_p_din0;
    grp_fu_429_p_din1 <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_128_p_din1;
    grp_fu_433_p_ce <= grp_fu_132_ce;
    grp_fu_433_p_din0 <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_132_p_din0;
    grp_fu_433_p_din1 <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_132_p_din1;
    grp_fu_437_p_ce <= grp_fu_136_ce;
    grp_fu_437_p_din0 <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_136_p_din0;
    grp_fu_437_p_din1 <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_136_p_din1;
    grp_fu_441_p_ce <= grp_fu_140_ce;
    grp_fu_441_p_din0 <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_140_p_din0;
    grp_fu_441_p_din1 <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_140_p_din1;
    grp_fu_445_p_ce <= grp_fu_144_ce;
    grp_fu_445_p_din0 <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_144_p_din0;
    grp_fu_445_p_din1 <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_144_p_din1;
    grp_fu_449_p_ce <= grp_fu_148_ce;
    grp_fu_449_p_din0 <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_148_p_din0;
    grp_fu_449_p_din1 <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_148_p_din1;
    grp_fu_453_p_ce <= grp_fu_152_ce;
    grp_fu_453_p_din0 <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_152_p_din0;
    grp_fu_453_p_din1 <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_152_p_din1;
    grp_fu_457_p_ce <= grp_fu_156_ce;
    grp_fu_457_p_din0 <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_156_p_din0;
    grp_fu_457_p_din1 <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_156_p_din1;
    grp_fu_461_p_ce <= grp_fu_160_ce;
    grp_fu_461_p_din0 <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_160_p_din0;
    grp_fu_461_p_din1 <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_160_p_din1;
    grp_fu_465_p_ce <= grp_fu_164_ce;
    grp_fu_465_p_din0 <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_164_p_din0;
    grp_fu_465_p_din1 <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_164_p_din1;
    grp_fu_469_p_ce <= grp_fu_168_ce;
    grp_fu_469_p_din0 <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_168_p_din0;
    grp_fu_469_p_din1 <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_168_p_din1;
    grp_fu_473_p_ce <= grp_fu_172_ce;
    grp_fu_473_p_din0 <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_172_p_din0;
    grp_fu_473_p_din1 <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_172_p_din1;
    grp_fu_477_p_ce <= grp_fu_108_ce;
    grp_fu_477_p_din0 <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_108_p_din0;
    grp_fu_477_p_din1 <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_108_p_din1;
    x_address0 <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_x_address0;
    x_ce0 <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_x_ce0;
    x_d0 <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_x_d0;
    x_we0 <= grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_x_we0;
end behav;
