// Auto-generated by scripts/header_generator.py. Do not edit.
`ifndef ADMM_AUTOGEN_PARAMS_VH
`define ADMM_AUTOGEN_PARAMS_VH

`define ADMM_HORIZON_LENGTH 40
`define ADMM_N_STATE 12
`define ADMM_STAGE_SIZE 16
`define ADMM_N_VAR 652
`define ADMM_N_CONSTR 732
`define ADMM_START_INEQ 492
`define ADMM_DELAY_STEPS 0
`endif // ADMM_AUTOGEN_PARAMS_VH
