// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module ADMM_solver_ADMM_iteration (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_address0,
        x_ce0,
        x_we0,
        x_d0,
        x_q0,
        x_address1,
        x_ce1,
        x_q1,
        current_state_address0,
        current_state_ce0,
        current_state_q0
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] x_address0;
output   x_ce0;
output   x_we0;
output  [31:0] x_d0;
input  [31:0] x_q0;
output  [8:0] x_address1;
output   x_ce1;
input  [31:0] x_q1;
output  [3:0] current_state_address0;
output   current_state_ce0;
input  [31:0] current_state_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[8:0] x_address0;
reg x_ce0;
reg x_we0;
reg x_ce1;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [8:0] b_address0;
reg    b_ce0;
reg    b_we0;
wire   [31:0] b_q0;
reg   [8:0] tmp_address0;
reg    tmp_ce0;
reg    tmp_we0;
wire   [31:0] tmp_q0;
reg   [8:0] b_tmp_address0;
reg    b_tmp_ce0;
reg    b_tmp_we0;
wire   [31:0] b_tmp_q0;
reg    b_tmp_ce1;
wire   [31:0] b_tmp_q1;
reg    b_tmp_ce2;
wire   [31:0] b_tmp_q2;
reg    b_tmp_ce3;
wire   [31:0] b_tmp_q3;
reg    b_tmp_ce4;
wire   [31:0] b_tmp_q4;
reg    b_tmp_ce5;
wire   [31:0] b_tmp_q5;
reg    b_tmp_ce6;
wire   [31:0] b_tmp_q6;
reg    b_tmp_ce7;
wire   [31:0] b_tmp_q7;
reg    b_tmp_ce8;
wire   [31:0] b_tmp_q8;
reg    b_tmp_ce9;
wire   [31:0] b_tmp_q9;
reg    b_tmp_ce10;
wire   [31:0] b_tmp_q10;
reg    b_tmp_ce11;
wire   [31:0] b_tmp_q11;
reg    b_tmp_ce12;
wire   [31:0] b_tmp_q12;
wire    grp_forward_substitution_fu_208_ap_start;
wire    grp_forward_substitution_fu_208_ap_done;
wire    grp_forward_substitution_fu_208_ap_idle;
wire    grp_forward_substitution_fu_208_ap_ready;
wire   [8:0] grp_forward_substitution_fu_208_x_address0;
wire    grp_forward_substitution_fu_208_x_ce0;
wire    grp_forward_substitution_fu_208_x_we0;
wire   [31:0] grp_forward_substitution_fu_208_x_d0;
wire   [8:0] grp_forward_substitution_fu_208_b_address0;
wire    grp_forward_substitution_fu_208_b_ce0;
wire  signed [10:0] grp_forward_substitution_fu_208_grp_fu_413_p_din0;
wire  signed [31:0] grp_forward_substitution_fu_208_grp_fu_413_p_din1;
wire    grp_forward_substitution_fu_208_grp_fu_413_p_ce;
wire  signed [21:0] grp_forward_substitution_fu_208_grp_fu_417_p_din0;
wire  signed [31:0] grp_forward_substitution_fu_208_grp_fu_417_p_din1;
wire    grp_forward_substitution_fu_208_grp_fu_417_p_ce;
wire  signed [22:0] grp_forward_substitution_fu_208_grp_fu_421_p_din0;
wire  signed [31:0] grp_forward_substitution_fu_208_grp_fu_421_p_din1;
wire    grp_forward_substitution_fu_208_grp_fu_421_p_ce;
wire  signed [22:0] grp_forward_substitution_fu_208_grp_fu_425_p_din0;
wire  signed [31:0] grp_forward_substitution_fu_208_grp_fu_425_p_din1;
wire    grp_forward_substitution_fu_208_grp_fu_425_p_ce;
wire  signed [23:0] grp_forward_substitution_fu_208_grp_fu_429_p_din0;
wire  signed [31:0] grp_forward_substitution_fu_208_grp_fu_429_p_din1;
wire    grp_forward_substitution_fu_208_grp_fu_429_p_ce;
wire   [24:0] grp_forward_substitution_fu_208_grp_fu_433_p_din0;
wire  signed [31:0] grp_forward_substitution_fu_208_grp_fu_433_p_din1;
wire    grp_forward_substitution_fu_208_grp_fu_433_p_ce;
wire  signed [25:0] grp_forward_substitution_fu_208_grp_fu_437_p_din0;
wire  signed [31:0] grp_forward_substitution_fu_208_grp_fu_437_p_din1;
wire    grp_forward_substitution_fu_208_grp_fu_437_p_ce;
wire  signed [25:0] grp_forward_substitution_fu_208_grp_fu_441_p_din0;
wire  signed [31:0] grp_forward_substitution_fu_208_grp_fu_441_p_din1;
wire    grp_forward_substitution_fu_208_grp_fu_441_p_ce;
wire  signed [25:0] grp_forward_substitution_fu_208_grp_fu_445_p_din0;
wire  signed [31:0] grp_forward_substitution_fu_208_grp_fu_445_p_din1;
wire    grp_forward_substitution_fu_208_grp_fu_445_p_ce;
wire  signed [25:0] grp_forward_substitution_fu_208_grp_fu_449_p_din0;
wire  signed [31:0] grp_forward_substitution_fu_208_grp_fu_449_p_din1;
wire    grp_forward_substitution_fu_208_grp_fu_449_p_ce;
wire  signed [26:0] grp_forward_substitution_fu_208_grp_fu_453_p_din0;
wire  signed [31:0] grp_forward_substitution_fu_208_grp_fu_453_p_din1;
wire    grp_forward_substitution_fu_208_grp_fu_453_p_ce;
wire  signed [29:0] grp_forward_substitution_fu_208_grp_fu_457_p_din0;
wire  signed [31:0] grp_forward_substitution_fu_208_grp_fu_457_p_din1;
wire    grp_forward_substitution_fu_208_grp_fu_457_p_ce;
wire  signed [29:0] grp_forward_substitution_fu_208_grp_fu_461_p_din0;
wire  signed [31:0] grp_forward_substitution_fu_208_grp_fu_461_p_din1;
wire    grp_forward_substitution_fu_208_grp_fu_461_p_ce;
wire  signed [29:0] grp_forward_substitution_fu_208_grp_fu_465_p_din0;
wire  signed [31:0] grp_forward_substitution_fu_208_grp_fu_465_p_din1;
wire    grp_forward_substitution_fu_208_grp_fu_465_p_ce;
wire  signed [29:0] grp_forward_substitution_fu_208_grp_fu_469_p_din0;
wire  signed [31:0] grp_forward_substitution_fu_208_grp_fu_469_p_din1;
wire    grp_forward_substitution_fu_208_grp_fu_469_p_ce;
wire  signed [32:0] grp_forward_substitution_fu_208_grp_fu_473_p_din0;
wire   [21:0] grp_forward_substitution_fu_208_grp_fu_473_p_din1;
wire    grp_forward_substitution_fu_208_grp_fu_473_p_ce;
wire   [9:0] grp_forward_substitution_fu_208_grp_fu_477_p_din0;
wire  signed [31:0] grp_forward_substitution_fu_208_grp_fu_477_p_din1;
wire    grp_forward_substitution_fu_208_grp_fu_477_p_ce;
wire    grp_backward_substitution_fu_258_ap_start;
wire    grp_backward_substitution_fu_258_ap_done;
wire    grp_backward_substitution_fu_258_ap_idle;
wire    grp_backward_substitution_fu_258_ap_ready;
wire   [8:0] grp_backward_substitution_fu_258_b_address0;
wire    grp_backward_substitution_fu_258_b_ce0;
wire   [8:0] grp_backward_substitution_fu_258_x_address0;
wire    grp_backward_substitution_fu_258_x_ce0;
wire    grp_backward_substitution_fu_258_x_we0;
wire   [31:0] grp_backward_substitution_fu_258_x_d0;
wire   [9:0] grp_backward_substitution_fu_258_grp_fu_477_p_din0;
wire  signed [31:0] grp_backward_substitution_fu_258_grp_fu_477_p_din1;
wire    grp_backward_substitution_fu_258_grp_fu_477_p_ce;
wire  signed [10:0] grp_backward_substitution_fu_258_grp_fu_413_p_din0;
wire  signed [31:0] grp_backward_substitution_fu_258_grp_fu_413_p_din1;
wire    grp_backward_substitution_fu_258_grp_fu_413_p_ce;
wire  signed [21:0] grp_backward_substitution_fu_258_grp_fu_417_p_din0;
wire  signed [31:0] grp_backward_substitution_fu_258_grp_fu_417_p_din1;
wire    grp_backward_substitution_fu_258_grp_fu_417_p_ce;
wire  signed [22:0] grp_backward_substitution_fu_258_grp_fu_421_p_din0;
wire  signed [31:0] grp_backward_substitution_fu_258_grp_fu_421_p_din1;
wire    grp_backward_substitution_fu_258_grp_fu_421_p_ce;
wire  signed [22:0] grp_backward_substitution_fu_258_grp_fu_425_p_din0;
wire  signed [31:0] grp_backward_substitution_fu_258_grp_fu_425_p_din1;
wire    grp_backward_substitution_fu_258_grp_fu_425_p_ce;
wire  signed [23:0] grp_backward_substitution_fu_258_grp_fu_429_p_din0;
wire  signed [31:0] grp_backward_substitution_fu_258_grp_fu_429_p_din1;
wire    grp_backward_substitution_fu_258_grp_fu_429_p_ce;
wire   [24:0] grp_backward_substitution_fu_258_grp_fu_433_p_din0;
wire  signed [31:0] grp_backward_substitution_fu_258_grp_fu_433_p_din1;
wire    grp_backward_substitution_fu_258_grp_fu_433_p_ce;
wire  signed [25:0] grp_backward_substitution_fu_258_grp_fu_437_p_din0;
wire  signed [31:0] grp_backward_substitution_fu_258_grp_fu_437_p_din1;
wire    grp_backward_substitution_fu_258_grp_fu_437_p_ce;
wire  signed [25:0] grp_backward_substitution_fu_258_grp_fu_441_p_din0;
wire  signed [31:0] grp_backward_substitution_fu_258_grp_fu_441_p_din1;
wire    grp_backward_substitution_fu_258_grp_fu_441_p_ce;
wire  signed [25:0] grp_backward_substitution_fu_258_grp_fu_445_p_din0;
wire  signed [31:0] grp_backward_substitution_fu_258_grp_fu_445_p_din1;
wire    grp_backward_substitution_fu_258_grp_fu_445_p_ce;
wire  signed [25:0] grp_backward_substitution_fu_258_grp_fu_449_p_din0;
wire  signed [31:0] grp_backward_substitution_fu_258_grp_fu_449_p_din1;
wire    grp_backward_substitution_fu_258_grp_fu_449_p_ce;
wire  signed [26:0] grp_backward_substitution_fu_258_grp_fu_453_p_din0;
wire  signed [31:0] grp_backward_substitution_fu_258_grp_fu_453_p_din1;
wire    grp_backward_substitution_fu_258_grp_fu_453_p_ce;
wire  signed [29:0] grp_backward_substitution_fu_258_grp_fu_457_p_din0;
wire  signed [31:0] grp_backward_substitution_fu_258_grp_fu_457_p_din1;
wire    grp_backward_substitution_fu_258_grp_fu_457_p_ce;
wire  signed [29:0] grp_backward_substitution_fu_258_grp_fu_461_p_din0;
wire  signed [31:0] grp_backward_substitution_fu_258_grp_fu_461_p_din1;
wire    grp_backward_substitution_fu_258_grp_fu_461_p_ce;
wire  signed [29:0] grp_backward_substitution_fu_258_grp_fu_465_p_din0;
wire  signed [31:0] grp_backward_substitution_fu_258_grp_fu_465_p_din1;
wire    grp_backward_substitution_fu_258_grp_fu_465_p_ce;
wire  signed [29:0] grp_backward_substitution_fu_258_grp_fu_469_p_din0;
wire  signed [31:0] grp_backward_substitution_fu_258_grp_fu_469_p_din1;
wire    grp_backward_substitution_fu_258_grp_fu_469_p_ce;
wire  signed [32:0] grp_backward_substitution_fu_258_grp_fu_473_p_din0;
wire   [21:0] grp_backward_substitution_fu_258_grp_fu_473_p_din1;
wire    grp_backward_substitution_fu_258_grp_fu_473_p_ce;
wire    grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_ap_start;
wire    grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_ap_done;
wire    grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_ap_idle;
wire    grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_ap_ready;
wire   [8:0] grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_x_address0;
wire    grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_x_ce0;
wire   [8:0] grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_x_address1;
wire    grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_x_ce1;
wire   [3:0] grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_current_state_address0;
wire    grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_current_state_ce0;
wire   [8:0] grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_b_tmp_address0;
wire    grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_b_tmp_ce0;
wire    grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_b_tmp_we0;
wire   [31:0] grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_b_tmp_d0;
wire  signed [31:0] grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_grp_fu_481_p_din0;
wire   [22:0] grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_grp_fu_481_p_din1;
wire    grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_grp_fu_481_p_ce;
wire  signed [31:0] grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_grp_fu_485_p_din0;
wire  signed [23:0] grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_grp_fu_485_p_din1;
wire    grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_grp_fu_485_p_ce;
wire  signed [31:0] grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_grp_fu_489_p_din0;
wire  signed [25:0] grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_grp_fu_489_p_din1;
wire    grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_grp_fu_489_p_ce;
wire  signed [31:0] grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_grp_fu_493_p_din0;
wire  signed [25:0] grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_grp_fu_493_p_din1;
wire    grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_grp_fu_493_p_ce;
wire    grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_ap_start;
wire    grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_ap_done;
wire    grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_ap_idle;
wire    grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_ap_ready;
wire   [8:0] grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_address0;
wire    grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_ce0;
wire   [8:0] grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_address1;
wire    grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_ce1;
wire   [8:0] grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_address2;
wire    grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_ce2;
wire   [8:0] grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_address3;
wire    grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_ce3;
wire   [8:0] grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_address4;
wire    grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_ce4;
wire   [8:0] grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_address5;
wire    grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_ce5;
wire   [8:0] grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_address6;
wire    grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_ce6;
wire   [8:0] grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_address7;
wire    grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_ce7;
wire   [8:0] grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_address8;
wire    grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_ce8;
wire   [8:0] grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_address9;
wire    grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_ce9;
wire   [8:0] grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_address10;
wire    grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_ce10;
wire   [8:0] grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_address11;
wire    grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_ce11;
wire   [8:0] grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_address12;
wire    grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_ce12;
wire   [8:0] grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_address0;
wire    grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_ce0;
wire    grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_we0;
wire   [31:0] grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_d0;
wire  signed [31:0] grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_grp_fu_481_p_din0;
wire   [22:0] grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_grp_fu_481_p_din1;
wire    grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_grp_fu_481_p_ce;
wire  signed [31:0] grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_grp_fu_485_p_din0;
wire  signed [23:0] grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_grp_fu_485_p_din1;
wire    grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_grp_fu_485_p_ce;
wire  signed [31:0] grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_grp_fu_489_p_din0;
wire  signed [25:0] grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_grp_fu_489_p_din1;
wire    grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_grp_fu_489_p_ce;
wire  signed [31:0] grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_grp_fu_493_p_din0;
wire  signed [25:0] grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_grp_fu_493_p_din1;
wire    grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_grp_fu_493_p_ce;
reg    grp_forward_substitution_fu_208_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_backward_substitution_fu_258_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg    grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_ap_start_reg;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire  signed [42:0] grp_fu_413_p2;
reg  signed [10:0] grp_fu_413_p0;
reg  signed [31:0] grp_fu_413_p1;
reg    grp_fu_413_ce;
wire  signed [52:0] grp_fu_417_p2;
reg  signed [21:0] grp_fu_417_p0;
reg  signed [31:0] grp_fu_417_p1;
reg    grp_fu_417_ce;
wire  signed [53:0] grp_fu_421_p2;
reg  signed [22:0] grp_fu_421_p0;
reg  signed [31:0] grp_fu_421_p1;
reg    grp_fu_421_ce;
wire  signed [53:0] grp_fu_425_p2;
reg  signed [22:0] grp_fu_425_p0;
reg  signed [31:0] grp_fu_425_p1;
reg    grp_fu_425_ce;
wire  signed [54:0] grp_fu_429_p2;
reg  signed [23:0] grp_fu_429_p0;
reg  signed [31:0] grp_fu_429_p1;
reg    grp_fu_429_ce;
wire   [56:0] grp_fu_433_p2;
reg   [24:0] grp_fu_433_p0;
reg  signed [31:0] grp_fu_433_p1;
reg    grp_fu_433_ce;
wire   [56:0] grp_fu_437_p2;
reg  signed [25:0] grp_fu_437_p0;
reg  signed [31:0] grp_fu_437_p1;
reg    grp_fu_437_ce;
wire  signed [56:0] grp_fu_441_p2;
reg  signed [25:0] grp_fu_441_p0;
reg  signed [31:0] grp_fu_441_p1;
reg    grp_fu_441_ce;
wire  signed [56:0] grp_fu_445_p2;
reg  signed [25:0] grp_fu_445_p0;
reg  signed [31:0] grp_fu_445_p1;
reg    grp_fu_445_ce;
wire  signed [56:0] grp_fu_449_p2;
reg  signed [25:0] grp_fu_449_p0;
reg  signed [31:0] grp_fu_449_p1;
reg    grp_fu_449_ce;
wire  signed [57:0] grp_fu_453_p2;
reg  signed [26:0] grp_fu_453_p0;
reg  signed [31:0] grp_fu_453_p1;
reg    grp_fu_453_ce;
wire   [60:0] grp_fu_457_p2;
reg  signed [29:0] grp_fu_457_p0;
reg  signed [31:0] grp_fu_457_p1;
reg    grp_fu_457_ce;
wire   [60:0] grp_fu_461_p2;
reg  signed [29:0] grp_fu_461_p0;
reg  signed [31:0] grp_fu_461_p1;
reg    grp_fu_461_ce;
wire   [60:0] grp_fu_465_p2;
reg  signed [29:0] grp_fu_465_p0;
reg  signed [31:0] grp_fu_465_p1;
reg    grp_fu_465_ce;
wire   [60:0] grp_fu_469_p2;
reg  signed [29:0] grp_fu_469_p0;
reg  signed [31:0] grp_fu_469_p1;
reg    grp_fu_469_ce;
wire   [54:0] grp_fu_473_p2;
reg  signed [32:0] grp_fu_473_p0;
reg   [21:0] grp_fu_473_p1;
reg    grp_fu_473_ce;
wire  signed [41:0] grp_fu_477_p2;
reg   [9:0] grp_fu_477_p0;
reg  signed [31:0] grp_fu_477_p1;
reg    grp_fu_477_ce;
wire  signed [53:0] grp_fu_481_p2;
reg  signed [31:0] grp_fu_481_p0;
reg   [22:0] grp_fu_481_p1;
reg    grp_fu_481_ce;
wire  signed [53:0] grp_fu_485_p2;
reg  signed [31:0] grp_fu_485_p0;
reg  signed [23:0] grp_fu_485_p1;
reg    grp_fu_485_ce;
wire   [56:0] grp_fu_489_p2;
reg  signed [31:0] grp_fu_489_p0;
reg  signed [25:0] grp_fu_489_p1;
reg    grp_fu_489_ce;
wire   [56:0] grp_fu_493_p2;
reg  signed [31:0] grp_fu_493_p0;
reg  signed [25:0] grp_fu_493_p1;
reg    grp_fu_493_ce;
reg   [7:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 grp_forward_substitution_fu_208_ap_start_reg = 1'b0;
#0 grp_backward_substitution_fu_258_ap_start_reg = 1'b0;
#0 grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_ap_start_reg = 1'b0;
#0 grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_ap_start_reg = 1'b0;
end

ADMM_solver_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_y_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 332 ),
    .AddressWidth( 9 ))
b_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(b_address0),
    .ce0(b_ce0),
    .we0(b_we0),
    .d0(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_d0),
    .q0(b_q0)
);

ADMM_solver_ADMM_iteration_tmp_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 332 ),
    .AddressWidth( 9 ))
tmp_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tmp_address0),
    .ce0(tmp_ce0),
    .we0(tmp_we0),
    .d0(grp_forward_substitution_fu_208_x_d0),
    .q0(tmp_q0)
);

ADMM_solver_ADMM_iteration_b_tmp_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 332 ),
    .AddressWidth( 9 ))
b_tmp_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(b_tmp_address0),
    .ce0(b_tmp_ce0),
    .we0(b_tmp_we0),
    .d0(grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_b_tmp_d0),
    .q0(b_tmp_q0),
    .address1(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_address1),
    .ce1(b_tmp_ce1),
    .q1(b_tmp_q1),
    .address2(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_address2),
    .ce2(b_tmp_ce2),
    .q2(b_tmp_q2),
    .address3(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_address3),
    .ce3(b_tmp_ce3),
    .q3(b_tmp_q3),
    .address4(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_address4),
    .ce4(b_tmp_ce4),
    .q4(b_tmp_q4),
    .address5(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_address5),
    .ce5(b_tmp_ce5),
    .q5(b_tmp_q5),
    .address6(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_address6),
    .ce6(b_tmp_ce6),
    .q6(b_tmp_q6),
    .address7(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_address7),
    .ce7(b_tmp_ce7),
    .q7(b_tmp_q7),
    .address8(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_address8),
    .ce8(b_tmp_ce8),
    .q8(b_tmp_q8),
    .address9(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_address9),
    .ce9(b_tmp_ce9),
    .q9(b_tmp_q9),
    .address10(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_address10),
    .ce10(b_tmp_ce10),
    .q10(b_tmp_q10),
    .address11(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_address11),
    .ce11(b_tmp_ce11),
    .q11(b_tmp_q11),
    .address12(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_address12),
    .ce12(b_tmp_ce12),
    .q12(b_tmp_q12)
);

ADMM_solver_forward_substitution grp_forward_substitution_fu_208(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_forward_substitution_fu_208_ap_start),
    .ap_done(grp_forward_substitution_fu_208_ap_done),
    .ap_idle(grp_forward_substitution_fu_208_ap_idle),
    .ap_ready(grp_forward_substitution_fu_208_ap_ready),
    .x_address0(grp_forward_substitution_fu_208_x_address0),
    .x_ce0(grp_forward_substitution_fu_208_x_ce0),
    .x_we0(grp_forward_substitution_fu_208_x_we0),
    .x_d0(grp_forward_substitution_fu_208_x_d0),
    .b_address0(grp_forward_substitution_fu_208_b_address0),
    .b_ce0(grp_forward_substitution_fu_208_b_ce0),
    .b_q0(b_q0),
    .grp_fu_413_p_din0(grp_forward_substitution_fu_208_grp_fu_413_p_din0),
    .grp_fu_413_p_din1(grp_forward_substitution_fu_208_grp_fu_413_p_din1),
    .grp_fu_413_p_dout0(grp_fu_413_p2),
    .grp_fu_413_p_ce(grp_forward_substitution_fu_208_grp_fu_413_p_ce),
    .grp_fu_417_p_din0(grp_forward_substitution_fu_208_grp_fu_417_p_din0),
    .grp_fu_417_p_din1(grp_forward_substitution_fu_208_grp_fu_417_p_din1),
    .grp_fu_417_p_dout0(grp_fu_417_p2),
    .grp_fu_417_p_ce(grp_forward_substitution_fu_208_grp_fu_417_p_ce),
    .grp_fu_421_p_din0(grp_forward_substitution_fu_208_grp_fu_421_p_din0),
    .grp_fu_421_p_din1(grp_forward_substitution_fu_208_grp_fu_421_p_din1),
    .grp_fu_421_p_dout0(grp_fu_421_p2),
    .grp_fu_421_p_ce(grp_forward_substitution_fu_208_grp_fu_421_p_ce),
    .grp_fu_425_p_din0(grp_forward_substitution_fu_208_grp_fu_425_p_din0),
    .grp_fu_425_p_din1(grp_forward_substitution_fu_208_grp_fu_425_p_din1),
    .grp_fu_425_p_dout0(grp_fu_425_p2),
    .grp_fu_425_p_ce(grp_forward_substitution_fu_208_grp_fu_425_p_ce),
    .grp_fu_429_p_din0(grp_forward_substitution_fu_208_grp_fu_429_p_din0),
    .grp_fu_429_p_din1(grp_forward_substitution_fu_208_grp_fu_429_p_din1),
    .grp_fu_429_p_dout0(grp_fu_429_p2),
    .grp_fu_429_p_ce(grp_forward_substitution_fu_208_grp_fu_429_p_ce),
    .grp_fu_433_p_din0(grp_forward_substitution_fu_208_grp_fu_433_p_din0),
    .grp_fu_433_p_din1(grp_forward_substitution_fu_208_grp_fu_433_p_din1),
    .grp_fu_433_p_dout0(grp_fu_433_p2),
    .grp_fu_433_p_ce(grp_forward_substitution_fu_208_grp_fu_433_p_ce),
    .grp_fu_437_p_din0(grp_forward_substitution_fu_208_grp_fu_437_p_din0),
    .grp_fu_437_p_din1(grp_forward_substitution_fu_208_grp_fu_437_p_din1),
    .grp_fu_437_p_dout0(grp_fu_437_p2),
    .grp_fu_437_p_ce(grp_forward_substitution_fu_208_grp_fu_437_p_ce),
    .grp_fu_441_p_din0(grp_forward_substitution_fu_208_grp_fu_441_p_din0),
    .grp_fu_441_p_din1(grp_forward_substitution_fu_208_grp_fu_441_p_din1),
    .grp_fu_441_p_dout0(grp_fu_441_p2),
    .grp_fu_441_p_ce(grp_forward_substitution_fu_208_grp_fu_441_p_ce),
    .grp_fu_445_p_din0(grp_forward_substitution_fu_208_grp_fu_445_p_din0),
    .grp_fu_445_p_din1(grp_forward_substitution_fu_208_grp_fu_445_p_din1),
    .grp_fu_445_p_dout0(grp_fu_445_p2),
    .grp_fu_445_p_ce(grp_forward_substitution_fu_208_grp_fu_445_p_ce),
    .grp_fu_449_p_din0(grp_forward_substitution_fu_208_grp_fu_449_p_din0),
    .grp_fu_449_p_din1(grp_forward_substitution_fu_208_grp_fu_449_p_din1),
    .grp_fu_449_p_dout0(grp_fu_449_p2),
    .grp_fu_449_p_ce(grp_forward_substitution_fu_208_grp_fu_449_p_ce),
    .grp_fu_453_p_din0(grp_forward_substitution_fu_208_grp_fu_453_p_din0),
    .grp_fu_453_p_din1(grp_forward_substitution_fu_208_grp_fu_453_p_din1),
    .grp_fu_453_p_dout0(grp_fu_453_p2),
    .grp_fu_453_p_ce(grp_forward_substitution_fu_208_grp_fu_453_p_ce),
    .grp_fu_457_p_din0(grp_forward_substitution_fu_208_grp_fu_457_p_din0),
    .grp_fu_457_p_din1(grp_forward_substitution_fu_208_grp_fu_457_p_din1),
    .grp_fu_457_p_dout0(grp_fu_457_p2),
    .grp_fu_457_p_ce(grp_forward_substitution_fu_208_grp_fu_457_p_ce),
    .grp_fu_461_p_din0(grp_forward_substitution_fu_208_grp_fu_461_p_din0),
    .grp_fu_461_p_din1(grp_forward_substitution_fu_208_grp_fu_461_p_din1),
    .grp_fu_461_p_dout0(grp_fu_461_p2),
    .grp_fu_461_p_ce(grp_forward_substitution_fu_208_grp_fu_461_p_ce),
    .grp_fu_465_p_din0(grp_forward_substitution_fu_208_grp_fu_465_p_din0),
    .grp_fu_465_p_din1(grp_forward_substitution_fu_208_grp_fu_465_p_din1),
    .grp_fu_465_p_dout0(grp_fu_465_p2),
    .grp_fu_465_p_ce(grp_forward_substitution_fu_208_grp_fu_465_p_ce),
    .grp_fu_469_p_din0(grp_forward_substitution_fu_208_grp_fu_469_p_din0),
    .grp_fu_469_p_din1(grp_forward_substitution_fu_208_grp_fu_469_p_din1),
    .grp_fu_469_p_dout0(grp_fu_469_p2),
    .grp_fu_469_p_ce(grp_forward_substitution_fu_208_grp_fu_469_p_ce),
    .grp_fu_473_p_din0(grp_forward_substitution_fu_208_grp_fu_473_p_din0),
    .grp_fu_473_p_din1(grp_forward_substitution_fu_208_grp_fu_473_p_din1),
    .grp_fu_473_p_dout0(grp_fu_473_p2),
    .grp_fu_473_p_ce(grp_forward_substitution_fu_208_grp_fu_473_p_ce),
    .grp_fu_477_p_din0(grp_forward_substitution_fu_208_grp_fu_477_p_din0),
    .grp_fu_477_p_din1(grp_forward_substitution_fu_208_grp_fu_477_p_din1),
    .grp_fu_477_p_dout0(grp_fu_477_p2),
    .grp_fu_477_p_ce(grp_forward_substitution_fu_208_grp_fu_477_p_ce)
);

ADMM_solver_backward_substitution grp_backward_substitution_fu_258(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_backward_substitution_fu_258_ap_start),
    .ap_done(grp_backward_substitution_fu_258_ap_done),
    .ap_idle(grp_backward_substitution_fu_258_ap_idle),
    .ap_ready(grp_backward_substitution_fu_258_ap_ready),
    .b_address0(grp_backward_substitution_fu_258_b_address0),
    .b_ce0(grp_backward_substitution_fu_258_b_ce0),
    .b_q0(tmp_q0),
    .x_address0(grp_backward_substitution_fu_258_x_address0),
    .x_ce0(grp_backward_substitution_fu_258_x_ce0),
    .x_we0(grp_backward_substitution_fu_258_x_we0),
    .x_d0(grp_backward_substitution_fu_258_x_d0),
    .grp_fu_477_p_din0(grp_backward_substitution_fu_258_grp_fu_477_p_din0),
    .grp_fu_477_p_din1(grp_backward_substitution_fu_258_grp_fu_477_p_din1),
    .grp_fu_477_p_dout0(grp_fu_477_p2),
    .grp_fu_477_p_ce(grp_backward_substitution_fu_258_grp_fu_477_p_ce),
    .grp_fu_413_p_din0(grp_backward_substitution_fu_258_grp_fu_413_p_din0),
    .grp_fu_413_p_din1(grp_backward_substitution_fu_258_grp_fu_413_p_din1),
    .grp_fu_413_p_dout0(grp_fu_413_p2),
    .grp_fu_413_p_ce(grp_backward_substitution_fu_258_grp_fu_413_p_ce),
    .grp_fu_417_p_din0(grp_backward_substitution_fu_258_grp_fu_417_p_din0),
    .grp_fu_417_p_din1(grp_backward_substitution_fu_258_grp_fu_417_p_din1),
    .grp_fu_417_p_dout0(grp_fu_417_p2),
    .grp_fu_417_p_ce(grp_backward_substitution_fu_258_grp_fu_417_p_ce),
    .grp_fu_421_p_din0(grp_backward_substitution_fu_258_grp_fu_421_p_din0),
    .grp_fu_421_p_din1(grp_backward_substitution_fu_258_grp_fu_421_p_din1),
    .grp_fu_421_p_dout0(grp_fu_421_p2),
    .grp_fu_421_p_ce(grp_backward_substitution_fu_258_grp_fu_421_p_ce),
    .grp_fu_425_p_din0(grp_backward_substitution_fu_258_grp_fu_425_p_din0),
    .grp_fu_425_p_din1(grp_backward_substitution_fu_258_grp_fu_425_p_din1),
    .grp_fu_425_p_dout0(grp_fu_425_p2),
    .grp_fu_425_p_ce(grp_backward_substitution_fu_258_grp_fu_425_p_ce),
    .grp_fu_429_p_din0(grp_backward_substitution_fu_258_grp_fu_429_p_din0),
    .grp_fu_429_p_din1(grp_backward_substitution_fu_258_grp_fu_429_p_din1),
    .grp_fu_429_p_dout0(grp_fu_429_p2),
    .grp_fu_429_p_ce(grp_backward_substitution_fu_258_grp_fu_429_p_ce),
    .grp_fu_433_p_din0(grp_backward_substitution_fu_258_grp_fu_433_p_din0),
    .grp_fu_433_p_din1(grp_backward_substitution_fu_258_grp_fu_433_p_din1),
    .grp_fu_433_p_dout0(grp_fu_433_p2),
    .grp_fu_433_p_ce(grp_backward_substitution_fu_258_grp_fu_433_p_ce),
    .grp_fu_437_p_din0(grp_backward_substitution_fu_258_grp_fu_437_p_din0),
    .grp_fu_437_p_din1(grp_backward_substitution_fu_258_grp_fu_437_p_din1),
    .grp_fu_437_p_dout0(grp_fu_437_p2),
    .grp_fu_437_p_ce(grp_backward_substitution_fu_258_grp_fu_437_p_ce),
    .grp_fu_441_p_din0(grp_backward_substitution_fu_258_grp_fu_441_p_din0),
    .grp_fu_441_p_din1(grp_backward_substitution_fu_258_grp_fu_441_p_din1),
    .grp_fu_441_p_dout0(grp_fu_441_p2),
    .grp_fu_441_p_ce(grp_backward_substitution_fu_258_grp_fu_441_p_ce),
    .grp_fu_445_p_din0(grp_backward_substitution_fu_258_grp_fu_445_p_din0),
    .grp_fu_445_p_din1(grp_backward_substitution_fu_258_grp_fu_445_p_din1),
    .grp_fu_445_p_dout0(grp_fu_445_p2),
    .grp_fu_445_p_ce(grp_backward_substitution_fu_258_grp_fu_445_p_ce),
    .grp_fu_449_p_din0(grp_backward_substitution_fu_258_grp_fu_449_p_din0),
    .grp_fu_449_p_din1(grp_backward_substitution_fu_258_grp_fu_449_p_din1),
    .grp_fu_449_p_dout0(grp_fu_449_p2),
    .grp_fu_449_p_ce(grp_backward_substitution_fu_258_grp_fu_449_p_ce),
    .grp_fu_453_p_din0(grp_backward_substitution_fu_258_grp_fu_453_p_din0),
    .grp_fu_453_p_din1(grp_backward_substitution_fu_258_grp_fu_453_p_din1),
    .grp_fu_453_p_dout0(grp_fu_453_p2),
    .grp_fu_453_p_ce(grp_backward_substitution_fu_258_grp_fu_453_p_ce),
    .grp_fu_457_p_din0(grp_backward_substitution_fu_258_grp_fu_457_p_din0),
    .grp_fu_457_p_din1(grp_backward_substitution_fu_258_grp_fu_457_p_din1),
    .grp_fu_457_p_dout0(grp_fu_457_p2),
    .grp_fu_457_p_ce(grp_backward_substitution_fu_258_grp_fu_457_p_ce),
    .grp_fu_461_p_din0(grp_backward_substitution_fu_258_grp_fu_461_p_din0),
    .grp_fu_461_p_din1(grp_backward_substitution_fu_258_grp_fu_461_p_din1),
    .grp_fu_461_p_dout0(grp_fu_461_p2),
    .grp_fu_461_p_ce(grp_backward_substitution_fu_258_grp_fu_461_p_ce),
    .grp_fu_465_p_din0(grp_backward_substitution_fu_258_grp_fu_465_p_din0),
    .grp_fu_465_p_din1(grp_backward_substitution_fu_258_grp_fu_465_p_din1),
    .grp_fu_465_p_dout0(grp_fu_465_p2),
    .grp_fu_465_p_ce(grp_backward_substitution_fu_258_grp_fu_465_p_ce),
    .grp_fu_469_p_din0(grp_backward_substitution_fu_258_grp_fu_469_p_din0),
    .grp_fu_469_p_din1(grp_backward_substitution_fu_258_grp_fu_469_p_din1),
    .grp_fu_469_p_dout0(grp_fu_469_p2),
    .grp_fu_469_p_ce(grp_backward_substitution_fu_258_grp_fu_469_p_ce),
    .grp_fu_473_p_din0(grp_backward_substitution_fu_258_grp_fu_473_p_din0),
    .grp_fu_473_p_din1(grp_backward_substitution_fu_258_grp_fu_473_p_din1),
    .grp_fu_473_p_dout0(grp_fu_473_p2),
    .grp_fu_473_p_ce(grp_backward_substitution_fu_258_grp_fu_473_p_ce)
);

ADMM_solver_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_ap_start),
    .ap_done(grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_ap_done),
    .ap_idle(grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_ap_idle),
    .ap_ready(grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_ap_ready),
    .x_address0(grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_x_address0),
    .x_ce0(grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_x_ce0),
    .x_q0(x_q0),
    .x_address1(grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_x_address1),
    .x_ce1(grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_x_ce1),
    .x_q1(x_q1),
    .current_state_address0(grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_current_state_address0),
    .current_state_ce0(grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_current_state_ce0),
    .current_state_q0(current_state_q0),
    .b_tmp_address0(grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_b_tmp_address0),
    .b_tmp_ce0(grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_b_tmp_ce0),
    .b_tmp_we0(grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_b_tmp_we0),
    .b_tmp_d0(grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_b_tmp_d0),
    .grp_fu_481_p_din0(grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_grp_fu_481_p_din0),
    .grp_fu_481_p_din1(grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_grp_fu_481_p_din1),
    .grp_fu_481_p_dout0(grp_fu_481_p2),
    .grp_fu_481_p_ce(grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_grp_fu_481_p_ce),
    .grp_fu_485_p_din0(grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_grp_fu_485_p_din0),
    .grp_fu_485_p_din1(grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_grp_fu_485_p_din1),
    .grp_fu_485_p_dout0(grp_fu_485_p2),
    .grp_fu_485_p_ce(grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_grp_fu_485_p_ce),
    .grp_fu_489_p_din0(grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_grp_fu_489_p_din0),
    .grp_fu_489_p_din1(grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_grp_fu_489_p_din1),
    .grp_fu_489_p_dout0(grp_fu_489_p2),
    .grp_fu_489_p_ce(grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_grp_fu_489_p_ce),
    .grp_fu_493_p_din0(grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_grp_fu_493_p_din0),
    .grp_fu_493_p_din1(grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_grp_fu_493_p_din1),
    .grp_fu_493_p_dout0(grp_fu_493_p2),
    .grp_fu_493_p_ce(grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_grp_fu_493_p_ce)
);

ADMM_solver_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_ap_start),
    .ap_done(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_ap_done),
    .ap_idle(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_ap_idle),
    .ap_ready(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_ap_ready),
    .b_tmp_address0(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_address0),
    .b_tmp_ce0(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_ce0),
    .b_tmp_q0(b_tmp_q0),
    .b_tmp_address1(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_address1),
    .b_tmp_ce1(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_ce1),
    .b_tmp_q1(b_tmp_q1),
    .b_tmp_address2(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_address2),
    .b_tmp_ce2(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_ce2),
    .b_tmp_q2(b_tmp_q2),
    .b_tmp_address3(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_address3),
    .b_tmp_ce3(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_ce3),
    .b_tmp_q3(b_tmp_q3),
    .b_tmp_address4(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_address4),
    .b_tmp_ce4(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_ce4),
    .b_tmp_q4(b_tmp_q4),
    .b_tmp_address5(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_address5),
    .b_tmp_ce5(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_ce5),
    .b_tmp_q5(b_tmp_q5),
    .b_tmp_address6(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_address6),
    .b_tmp_ce6(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_ce6),
    .b_tmp_q6(b_tmp_q6),
    .b_tmp_address7(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_address7),
    .b_tmp_ce7(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_ce7),
    .b_tmp_q7(b_tmp_q7),
    .b_tmp_address8(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_address8),
    .b_tmp_ce8(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_ce8),
    .b_tmp_q8(b_tmp_q8),
    .b_tmp_address9(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_address9),
    .b_tmp_ce9(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_ce9),
    .b_tmp_q9(b_tmp_q9),
    .b_tmp_address10(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_address10),
    .b_tmp_ce10(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_ce10),
    .b_tmp_q10(b_tmp_q10),
    .b_tmp_address11(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_address11),
    .b_tmp_ce11(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_ce11),
    .b_tmp_q11(b_tmp_q11),
    .b_tmp_address12(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_address12),
    .b_tmp_ce12(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_ce12),
    .b_tmp_q12(b_tmp_q12),
    .b_address0(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_address0),
    .b_ce0(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_ce0),
    .b_we0(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_we0),
    .b_d0(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_d0),
    .grp_fu_481_p_din0(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_grp_fu_481_p_din0),
    .grp_fu_481_p_din1(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_grp_fu_481_p_din1),
    .grp_fu_481_p_dout0(grp_fu_481_p2),
    .grp_fu_481_p_ce(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_grp_fu_481_p_ce),
    .grp_fu_485_p_din0(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_grp_fu_485_p_din0),
    .grp_fu_485_p_din1(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_grp_fu_485_p_din1),
    .grp_fu_485_p_dout0(grp_fu_485_p2),
    .grp_fu_485_p_ce(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_grp_fu_485_p_ce),
    .grp_fu_489_p_din0(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_grp_fu_489_p_din0),
    .grp_fu_489_p_din1(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_grp_fu_489_p_din1),
    .grp_fu_489_p_dout0(grp_fu_489_p2),
    .grp_fu_489_p_ce(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_grp_fu_489_p_ce),
    .grp_fu_493_p_din0(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_grp_fu_493_p_din0),
    .grp_fu_493_p_din1(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_grp_fu_493_p_din1),
    .grp_fu_493_p_dout0(grp_fu_493_p2),
    .grp_fu_493_p_ce(grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_grp_fu_493_p_ce)
);

ADMM_solver_mul_11s_32s_43_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 43 ))
mul_11s_32s_43_2_1_U199(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_413_p0),
    .din1(grp_fu_413_p1),
    .ce(grp_fu_413_ce),
    .dout(grp_fu_413_p2)
);

ADMM_solver_mul_22s_32s_53_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 22 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 53 ))
mul_22s_32s_53_2_1_U200(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_417_p0),
    .din1(grp_fu_417_p1),
    .ce(grp_fu_417_ce),
    .dout(grp_fu_417_p2)
);

ADMM_solver_mul_23s_32s_54_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 23 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 54 ))
mul_23s_32s_54_2_1_U201(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_421_p0),
    .din1(grp_fu_421_p1),
    .ce(grp_fu_421_ce),
    .dout(grp_fu_421_p2)
);

ADMM_solver_mul_23s_32s_54_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 23 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 54 ))
mul_23s_32s_54_2_1_U202(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_425_p0),
    .din1(grp_fu_425_p1),
    .ce(grp_fu_425_ce),
    .dout(grp_fu_425_p2)
);

ADMM_solver_mul_24s_32s_55_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 55 ))
mul_24s_32s_55_2_1_U203(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_429_p0),
    .din1(grp_fu_429_p1),
    .ce(grp_fu_429_ce),
    .dout(grp_fu_429_p2)
);

ADMM_solver_mul_25ns_32s_57_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 25 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 57 ))
mul_25ns_32s_57_2_1_U204(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_433_p0),
    .din1(grp_fu_433_p1),
    .ce(grp_fu_433_ce),
    .dout(grp_fu_433_p2)
);

ADMM_solver_mul_26s_32s_57_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 26 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 57 ))
mul_26s_32s_57_2_1_U205(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_437_p0),
    .din1(grp_fu_437_p1),
    .ce(grp_fu_437_ce),
    .dout(grp_fu_437_p2)
);

ADMM_solver_mul_26s_32s_57_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 26 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 57 ))
mul_26s_32s_57_2_1_U206(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_441_p0),
    .din1(grp_fu_441_p1),
    .ce(grp_fu_441_ce),
    .dout(grp_fu_441_p2)
);

ADMM_solver_mul_26s_32s_57_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 26 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 57 ))
mul_26s_32s_57_2_1_U207(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_445_p0),
    .din1(grp_fu_445_p1),
    .ce(grp_fu_445_ce),
    .dout(grp_fu_445_p2)
);

ADMM_solver_mul_26s_32s_57_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 26 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 57 ))
mul_26s_32s_57_2_1_U208(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_449_p0),
    .din1(grp_fu_449_p1),
    .ce(grp_fu_449_ce),
    .dout(grp_fu_449_p2)
);

ADMM_solver_mul_27s_32s_58_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 27 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 58 ))
mul_27s_32s_58_2_1_U209(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_453_p0),
    .din1(grp_fu_453_p1),
    .ce(grp_fu_453_ce),
    .dout(grp_fu_453_p2)
);

ADMM_solver_mul_30s_32s_61_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 30 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 61 ))
mul_30s_32s_61_2_1_U210(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_457_p0),
    .din1(grp_fu_457_p1),
    .ce(grp_fu_457_ce),
    .dout(grp_fu_457_p2)
);

ADMM_solver_mul_30s_32s_61_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 30 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 61 ))
mul_30s_32s_61_2_1_U211(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_461_p0),
    .din1(grp_fu_461_p1),
    .ce(grp_fu_461_ce),
    .dout(grp_fu_461_p2)
);

ADMM_solver_mul_30s_32s_61_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 30 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 61 ))
mul_30s_32s_61_2_1_U212(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_465_p0),
    .din1(grp_fu_465_p1),
    .ce(grp_fu_465_ce),
    .dout(grp_fu_465_p2)
);

ADMM_solver_mul_30s_32s_61_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 30 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 61 ))
mul_30s_32s_61_2_1_U213(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_469_p0),
    .din1(grp_fu_469_p1),
    .ce(grp_fu_469_ce),
    .dout(grp_fu_469_p2)
);

ADMM_solver_mul_33s_22ns_55_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 33 ),
    .din1_WIDTH( 22 ),
    .dout_WIDTH( 55 ))
mul_33s_22ns_55_2_1_U214(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_473_p0),
    .din1(grp_fu_473_p1),
    .ce(grp_fu_473_ce),
    .dout(grp_fu_473_p2)
);

ADMM_solver_mul_10ns_32s_42_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 42 ))
mul_10ns_32s_42_2_1_U215(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_477_p0),
    .din1(grp_fu_477_p1),
    .ce(grp_fu_477_ce),
    .dout(grp_fu_477_p2)
);

ADMM_solver_mul_32s_23ns_54_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 23 ),
    .dout_WIDTH( 54 ))
mul_32s_23ns_54_2_1_U216(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_481_p0),
    .din1(grp_fu_481_p1),
    .ce(grp_fu_481_ce),
    .dout(grp_fu_481_p2)
);

ADMM_solver_mul_32s_24s_54_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 54 ))
mul_32s_24s_54_2_1_U217(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_485_p0),
    .din1(grp_fu_485_p1),
    .ce(grp_fu_485_ce),
    .dout(grp_fu_485_p2)
);

ADMM_solver_mul_32s_26s_57_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 26 ),
    .dout_WIDTH( 57 ))
mul_32s_26s_57_2_1_U218(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_489_p0),
    .din1(grp_fu_489_p1),
    .ce(grp_fu_489_ce),
    .dout(grp_fu_489_p2)
);

ADMM_solver_mul_32s_26s_57_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 26 ),
    .dout_WIDTH( 57 ))
mul_32s_26s_57_2_1_U219(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_493_p0),
    .din1(grp_fu_493_p1),
    .ce(grp_fu_493_ce),
    .dout(grp_fu_493_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_ap_start_reg <= 1'b1;
        end else if ((grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_ap_ready == 1'b1)) begin
            grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_ap_start_reg <= 1'b1;
        end else if ((grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_ap_ready == 1'b1)) begin
            grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_backward_substitution_fu_258_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_backward_substitution_fu_258_ap_start_reg <= 1'b1;
        end else if ((grp_backward_substitution_fu_258_ap_ready == 1'b1)) begin
            grp_backward_substitution_fu_258_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_forward_substitution_fu_208_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_forward_substitution_fu_208_ap_start_reg <= 1'b1;
        end else if ((grp_forward_substitution_fu_208_ap_ready == 1'b1)) begin
            grp_forward_substitution_fu_208_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_forward_substitution_fu_208_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_backward_substitution_fu_258_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        b_address0 = grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        b_address0 = grp_forward_substitution_fu_208_b_address0;
    end else begin
        b_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        b_ce0 = grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        b_ce0 = grp_forward_substitution_fu_208_b_ce0;
    end else begin
        b_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        b_tmp_address0 = grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        b_tmp_address0 = grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_b_tmp_address0;
    end else begin
        b_tmp_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        b_tmp_ce0 = grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        b_tmp_ce0 = grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_b_tmp_ce0;
    end else begin
        b_tmp_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        b_tmp_ce1 = grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_ce1;
    end else begin
        b_tmp_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        b_tmp_ce10 = grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_ce10;
    end else begin
        b_tmp_ce10 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        b_tmp_ce11 = grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_ce11;
    end else begin
        b_tmp_ce11 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        b_tmp_ce12 = grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_ce12;
    end else begin
        b_tmp_ce12 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        b_tmp_ce2 = grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_ce2;
    end else begin
        b_tmp_ce2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        b_tmp_ce3 = grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_ce3;
    end else begin
        b_tmp_ce3 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        b_tmp_ce4 = grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_ce4;
    end else begin
        b_tmp_ce4 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        b_tmp_ce5 = grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_ce5;
    end else begin
        b_tmp_ce5 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        b_tmp_ce6 = grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_ce6;
    end else begin
        b_tmp_ce6 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        b_tmp_ce7 = grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_ce7;
    end else begin
        b_tmp_ce7 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        b_tmp_ce8 = grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_ce8;
    end else begin
        b_tmp_ce8 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        b_tmp_ce9 = grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_tmp_ce9;
    end else begin
        b_tmp_ce9 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        b_tmp_we0 = grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_b_tmp_we0;
    end else begin
        b_tmp_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        b_we0 = grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_b_we0;
    end else begin
        b_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_413_ce = grp_backward_substitution_fu_258_grp_fu_413_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_413_ce = grp_forward_substitution_fu_208_grp_fu_413_p_ce;
    end else begin
        grp_fu_413_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_413_p0 = grp_backward_substitution_fu_258_grp_fu_413_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_413_p0 = grp_forward_substitution_fu_208_grp_fu_413_p_din0;
    end else begin
        grp_fu_413_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_413_p1 = grp_backward_substitution_fu_258_grp_fu_413_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_413_p1 = grp_forward_substitution_fu_208_grp_fu_413_p_din1;
    end else begin
        grp_fu_413_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_417_ce = grp_backward_substitution_fu_258_grp_fu_417_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_417_ce = grp_forward_substitution_fu_208_grp_fu_417_p_ce;
    end else begin
        grp_fu_417_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_417_p0 = grp_backward_substitution_fu_258_grp_fu_417_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_417_p0 = grp_forward_substitution_fu_208_grp_fu_417_p_din0;
    end else begin
        grp_fu_417_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_417_p1 = grp_backward_substitution_fu_258_grp_fu_417_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_417_p1 = grp_forward_substitution_fu_208_grp_fu_417_p_din1;
    end else begin
        grp_fu_417_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_421_ce = grp_backward_substitution_fu_258_grp_fu_421_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_421_ce = grp_forward_substitution_fu_208_grp_fu_421_p_ce;
    end else begin
        grp_fu_421_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_421_p0 = grp_backward_substitution_fu_258_grp_fu_421_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_421_p0 = grp_forward_substitution_fu_208_grp_fu_421_p_din0;
    end else begin
        grp_fu_421_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_421_p1 = grp_backward_substitution_fu_258_grp_fu_421_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_421_p1 = grp_forward_substitution_fu_208_grp_fu_421_p_din1;
    end else begin
        grp_fu_421_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_425_ce = grp_backward_substitution_fu_258_grp_fu_425_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_425_ce = grp_forward_substitution_fu_208_grp_fu_425_p_ce;
    end else begin
        grp_fu_425_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_425_p0 = grp_backward_substitution_fu_258_grp_fu_425_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_425_p0 = grp_forward_substitution_fu_208_grp_fu_425_p_din0;
    end else begin
        grp_fu_425_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_425_p1 = grp_backward_substitution_fu_258_grp_fu_425_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_425_p1 = grp_forward_substitution_fu_208_grp_fu_425_p_din1;
    end else begin
        grp_fu_425_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_429_ce = grp_backward_substitution_fu_258_grp_fu_429_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_429_ce = grp_forward_substitution_fu_208_grp_fu_429_p_ce;
    end else begin
        grp_fu_429_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_429_p0 = grp_backward_substitution_fu_258_grp_fu_429_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_429_p0 = grp_forward_substitution_fu_208_grp_fu_429_p_din0;
    end else begin
        grp_fu_429_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_429_p1 = grp_backward_substitution_fu_258_grp_fu_429_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_429_p1 = grp_forward_substitution_fu_208_grp_fu_429_p_din1;
    end else begin
        grp_fu_429_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_433_ce = grp_backward_substitution_fu_258_grp_fu_433_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_433_ce = grp_forward_substitution_fu_208_grp_fu_433_p_ce;
    end else begin
        grp_fu_433_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_433_p0 = grp_backward_substitution_fu_258_grp_fu_433_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_433_p0 = grp_forward_substitution_fu_208_grp_fu_433_p_din0;
    end else begin
        grp_fu_433_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_433_p1 = grp_backward_substitution_fu_258_grp_fu_433_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_433_p1 = grp_forward_substitution_fu_208_grp_fu_433_p_din1;
    end else begin
        grp_fu_433_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_437_ce = grp_backward_substitution_fu_258_grp_fu_437_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_437_ce = grp_forward_substitution_fu_208_grp_fu_437_p_ce;
    end else begin
        grp_fu_437_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_437_p0 = grp_backward_substitution_fu_258_grp_fu_437_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_437_p0 = grp_forward_substitution_fu_208_grp_fu_437_p_din0;
    end else begin
        grp_fu_437_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_437_p1 = grp_backward_substitution_fu_258_grp_fu_437_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_437_p1 = grp_forward_substitution_fu_208_grp_fu_437_p_din1;
    end else begin
        grp_fu_437_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_441_ce = grp_backward_substitution_fu_258_grp_fu_441_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_441_ce = grp_forward_substitution_fu_208_grp_fu_441_p_ce;
    end else begin
        grp_fu_441_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_441_p0 = grp_backward_substitution_fu_258_grp_fu_441_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_441_p0 = grp_forward_substitution_fu_208_grp_fu_441_p_din0;
    end else begin
        grp_fu_441_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_441_p1 = grp_backward_substitution_fu_258_grp_fu_441_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_441_p1 = grp_forward_substitution_fu_208_grp_fu_441_p_din1;
    end else begin
        grp_fu_441_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_445_ce = grp_backward_substitution_fu_258_grp_fu_445_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_445_ce = grp_forward_substitution_fu_208_grp_fu_445_p_ce;
    end else begin
        grp_fu_445_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_445_p0 = grp_backward_substitution_fu_258_grp_fu_445_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_445_p0 = grp_forward_substitution_fu_208_grp_fu_445_p_din0;
    end else begin
        grp_fu_445_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_445_p1 = grp_backward_substitution_fu_258_grp_fu_445_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_445_p1 = grp_forward_substitution_fu_208_grp_fu_445_p_din1;
    end else begin
        grp_fu_445_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_449_ce = grp_backward_substitution_fu_258_grp_fu_449_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_449_ce = grp_forward_substitution_fu_208_grp_fu_449_p_ce;
    end else begin
        grp_fu_449_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_449_p0 = grp_backward_substitution_fu_258_grp_fu_449_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_449_p0 = grp_forward_substitution_fu_208_grp_fu_449_p_din0;
    end else begin
        grp_fu_449_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_449_p1 = grp_backward_substitution_fu_258_grp_fu_449_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_449_p1 = grp_forward_substitution_fu_208_grp_fu_449_p_din1;
    end else begin
        grp_fu_449_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_453_ce = grp_backward_substitution_fu_258_grp_fu_453_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_453_ce = grp_forward_substitution_fu_208_grp_fu_453_p_ce;
    end else begin
        grp_fu_453_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_453_p0 = grp_backward_substitution_fu_258_grp_fu_453_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_453_p0 = grp_forward_substitution_fu_208_grp_fu_453_p_din0;
    end else begin
        grp_fu_453_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_453_p1 = grp_backward_substitution_fu_258_grp_fu_453_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_453_p1 = grp_forward_substitution_fu_208_grp_fu_453_p_din1;
    end else begin
        grp_fu_453_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_457_ce = grp_backward_substitution_fu_258_grp_fu_457_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_457_ce = grp_forward_substitution_fu_208_grp_fu_457_p_ce;
    end else begin
        grp_fu_457_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_457_p0 = grp_backward_substitution_fu_258_grp_fu_457_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_457_p0 = grp_forward_substitution_fu_208_grp_fu_457_p_din0;
    end else begin
        grp_fu_457_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_457_p1 = grp_backward_substitution_fu_258_grp_fu_457_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_457_p1 = grp_forward_substitution_fu_208_grp_fu_457_p_din1;
    end else begin
        grp_fu_457_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_461_ce = grp_backward_substitution_fu_258_grp_fu_461_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_461_ce = grp_forward_substitution_fu_208_grp_fu_461_p_ce;
    end else begin
        grp_fu_461_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_461_p0 = grp_backward_substitution_fu_258_grp_fu_461_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_461_p0 = grp_forward_substitution_fu_208_grp_fu_461_p_din0;
    end else begin
        grp_fu_461_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_461_p1 = grp_backward_substitution_fu_258_grp_fu_461_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_461_p1 = grp_forward_substitution_fu_208_grp_fu_461_p_din1;
    end else begin
        grp_fu_461_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_465_ce = grp_backward_substitution_fu_258_grp_fu_465_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_465_ce = grp_forward_substitution_fu_208_grp_fu_465_p_ce;
    end else begin
        grp_fu_465_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_465_p0 = grp_backward_substitution_fu_258_grp_fu_465_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_465_p0 = grp_forward_substitution_fu_208_grp_fu_465_p_din0;
    end else begin
        grp_fu_465_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_465_p1 = grp_backward_substitution_fu_258_grp_fu_465_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_465_p1 = grp_forward_substitution_fu_208_grp_fu_465_p_din1;
    end else begin
        grp_fu_465_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_469_ce = grp_backward_substitution_fu_258_grp_fu_469_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_469_ce = grp_forward_substitution_fu_208_grp_fu_469_p_ce;
    end else begin
        grp_fu_469_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_469_p0 = grp_backward_substitution_fu_258_grp_fu_469_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_469_p0 = grp_forward_substitution_fu_208_grp_fu_469_p_din0;
    end else begin
        grp_fu_469_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_469_p1 = grp_backward_substitution_fu_258_grp_fu_469_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_469_p1 = grp_forward_substitution_fu_208_grp_fu_469_p_din1;
    end else begin
        grp_fu_469_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_473_ce = grp_backward_substitution_fu_258_grp_fu_473_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_473_ce = grp_forward_substitution_fu_208_grp_fu_473_p_ce;
    end else begin
        grp_fu_473_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_473_p0 = grp_backward_substitution_fu_258_grp_fu_473_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_473_p0 = grp_forward_substitution_fu_208_grp_fu_473_p_din0;
    end else begin
        grp_fu_473_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_473_p1 = grp_backward_substitution_fu_258_grp_fu_473_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_473_p1 = grp_forward_substitution_fu_208_grp_fu_473_p_din1;
    end else begin
        grp_fu_473_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_477_ce = grp_backward_substitution_fu_258_grp_fu_477_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_477_ce = grp_forward_substitution_fu_208_grp_fu_477_p_ce;
    end else begin
        grp_fu_477_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_477_p0 = grp_backward_substitution_fu_258_grp_fu_477_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_477_p0 = grp_forward_substitution_fu_208_grp_fu_477_p_din0;
    end else begin
        grp_fu_477_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_477_p1 = grp_backward_substitution_fu_258_grp_fu_477_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_477_p1 = grp_forward_substitution_fu_208_grp_fu_477_p_din1;
    end else begin
        grp_fu_477_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_481_ce = grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_grp_fu_481_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_481_ce = grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_grp_fu_481_p_ce;
    end else begin
        grp_fu_481_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_481_p0 = grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_grp_fu_481_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_481_p0 = grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_grp_fu_481_p_din0;
    end else begin
        grp_fu_481_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_481_p1 = grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_grp_fu_481_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_481_p1 = grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_grp_fu_481_p_din1;
    end else begin
        grp_fu_481_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_485_ce = grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_grp_fu_485_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_485_ce = grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_grp_fu_485_p_ce;
    end else begin
        grp_fu_485_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_485_p0 = grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_grp_fu_485_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_485_p0 = grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_grp_fu_485_p_din0;
    end else begin
        grp_fu_485_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_485_p1 = grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_grp_fu_485_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_485_p1 = grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_grp_fu_485_p_din1;
    end else begin
        grp_fu_485_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_489_ce = grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_grp_fu_489_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_489_ce = grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_grp_fu_489_p_ce;
    end else begin
        grp_fu_489_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_489_p0 = grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_grp_fu_489_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_489_p0 = grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_grp_fu_489_p_din0;
    end else begin
        grp_fu_489_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_489_p1 = grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_grp_fu_489_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_489_p1 = grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_grp_fu_489_p_din1;
    end else begin
        grp_fu_489_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_493_ce = grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_grp_fu_493_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_493_ce = grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_grp_fu_493_p_ce;
    end else begin
        grp_fu_493_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_493_p0 = grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_grp_fu_493_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_493_p0 = grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_grp_fu_493_p_din0;
    end else begin
        grp_fu_493_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_493_p1 = grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_grp_fu_493_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_493_p1 = grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_grp_fu_493_p_din1;
    end else begin
        grp_fu_493_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        tmp_address0 = grp_backward_substitution_fu_258_b_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_address0 = grp_forward_substitution_fu_208_x_address0;
    end else begin
        tmp_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        tmp_ce0 = grp_backward_substitution_fu_258_b_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_ce0 = grp_forward_substitution_fu_208_x_ce0;
    end else begin
        tmp_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_we0 = grp_forward_substitution_fu_208_x_we0;
    end else begin
        tmp_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        x_address0 = grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_x_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        x_address0 = grp_backward_substitution_fu_258_x_address0;
    end else begin
        x_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        x_ce0 = grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_x_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        x_ce0 = grp_backward_substitution_fu_258_x_ce0;
    end else begin
        x_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        x_ce1 = grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_x_ce1;
    end else begin
        x_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        x_we0 = grp_backward_substitution_fu_258_x_we0;
    end else begin
        x_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_forward_substitution_fu_208_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_backward_substitution_fu_258_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign current_state_address0 = grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_current_state_address0;

assign current_state_ce0 = grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_current_state_ce0;

assign grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_ap_start = grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_ap_start_reg;

assign grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_ap_start = grp_ADMM_iteration_Pipeline_AT_MUL_EXTERN_LOOP_fu_354_ap_start_reg;

assign grp_backward_substitution_fu_258_ap_start = grp_backward_substitution_fu_258_ap_start_reg;

assign grp_forward_substitution_fu_208_ap_start = grp_forward_substitution_fu_208_ap_start_reg;

assign x_address1 = grp_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_fu_307_x_address1;

assign x_d0 = grp_backward_substitution_fu_258_x_d0;

endmodule //ADMM_solver_ADMM_iteration
