// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module ADMM_solver_backward_substitution (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        b_address0,
        b_ce0,
        b_q0,
        x_address0,
        x_ce0,
        x_we0,
        x_d0,
        grp_fu_477_p_din0,
        grp_fu_477_p_din1,
        grp_fu_477_p_dout0,
        grp_fu_477_p_ce,
        grp_fu_413_p_din0,
        grp_fu_413_p_din1,
        grp_fu_413_p_dout0,
        grp_fu_413_p_ce,
        grp_fu_417_p_din0,
        grp_fu_417_p_din1,
        grp_fu_417_p_dout0,
        grp_fu_417_p_ce,
        grp_fu_421_p_din0,
        grp_fu_421_p_din1,
        grp_fu_421_p_dout0,
        grp_fu_421_p_ce,
        grp_fu_425_p_din0,
        grp_fu_425_p_din1,
        grp_fu_425_p_dout0,
        grp_fu_425_p_ce,
        grp_fu_429_p_din0,
        grp_fu_429_p_din1,
        grp_fu_429_p_dout0,
        grp_fu_429_p_ce,
        grp_fu_433_p_din0,
        grp_fu_433_p_din1,
        grp_fu_433_p_dout0,
        grp_fu_433_p_ce,
        grp_fu_437_p_din0,
        grp_fu_437_p_din1,
        grp_fu_437_p_dout0,
        grp_fu_437_p_ce,
        grp_fu_441_p_din0,
        grp_fu_441_p_din1,
        grp_fu_441_p_dout0,
        grp_fu_441_p_ce,
        grp_fu_445_p_din0,
        grp_fu_445_p_din1,
        grp_fu_445_p_dout0,
        grp_fu_445_p_ce,
        grp_fu_449_p_din0,
        grp_fu_449_p_din1,
        grp_fu_449_p_dout0,
        grp_fu_449_p_ce,
        grp_fu_453_p_din0,
        grp_fu_453_p_din1,
        grp_fu_453_p_dout0,
        grp_fu_453_p_ce,
        grp_fu_457_p_din0,
        grp_fu_457_p_din1,
        grp_fu_457_p_dout0,
        grp_fu_457_p_ce,
        grp_fu_461_p_din0,
        grp_fu_461_p_din1,
        grp_fu_461_p_dout0,
        grp_fu_461_p_ce,
        grp_fu_465_p_din0,
        grp_fu_465_p_din1,
        grp_fu_465_p_dout0,
        grp_fu_465_p_ce,
        grp_fu_469_p_din0,
        grp_fu_469_p_din1,
        grp_fu_469_p_dout0,
        grp_fu_469_p_ce,
        grp_fu_473_p_din0,
        grp_fu_473_p_din1,
        grp_fu_473_p_dout0,
        grp_fu_473_p_ce
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] b_address0;
output   b_ce0;
input  [31:0] b_q0;
output  [8:0] x_address0;
output   x_ce0;
output   x_we0;
output  [31:0] x_d0;
output  [9:0] grp_fu_477_p_din0;
output  [31:0] grp_fu_477_p_din1;
input  [41:0] grp_fu_477_p_dout0;
output   grp_fu_477_p_ce;
output  [10:0] grp_fu_413_p_din0;
output  [31:0] grp_fu_413_p_din1;
input  [42:0] grp_fu_413_p_dout0;
output   grp_fu_413_p_ce;
output  [21:0] grp_fu_417_p_din0;
output  [31:0] grp_fu_417_p_din1;
input  [52:0] grp_fu_417_p_dout0;
output   grp_fu_417_p_ce;
output  [22:0] grp_fu_421_p_din0;
output  [31:0] grp_fu_421_p_din1;
input  [53:0] grp_fu_421_p_dout0;
output   grp_fu_421_p_ce;
output  [22:0] grp_fu_425_p_din0;
output  [31:0] grp_fu_425_p_din1;
input  [53:0] grp_fu_425_p_dout0;
output   grp_fu_425_p_ce;
output  [23:0] grp_fu_429_p_din0;
output  [31:0] grp_fu_429_p_din1;
input  [54:0] grp_fu_429_p_dout0;
output   grp_fu_429_p_ce;
output  [24:0] grp_fu_433_p_din0;
output  [31:0] grp_fu_433_p_din1;
input  [56:0] grp_fu_433_p_dout0;
output   grp_fu_433_p_ce;
output  [25:0] grp_fu_437_p_din0;
output  [31:0] grp_fu_437_p_din1;
input  [56:0] grp_fu_437_p_dout0;
output   grp_fu_437_p_ce;
output  [25:0] grp_fu_441_p_din0;
output  [31:0] grp_fu_441_p_din1;
input  [56:0] grp_fu_441_p_dout0;
output   grp_fu_441_p_ce;
output  [25:0] grp_fu_445_p_din0;
output  [31:0] grp_fu_445_p_din1;
input  [56:0] grp_fu_445_p_dout0;
output   grp_fu_445_p_ce;
output  [25:0] grp_fu_449_p_din0;
output  [31:0] grp_fu_449_p_din1;
input  [56:0] grp_fu_449_p_dout0;
output   grp_fu_449_p_ce;
output  [26:0] grp_fu_453_p_din0;
output  [31:0] grp_fu_453_p_din1;
input  [57:0] grp_fu_453_p_dout0;
output   grp_fu_453_p_ce;
output  [29:0] grp_fu_457_p_din0;
output  [31:0] grp_fu_457_p_din1;
input  [60:0] grp_fu_457_p_dout0;
output   grp_fu_457_p_ce;
output  [29:0] grp_fu_461_p_din0;
output  [31:0] grp_fu_461_p_din1;
input  [60:0] grp_fu_461_p_dout0;
output   grp_fu_461_p_ce;
output  [29:0] grp_fu_465_p_din0;
output  [31:0] grp_fu_465_p_din1;
input  [60:0] grp_fu_465_p_dout0;
output   grp_fu_465_p_ce;
output  [29:0] grp_fu_469_p_din0;
output  [31:0] grp_fu_469_p_din1;
input  [60:0] grp_fu_469_p_dout0;
output   grp_fu_469_p_ce;
output  [32:0] grp_fu_473_p_din0;
output  [21:0] grp_fu_473_p_din1;
input  [54:0] grp_fu_473_p_dout0;
output   grp_fu_473_p_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_start;
wire    grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_done;
wire    grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_idle;
wire    grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_ready;
wire   [8:0] grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_b_address0;
wire    grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_b_ce0;
wire   [8:0] grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_x_address0;
wire    grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_x_ce0;
wire    grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_x_we0;
wire   [31:0] grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_x_d0;
wire   [9:0] grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_108_p_din0;
wire  signed [31:0] grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_108_p_din1;
wire    grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_108_p_ce;
wire  signed [10:0] grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_112_p_din0;
wire  signed [31:0] grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_112_p_din1;
wire    grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_112_p_ce;
wire  signed [21:0] grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_116_p_din0;
wire  signed [31:0] grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_116_p_din1;
wire    grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_116_p_ce;
wire  signed [22:0] grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_120_p_din0;
wire  signed [31:0] grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_120_p_din1;
wire    grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_120_p_ce;
wire  signed [22:0] grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_124_p_din0;
wire  signed [31:0] grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_124_p_din1;
wire    grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_124_p_ce;
wire  signed [23:0] grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_128_p_din0;
wire  signed [31:0] grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_128_p_din1;
wire    grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_128_p_ce;
wire   [24:0] grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_132_p_din0;
wire  signed [31:0] grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_132_p_din1;
wire    grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_132_p_ce;
wire  signed [25:0] grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_136_p_din0;
wire  signed [31:0] grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_136_p_din1;
wire    grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_136_p_ce;
wire  signed [25:0] grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_140_p_din0;
wire  signed [31:0] grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_140_p_din1;
wire    grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_140_p_ce;
wire  signed [25:0] grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_144_p_din0;
wire  signed [31:0] grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_144_p_din1;
wire    grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_144_p_ce;
wire  signed [25:0] grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_148_p_din0;
wire  signed [31:0] grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_148_p_din1;
wire    grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_148_p_ce;
wire  signed [26:0] grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_152_p_din0;
wire  signed [31:0] grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_152_p_din1;
wire    grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_152_p_ce;
wire  signed [29:0] grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_156_p_din0;
wire  signed [31:0] grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_156_p_din1;
wire    grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_156_p_ce;
wire  signed [29:0] grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_160_p_din0;
wire  signed [31:0] grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_160_p_din1;
wire    grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_160_p_ce;
wire  signed [29:0] grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_164_p_din0;
wire  signed [31:0] grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_164_p_din1;
wire    grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_164_p_ce;
wire  signed [29:0] grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_168_p_din0;
wire  signed [31:0] grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_168_p_din1;
wire    grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_168_p_ce;
wire  signed [32:0] grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_172_p_din0;
wire   [21:0] grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_172_p_din1;
wire    grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_172_p_ce;
reg    grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_fu_108_ce;
reg    grp_fu_112_ce;
reg    grp_fu_116_ce;
reg    grp_fu_120_ce;
reg    grp_fu_124_ce;
reg    grp_fu_128_ce;
reg    grp_fu_132_ce;
reg    grp_fu_136_ce;
reg    grp_fu_140_ce;
reg    grp_fu_144_ce;
reg    grp_fu_148_ce;
reg    grp_fu_152_ce;
reg    grp_fu_156_ce;
reg    grp_fu_160_ce;
reg    grp_fu_164_ce;
reg    grp_fu_168_ce;
reg    grp_fu_172_ce;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_start_reg = 1'b0;
end

ADMM_solver_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_start),
    .ap_done(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_done),
    .ap_idle(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_idle),
    .ap_ready(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_ready),
    .b_address0(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_b_address0),
    .b_ce0(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_b_ce0),
    .b_q0(b_q0),
    .x_address0(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_x_address0),
    .x_ce0(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_x_ce0),
    .x_we0(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_x_we0),
    .x_d0(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_x_d0),
    .grp_fu_108_p_din0(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_108_p_din0),
    .grp_fu_108_p_din1(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_108_p_din1),
    .grp_fu_108_p_dout0(grp_fu_477_p_dout0),
    .grp_fu_108_p_ce(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_108_p_ce),
    .grp_fu_112_p_din0(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_112_p_din0),
    .grp_fu_112_p_din1(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_112_p_din1),
    .grp_fu_112_p_dout0(grp_fu_413_p_dout0),
    .grp_fu_112_p_ce(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_112_p_ce),
    .grp_fu_116_p_din0(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_116_p_din0),
    .grp_fu_116_p_din1(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_116_p_din1),
    .grp_fu_116_p_dout0(grp_fu_417_p_dout0),
    .grp_fu_116_p_ce(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_116_p_ce),
    .grp_fu_120_p_din0(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_120_p_din0),
    .grp_fu_120_p_din1(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_120_p_din1),
    .grp_fu_120_p_dout0(grp_fu_421_p_dout0),
    .grp_fu_120_p_ce(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_120_p_ce),
    .grp_fu_124_p_din0(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_124_p_din0),
    .grp_fu_124_p_din1(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_124_p_din1),
    .grp_fu_124_p_dout0(grp_fu_425_p_dout0),
    .grp_fu_124_p_ce(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_124_p_ce),
    .grp_fu_128_p_din0(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_128_p_din0),
    .grp_fu_128_p_din1(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_128_p_din1),
    .grp_fu_128_p_dout0(grp_fu_429_p_dout0),
    .grp_fu_128_p_ce(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_128_p_ce),
    .grp_fu_132_p_din0(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_132_p_din0),
    .grp_fu_132_p_din1(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_132_p_din1),
    .grp_fu_132_p_dout0(grp_fu_433_p_dout0),
    .grp_fu_132_p_ce(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_132_p_ce),
    .grp_fu_136_p_din0(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_136_p_din0),
    .grp_fu_136_p_din1(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_136_p_din1),
    .grp_fu_136_p_dout0(grp_fu_437_p_dout0),
    .grp_fu_136_p_ce(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_136_p_ce),
    .grp_fu_140_p_din0(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_140_p_din0),
    .grp_fu_140_p_din1(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_140_p_din1),
    .grp_fu_140_p_dout0(grp_fu_441_p_dout0),
    .grp_fu_140_p_ce(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_140_p_ce),
    .grp_fu_144_p_din0(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_144_p_din0),
    .grp_fu_144_p_din1(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_144_p_din1),
    .grp_fu_144_p_dout0(grp_fu_445_p_dout0),
    .grp_fu_144_p_ce(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_144_p_ce),
    .grp_fu_148_p_din0(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_148_p_din0),
    .grp_fu_148_p_din1(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_148_p_din1),
    .grp_fu_148_p_dout0(grp_fu_449_p_dout0),
    .grp_fu_148_p_ce(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_148_p_ce),
    .grp_fu_152_p_din0(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_152_p_din0),
    .grp_fu_152_p_din1(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_152_p_din1),
    .grp_fu_152_p_dout0(grp_fu_453_p_dout0),
    .grp_fu_152_p_ce(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_152_p_ce),
    .grp_fu_156_p_din0(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_156_p_din0),
    .grp_fu_156_p_din1(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_156_p_din1),
    .grp_fu_156_p_dout0(grp_fu_457_p_dout0),
    .grp_fu_156_p_ce(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_156_p_ce),
    .grp_fu_160_p_din0(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_160_p_din0),
    .grp_fu_160_p_din1(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_160_p_din1),
    .grp_fu_160_p_dout0(grp_fu_461_p_dout0),
    .grp_fu_160_p_ce(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_160_p_ce),
    .grp_fu_164_p_din0(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_164_p_din0),
    .grp_fu_164_p_din1(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_164_p_din1),
    .grp_fu_164_p_dout0(grp_fu_465_p_dout0),
    .grp_fu_164_p_ce(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_164_p_ce),
    .grp_fu_168_p_din0(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_168_p_din0),
    .grp_fu_168_p_din1(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_168_p_din1),
    .grp_fu_168_p_dout0(grp_fu_469_p_dout0),
    .grp_fu_168_p_ce(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_168_p_ce),
    .grp_fu_172_p_din0(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_172_p_din0),
    .grp_fu_172_p_din1(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_172_p_din1),
    .grp_fu_172_p_dout0(grp_fu_473_p_dout0),
    .grp_fu_172_p_ce(grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_172_p_ce)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_start_reg <= 1'b1;
        end else if ((grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_ready == 1'b1)) begin
            grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_108_ce = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_108_p_ce;
    end else begin
        grp_fu_108_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_112_ce = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_112_p_ce;
    end else begin
        grp_fu_112_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_116_ce = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_116_p_ce;
    end else begin
        grp_fu_116_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_120_ce = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_120_p_ce;
    end else begin
        grp_fu_120_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_124_ce = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_124_p_ce;
    end else begin
        grp_fu_124_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_128_ce = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_128_p_ce;
    end else begin
        grp_fu_128_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_132_ce = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_132_p_ce;
    end else begin
        grp_fu_132_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_136_ce = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_136_p_ce;
    end else begin
        grp_fu_136_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_140_ce = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_140_p_ce;
    end else begin
        grp_fu_140_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_144_ce = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_144_p_ce;
    end else begin
        grp_fu_144_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_148_ce = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_148_p_ce;
    end else begin
        grp_fu_148_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_152_ce = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_152_p_ce;
    end else begin
        grp_fu_152_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_156_ce = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_156_p_ce;
    end else begin
        grp_fu_156_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_160_ce = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_160_p_ce;
    end else begin
        grp_fu_160_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_164_ce = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_164_p_ce;
    end else begin
        grp_fu_164_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_168_ce = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_168_p_ce;
    end else begin
        grp_fu_168_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_172_ce = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_172_p_ce;
    end else begin
        grp_fu_172_ce = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign b_address0 = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_b_address0;

assign b_ce0 = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_b_ce0;

assign grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_start = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_ap_start_reg;

assign grp_fu_413_p_ce = grp_fu_112_ce;

assign grp_fu_413_p_din0 = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_112_p_din0;

assign grp_fu_413_p_din1 = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_112_p_din1;

assign grp_fu_417_p_ce = grp_fu_116_ce;

assign grp_fu_417_p_din0 = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_116_p_din0;

assign grp_fu_417_p_din1 = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_116_p_din1;

assign grp_fu_421_p_ce = grp_fu_120_ce;

assign grp_fu_421_p_din0 = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_120_p_din0;

assign grp_fu_421_p_din1 = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_120_p_din1;

assign grp_fu_425_p_ce = grp_fu_124_ce;

assign grp_fu_425_p_din0 = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_124_p_din0;

assign grp_fu_425_p_din1 = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_124_p_din1;

assign grp_fu_429_p_ce = grp_fu_128_ce;

assign grp_fu_429_p_din0 = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_128_p_din0;

assign grp_fu_429_p_din1 = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_128_p_din1;

assign grp_fu_433_p_ce = grp_fu_132_ce;

assign grp_fu_433_p_din0 = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_132_p_din0;

assign grp_fu_433_p_din1 = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_132_p_din1;

assign grp_fu_437_p_ce = grp_fu_136_ce;

assign grp_fu_437_p_din0 = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_136_p_din0;

assign grp_fu_437_p_din1 = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_136_p_din1;

assign grp_fu_441_p_ce = grp_fu_140_ce;

assign grp_fu_441_p_din0 = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_140_p_din0;

assign grp_fu_441_p_din1 = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_140_p_din1;

assign grp_fu_445_p_ce = grp_fu_144_ce;

assign grp_fu_445_p_din0 = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_144_p_din0;

assign grp_fu_445_p_din1 = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_144_p_din1;

assign grp_fu_449_p_ce = grp_fu_148_ce;

assign grp_fu_449_p_din0 = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_148_p_din0;

assign grp_fu_449_p_din1 = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_148_p_din1;

assign grp_fu_453_p_ce = grp_fu_152_ce;

assign grp_fu_453_p_din0 = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_152_p_din0;

assign grp_fu_453_p_din1 = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_152_p_din1;

assign grp_fu_457_p_ce = grp_fu_156_ce;

assign grp_fu_457_p_din0 = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_156_p_din0;

assign grp_fu_457_p_din1 = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_156_p_din1;

assign grp_fu_461_p_ce = grp_fu_160_ce;

assign grp_fu_461_p_din0 = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_160_p_din0;

assign grp_fu_461_p_din1 = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_160_p_din1;

assign grp_fu_465_p_ce = grp_fu_164_ce;

assign grp_fu_465_p_din0 = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_164_p_din0;

assign grp_fu_465_p_din1 = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_164_p_din1;

assign grp_fu_469_p_ce = grp_fu_168_ce;

assign grp_fu_469_p_din0 = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_168_p_din0;

assign grp_fu_469_p_din1 = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_168_p_din1;

assign grp_fu_473_p_ce = grp_fu_172_ce;

assign grp_fu_473_p_din0 = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_172_p_din0;

assign grp_fu_473_p_din1 = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_172_p_din1;

assign grp_fu_477_p_ce = grp_fu_108_ce;

assign grp_fu_477_p_din0 = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_108_p_din0;

assign grp_fu_477_p_din1 = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_grp_fu_108_p_din1;

assign x_address0 = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_x_address0;

assign x_ce0 = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_x_ce0;

assign x_d0 = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_x_d0;

assign x_we0 = grp_backward_substitution_Pipeline_BACK_SUBST_EXTERN_LOOP_fu_58_x_we0;

endmodule //ADMM_solver_backward_substitution
