// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module ADMM_solver_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_address0,
        x_ce0,
        x_q0,
        x_address1,
        x_ce1,
        x_q1,
        current_state_address0,
        current_state_ce0,
        current_state_q0,
        b_tmp_address0,
        b_tmp_ce0,
        b_tmp_we0,
        b_tmp_d0,
        grp_fu_481_p_din0,
        grp_fu_481_p_din1,
        grp_fu_481_p_dout0,
        grp_fu_481_p_ce,
        grp_fu_485_p_din0,
        grp_fu_485_p_din1,
        grp_fu_485_p_dout0,
        grp_fu_485_p_ce,
        grp_fu_489_p_din0,
        grp_fu_489_p_din1,
        grp_fu_489_p_dout0,
        grp_fu_489_p_ce,
        grp_fu_493_p_din0,
        grp_fu_493_p_din1,
        grp_fu_493_p_dout0,
        grp_fu_493_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 5'd1;
parameter    ap_ST_fsm_pp0_stage1 = 5'd2;
parameter    ap_ST_fsm_pp0_stage2 = 5'd4;
parameter    ap_ST_fsm_pp0_stage3 = 5'd8;
parameter    ap_ST_fsm_pp0_stage4 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] x_address0;
output   x_ce0;
input  [31:0] x_q0;
output  [8:0] x_address1;
output   x_ce1;
input  [31:0] x_q1;
output  [3:0] current_state_address0;
output   current_state_ce0;
input  [31:0] current_state_q0;
output  [8:0] b_tmp_address0;
output   b_tmp_ce0;
output   b_tmp_we0;
output  [31:0] b_tmp_d0;
output  [31:0] grp_fu_481_p_din0;
output  [22:0] grp_fu_481_p_din1;
input  [53:0] grp_fu_481_p_dout0;
output   grp_fu_481_p_ce;
output  [31:0] grp_fu_485_p_din0;
output  [23:0] grp_fu_485_p_din1;
input  [53:0] grp_fu_485_p_dout0;
output   grp_fu_485_p_ce;
output  [31:0] grp_fu_489_p_din0;
output  [25:0] grp_fu_489_p_din1;
input  [56:0] grp_fu_489_p_dout0;
output   grp_fu_489_p_ce;
output  [31:0] grp_fu_493_p_din0;
output  [25:0] grp_fu_493_p_din1;
input  [56:0] grp_fu_493_p_dout0;
output   grp_fu_493_p_ce;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln99_reg_2898;
reg    ap_condition_exit_pp0_iter0_stage4;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [8:0] p_ZL16A_sparse_indexes_0_address0;
wire   [8:0] p_ZL16A_sparse_indexes_0_q0;
wire   [8:0] p_ZL13A_sparse_data_0_address0;
wire   [23:0] p_ZL13A_sparse_data_0_q0;
wire   [8:0] p_ZL16A_sparse_indexes_1_address0;
wire   [8:0] p_ZL16A_sparse_indexes_1_q0;
wire   [8:0] p_ZL13A_sparse_data_1_address0;
wire   [25:0] p_ZL13A_sparse_data_1_q0;
wire   [8:0] p_ZL16A_sparse_indexes_2_address0;
wire   [8:0] p_ZL16A_sparse_indexes_2_q0;
wire   [8:0] p_ZL13A_sparse_data_2_address0;
wire   [25:0] p_ZL13A_sparse_data_2_q0;
wire   [8:0] p_ZL16A_sparse_indexes_3_address0;
wire   [8:0] p_ZL16A_sparse_indexes_3_q0;
wire   [8:0] p_ZL13A_sparse_data_3_address0;
wire   [25:0] p_ZL13A_sparse_data_3_q0;
wire   [8:0] p_ZL16A_sparse_indexes_4_address0;
wire   [8:0] p_ZL16A_sparse_indexes_4_q0;
wire   [8:0] p_ZL13A_sparse_data_4_address0;
wire   [25:0] p_ZL13A_sparse_data_4_q0;
wire   [8:0] p_ZL16A_sparse_indexes_5_address0;
wire   [8:0] p_ZL16A_sparse_indexes_5_q0;
wire   [8:0] p_ZL13A_sparse_data_5_address0;
wire   [23:0] p_ZL13A_sparse_data_5_q0;
wire   [8:0] p_ZL16A_sparse_indexes_6_address0;
wire   [8:0] p_ZL16A_sparse_indexes_6_q0;
wire   [8:0] p_ZL13A_sparse_data_6_address0;
wire   [23:0] p_ZL13A_sparse_data_6_q0;
wire   [8:0] p_ZL16A_sparse_indexes_7_address0;
wire   [8:0] p_ZL16A_sparse_indexes_7_q0;
wire   [8:0] p_ZL13A_sparse_data_7_address0;
wire   [22:0] p_ZL13A_sparse_data_7_q0;
wire   [8:0] p_ZL16A_sparse_indexes_8_address0;
wire   [8:0] p_ZL16A_sparse_indexes_8_q0;
wire   [8:0] p_ZL13A_sparse_data_8_address0;
wire   [22:0] p_ZL13A_sparse_data_8_q0;
wire   [31:0] y_q0;
reg   [8:0] i_3_reg_2891;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln99_fu_614_p2;
reg   [0:0] icmp_ln99_reg_2898_pp0_iter1_reg;
reg   [0:0] icmp_ln99_reg_2898_pp0_iter2_reg;
reg   [0:0] icmp_ln99_reg_2898_pp0_iter3_reg;
wire   [63:0] zext_ln99_fu_620_p1;
reg   [63:0] zext_ln99_reg_2902;
reg   [63:0] zext_ln99_reg_2902_pp0_iter1_reg;
reg   [63:0] zext_ln99_reg_2902_pp0_iter2_reg;
reg   [63:0] zext_ln99_reg_2902_pp0_iter3_reg;
reg   [63:0] zext_ln99_reg_2902_pp0_iter4_reg;
reg  signed [23:0] p_ZL13A_sparse_data_0_load_reg_2999;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
reg   [25:0] p_ZL13A_sparse_data_1_load_reg_3009;
reg   [8:0] p_ZL16A_sparse_indexes_2_load_reg_3019;
reg   [25:0] p_ZL13A_sparse_data_2_load_reg_3024;
reg   [8:0] p_ZL16A_sparse_indexes_3_load_reg_3029;
reg   [25:0] p_ZL13A_sparse_data_3_load_reg_3034;
reg   [8:0] p_ZL16A_sparse_indexes_4_load_reg_3039;
reg   [25:0] p_ZL13A_sparse_data_4_load_reg_3044;
reg   [8:0] p_ZL16A_sparse_indexes_5_load_reg_3049;
reg   [23:0] p_ZL13A_sparse_data_5_load_reg_3054;
reg   [8:0] p_ZL16A_sparse_indexes_6_load_reg_3059;
reg   [23:0] p_ZL13A_sparse_data_6_load_reg_3064;
reg   [8:0] p_ZL16A_sparse_indexes_7_load_reg_3069;
reg   [22:0] p_ZL13A_sparse_data_7_load_reg_3074;
reg   [8:0] p_ZL16A_sparse_indexes_8_load_reg_3079;
reg   [22:0] p_ZL13A_sparse_data_8_load_reg_3084;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
wire  signed [56:0] sext_ln102_2_fu_661_p1;
wire  signed [56:0] sext_ln102_3_fu_665_p1;
reg   [0:0] tmp_reg_3119;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_11001;
reg   [31:0] Axi_reg_3126;
reg   [0:0] tmp_296_reg_3131;
reg   [0:0] tmp_298_reg_3136;
reg   [56:0] mul_ln102_1_reg_3142;
reg   [0:0] tmp_301_reg_3147;
wire  signed [56:0] sext_ln102_5_fu_712_p1;
wire  signed [56:0] sext_ln102_6_fu_716_p1;
wire  signed [56:0] sext_ln102_8_fu_721_p1;
wire  signed [56:0] sext_ln102_9_fu_725_p1;
wire   [31:0] Axi_1_fu_746_p2;
reg   [31:0] Axi_1_reg_3182;
wire    ap_block_pp0_stage4_11001;
wire   [0:0] and_ln102_1_fu_803_p2;
reg   [0:0] and_ln102_1_reg_3187;
wire   [0:0] or_ln102_1_fu_826_p2;
reg   [0:0] or_ln102_1_reg_3192;
reg   [56:0] mul_ln102_2_reg_3197;
reg   [0:0] tmp_306_reg_3202;
reg   [56:0] mul_ln102_3_reg_3207;
reg   [0:0] tmp_311_reg_3212;
wire  signed [56:0] sext_ln102_11_fu_840_p1;
wire  signed [56:0] sext_ln102_12_fu_844_p1;
wire  signed [53:0] sext_ln102_14_fu_849_p1;
wire  signed [53:0] sext_ln102_15_fu_853_p1;
wire   [0:0] icmp_ln106_fu_866_p2;
reg   [0:0] icmp_ln106_reg_3247;
reg   [0:0] icmp_ln106_reg_3247_pp0_iter1_reg;
reg   [0:0] icmp_ln106_reg_3247_pp0_iter2_reg;
reg   [0:0] icmp_ln106_reg_3247_pp0_iter3_reg;
wire   [0:0] icmp_ln108_fu_871_p2;
reg   [0:0] icmp_ln108_reg_3254;
reg   [0:0] icmp_ln108_reg_3254_pp0_iter1_reg;
reg   [0:0] icmp_ln108_reg_3254_pp0_iter2_reg;
reg   [0:0] icmp_ln108_reg_3254_pp0_iter3_reg;
wire   [56:0] add_ln102_fu_906_p2;
reg   [56:0] add_ln102_reg_3260;
reg   [0:0] tmp_300_reg_3265;
wire   [31:0] Axi_3_fu_940_p2;
reg   [31:0] Axi_3_reg_3271;
wire   [0:0] tmp_303_fu_946_p3;
reg   [0:0] tmp_303_reg_3276;
wire   [0:0] and_ln102_3_fu_960_p2;
reg   [0:0] and_ln102_3_reg_3282;
wire   [0:0] icmp_ln102_fu_976_p2;
reg   [0:0] icmp_ln102_reg_3289;
wire   [0:0] icmp_ln102_1_fu_992_p2;
reg   [0:0] icmp_ln102_1_reg_3294;
wire   [0:0] icmp_ln102_2_fu_998_p2;
reg   [0:0] icmp_ln102_2_reg_3301;
reg   [56:0] mul_ln102_4_reg_3306;
reg   [0:0] tmp_316_reg_3311;
reg  signed [53:0] mul_ln102_5_reg_3316;
reg  signed [53:0] mul_ln102_5_reg_3316_pp0_iter2_reg;
reg   [0:0] tmp_321_reg_3322;
reg   [0:0] tmp_321_reg_3322_pp0_iter2_reg;
wire  signed [53:0] sext_ln102_18_fu_1004_p1;
wire  signed [53:0] sext_ln102_19_fu_1008_p1;
wire   [53:0] zext_ln102_18_fu_1013_p1;
wire  signed [53:0] sext_ln102_22_fu_1017_p1;
wire   [56:0] add_ln102_2_fu_1136_p2;
reg   [56:0] add_ln102_2_reg_3352;
reg   [0:0] tmp_305_reg_3358;
reg   [31:0] Axi_4_reg_3364;
wire   [0:0] icmp_ln102_3_fu_1169_p2;
reg   [0:0] icmp_ln102_3_reg_3369;
wire   [0:0] icmp_ln102_4_fu_1185_p2;
reg   [0:0] icmp_ln102_4_reg_3374;
wire   [0:0] icmp_ln102_5_fu_1191_p2;
reg   [0:0] icmp_ln102_5_reg_3381;
reg  signed [53:0] mul_ln102_6_reg_3386;
reg  signed [53:0] mul_ln102_6_reg_3386_pp0_iter2_reg;
reg   [0:0] tmp_325_reg_3392;
reg   [0:0] tmp_325_reg_3392_pp0_iter2_reg;
reg  signed [53:0] mul_ln102_7_reg_3397;
reg  signed [53:0] mul_ln102_7_reg_3397_pp0_iter2_reg;
reg   [0:0] tmp_329_reg_3403;
reg   [0:0] tmp_329_reg_3403_pp0_iter2_reg;
wire   [53:0] zext_ln102_19_fu_1197_p1;
wire  signed [53:0] sext_ln102_25_fu_1201_p1;
wire   [31:0] Axi_5_fu_1216_p2;
reg   [31:0] Axi_5_reg_3418;
wire   [0:0] and_ln102_12_fu_1294_p2;
reg   [0:0] and_ln102_12_reg_3423;
wire   [0:0] or_ln102_5_fu_1323_p2;
reg   [0:0] or_ln102_5_reg_3428;
reg  signed [53:0] mul_ln102_8_reg_3433;
reg  signed [53:0] mul_ln102_8_reg_3433_pp0_iter2_reg;
reg   [0:0] tmp_333_reg_3439;
reg   [0:0] tmp_333_reg_3439_pp0_iter2_reg;
wire   [56:0] add_ln102_4_fu_1354_p2;
reg   [56:0] add_ln102_4_reg_3444;
reg   [0:0] tmp_310_reg_3449;
wire   [31:0] Axi_7_fu_1388_p2;
reg   [31:0] Axi_7_reg_3455;
wire   [0:0] tmp_313_fu_1394_p3;
reg   [0:0] tmp_313_reg_3460;
wire   [0:0] and_ln102_15_fu_1408_p2;
reg   [0:0] and_ln102_15_reg_3466;
wire   [0:0] icmp_ln102_6_fu_1424_p2;
reg   [0:0] icmp_ln102_6_reg_3473;
wire   [0:0] icmp_ln102_7_fu_1440_p2;
reg   [0:0] icmp_ln102_7_reg_3478;
wire   [0:0] icmp_ln102_8_fu_1446_p2;
reg   [0:0] icmp_ln102_8_reg_3485;
wire   [56:0] add_ln102_6_fu_1562_p2;
reg   [56:0] add_ln102_6_reg_3490;
reg   [0:0] tmp_315_reg_3496;
reg   [31:0] Axi_8_reg_3502;
wire   [0:0] icmp_ln102_9_fu_1595_p2;
reg   [0:0] icmp_ln102_9_reg_3507;
wire   [0:0] icmp_ln102_10_fu_1611_p2;
reg   [0:0] icmp_ln102_10_reg_3512;
wire   [0:0] icmp_ln102_11_fu_1617_p2;
reg   [0:0] icmp_ln102_11_reg_3519;
wire   [31:0] select_ln102_17_fu_1754_p3;
reg   [31:0] select_ln102_17_reg_3524;
reg   [0:0] tmp_320_reg_3529;
reg   [0:0] tmp_322_reg_3536;
wire   [31:0] Axi_11_fu_1816_p2;
reg   [31:0] Axi_11_reg_3542;
reg   [0:0] tmp_323_reg_3547;
reg   [0:0] tmp_324_reg_3555;
reg   [31:0] Axi_12_reg_3562;
reg   [0:0] tmp_326_reg_3567;
wire   [31:0] select_ln102_21_fu_2063_p3;
reg   [31:0] select_ln102_21_reg_3573;
reg   [0:0] tmp_328_reg_3578;
reg   [0:0] tmp_330_reg_3585;
wire   [31:0] Axi_15_fu_2125_p2;
reg   [31:0] Axi_15_reg_3591;
reg   [0:0] tmp_331_reg_3596;
reg   [0:0] tmp_332_reg_3604;
reg   [31:0] Axi_16_reg_3611;
reg   [0:0] tmp_334_reg_3616;
reg   [8:0] y_addr_reg_3622;
reg   [8:0] y_addr_reg_3622_pp0_iter4_reg;
wire  signed [31:0] Axi_18_fu_2372_p3;
reg  signed [31:0] Axi_18_reg_3627;
reg  signed [31:0] y_load_reg_3633;
reg  signed [31:0] y_load_reg_3633_pp0_iter4_reg;
reg  signed [23:0] trunc_ln109_1_reg_3638;
wire   [24:0] trunc_ln119_fu_2390_p1;
reg   [24:0] trunc_ln119_reg_3644;
reg   [24:0] trunc_ln119_reg_3644_pp0_iter4_reg;
wire   [24:0] trunc_ln105_1_fu_2468_p1;
reg   [24:0] trunc_ln105_1_reg_3649;
reg   [24:0] trunc_ln105_1_reg_3649_pp0_iter4_reg;
wire   [0:0] icmp_ln110_fu_2472_p2;
reg   [0:0] icmp_ln110_reg_3656;
wire   [0:0] tmp_338_fu_2478_p3;
reg   [0:0] tmp_338_reg_3662;
wire   [31:0] select_ln110_fu_2492_p3;
reg   [31:0] select_ln110_reg_3667;
wire   [5:0] trunc_ln110_fu_2507_p1;
reg   [5:0] trunc_ln110_reg_3673;
wire   [5:0] add_ln110_fu_2511_p2;
reg   [5:0] add_ln110_reg_3678;
wire   [63:0] LD_fu_2581_p5;
reg   [63:0] LD_reg_3683;
wire   [63:0] bitcast_ln758_fu_2593_p1;
reg   [63:0] bitcast_ln758_reg_3693;
wire   [24:0] trunc_ln105_fu_2597_p1;
reg   [24:0] trunc_ln105_reg_3698;
wire   [0:0] grp_fu_556_p2;
reg   [0:0] tmp_226_reg_3703;
wire   [24:0] select_ln110_2_fu_2601_p3;
reg   [24:0] select_ln110_2_reg_3709;
wire   [24:0] select_ln112_fu_2607_p3;
reg   [24:0] select_ln112_reg_3714;
wire   [0:0] xor_ln108_fu_2618_p2;
reg   [0:0] xor_ln108_reg_3719;
wire   [0:0] and_ln110_fu_2634_p2;
reg   [0:0] and_ln110_reg_3724;
wire   [0:0] and_ln110_2_fu_2649_p2;
reg   [0:0] and_ln110_2_reg_3729;
wire   [33:0] add_ln119_fu_2707_p2;
reg   [33:0] add_ln119_reg_3734;
reg   [0:0] tmp_340_reg_3739;
reg   [0:0] tmp_341_reg_3745;
reg   [1:0] tmp_228_reg_3751;
wire   [23:0] trunc_ln121_fu_2737_p1;
reg   [23:0] trunc_ln121_reg_3757;
wire   [31:0] select_ln121_1_fu_2876_p3;
reg   [31:0] select_ln121_1_reg_3762;
wire    ap_block_pp0_stage0_subdone;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln102_fu_642_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln102_2_fu_647_p1;
wire   [63:0] zext_ln102_4_fu_670_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] zext_ln102_6_fu_674_p1;
wire   [63:0] zext_ln102_8_fu_730_p1;
wire    ap_block_pp0_stage3;
wire   [63:0] zext_ln102_10_fu_734_p1;
wire   [63:0] zext_ln102_12_fu_858_p1;
wire    ap_block_pp0_stage4;
wire   [63:0] zext_ln102_14_fu_862_p1;
wire   [63:0] zext_ln102_16_fu_1022_p1;
reg   [8:0] i_fu_198;
wire   [8:0] add_ln99_fu_738_p2;
wire    ap_loop_init;
reg   [8:0] ap_sig_allocacmp_i_3;
reg    p_ZL16A_sparse_indexes_0_ce0_local;
reg    p_ZL13A_sparse_data_0_ce0_local;
reg    p_ZL16A_sparse_indexes_1_ce0_local;
reg    p_ZL13A_sparse_data_1_ce0_local;
reg    p_ZL16A_sparse_indexes_2_ce0_local;
reg    p_ZL13A_sparse_data_2_ce0_local;
reg    p_ZL16A_sparse_indexes_3_ce0_local;
reg    p_ZL13A_sparse_data_3_ce0_local;
reg    p_ZL16A_sparse_indexes_4_ce0_local;
reg    p_ZL13A_sparse_data_4_ce0_local;
reg    p_ZL16A_sparse_indexes_5_ce0_local;
reg    p_ZL13A_sparse_data_5_ce0_local;
reg    p_ZL16A_sparse_indexes_6_ce0_local;
reg    p_ZL13A_sparse_data_6_ce0_local;
reg    p_ZL16A_sparse_indexes_7_ce0_local;
reg    p_ZL13A_sparse_data_7_ce0_local;
reg    p_ZL16A_sparse_indexes_8_ce0_local;
reg    p_ZL13A_sparse_data_8_ce0_local;
reg    x_ce1_local;
reg   [8:0] x_address1_local;
reg    x_ce0_local;
reg   [8:0] x_address0_local;
reg    y_ce0_local;
reg   [8:0] y_address0_local;
reg    y_we0_local;
wire   [31:0] yi_1_fu_2800_p3;
reg    current_state_ce0_local;
reg    b_tmp_we0_local;
reg    b_tmp_ce0_local;
reg   [63:0] grp_fu_556_p0;
reg   [63:0] grp_fu_556_p1;
reg  signed [31:0] grp_fu_562_p0;
reg   [22:0] grp_fu_562_p1;
reg  signed [31:0] grp_fu_566_p0;
reg  signed [23:0] grp_fu_566_p1;
reg  signed [31:0] grp_fu_574_p0;
reg  signed [25:0] grp_fu_574_p1;
wire   [54:0] grp_fu_570_p2;
wire   [31:0] zext_ln102_1_fu_743_p1;
wire   [0:0] tmp_299_fu_751_p3;
wire   [0:0] xor_ln102_fu_759_p2;
wire   [0:0] xor_ln102_2_fu_770_p2;
wire   [0:0] or_ln102_18_fu_775_p2;
wire   [0:0] xor_ln102_4_fu_781_p2;
wire   [0:0] xor_ln102_3_fu_791_p2;
wire   [0:0] or_ln102_fu_797_p2;
wire   [0:0] xor_ln102_1_fu_786_p2;
wire   [0:0] and_ln102_fu_765_p2;
wire   [0:0] or_ln102_19_fu_809_p2;
wire   [0:0] xor_ln102_5_fu_815_p2;
wire   [0:0] and_ln102_2_fu_821_p2;
wire   [31:0] select_ln102_fu_881_p3;
wire   [31:0] select_ln102_1_fu_888_p3;
wire   [53:0] shl_ln_fu_894_p3;
wire  signed [56:0] sext_ln102_4_fu_902_p1;
wire   [31:0] Axi_2_fu_919_p4;
wire   [31:0] zext_ln102_3_fu_937_p1;
wire   [0:0] tmp_302_fu_929_p3;
wire   [0:0] xor_ln102_6_fu_954_p2;
wire   [1:0] tmp_s_fu_966_p4;
wire   [2:0] tmp_218_fu_982_p4;
wire   [0:0] tmp_304_fu_1026_p3;
wire   [0:0] xor_ln102_7_fu_1038_p2;
wire   [0:0] and_ln102_4_fu_1044_p2;
wire   [0:0] select_ln102_2_fu_1033_p3;
wire   [0:0] xor_ln102_8_fu_1059_p2;
wire   [0:0] or_ln102_2_fu_1065_p2;
wire   [0:0] xor_ln102_9_fu_1070_p2;
wire   [0:0] select_ln102_3_fu_1049_p3;
wire   [0:0] and_ln102_5_fu_1055_p2;
wire   [0:0] and_ln102_7_fu_1081_p2;
wire   [0:0] or_ln102_20_fu_1086_p2;
wire   [0:0] xor_ln102_10_fu_1092_p2;
wire   [0:0] and_ln102_6_fu_1075_p2;
wire   [0:0] and_ln102_8_fu_1098_p2;
wire   [0:0] or_ln102_3_fu_1103_p2;
wire   [31:0] select_ln102_4_fu_1109_p3;
wire   [31:0] select_ln102_5_fu_1117_p3;
wire   [53:0] shl_ln102_1_fu_1124_p3;
wire  signed [56:0] sext_ln102_7_fu_1132_p1;
wire   [1:0] tmp_219_fu_1159_p4;
wire   [2:0] tmp_220_fu_1175_p4;
wire   [31:0] zext_ln102_5_fu_1213_p1;
wire   [0:0] tmp_308_fu_1221_p3;
wire   [0:0] tmp_307_fu_1206_p3;
wire   [0:0] xor_ln102_11_fu_1229_p2;
wire   [0:0] and_ln102_9_fu_1235_p2;
wire   [0:0] tmp_309_fu_1241_p3;
wire   [0:0] xor_ln102_12_fu_1254_p2;
wire   [0:0] and_ln102_10_fu_1260_p2;
wire   [0:0] select_ln102_6_fu_1248_p3;
wire   [0:0] xor_ln102_13_fu_1277_p2;
wire   [0:0] or_ln102_4_fu_1283_p2;
wire   [0:0] xor_ln102_14_fu_1289_p2;
wire   [0:0] select_ln102_7_fu_1265_p3;
wire   [0:0] and_ln102_11_fu_1272_p2;
wire   [0:0] and_ln102_13_fu_1300_p2;
wire   [0:0] or_ln102_21_fu_1306_p2;
wire   [0:0] xor_ln102_15_fu_1312_p2;
wire   [0:0] and_ln102_14_fu_1318_p2;
wire   [31:0] select_ln102_8_fu_1329_p3;
wire   [31:0] select_ln102_9_fu_1336_p3;
wire   [53:0] shl_ln102_2_fu_1342_p3;
wire  signed [56:0] sext_ln102_10_fu_1350_p1;
wire   [31:0] Axi_6_fu_1367_p4;
wire   [31:0] zext_ln102_7_fu_1385_p1;
wire   [0:0] tmp_312_fu_1377_p3;
wire   [0:0] xor_ln102_16_fu_1402_p2;
wire   [1:0] tmp_221_fu_1414_p4;
wire   [2:0] tmp_222_fu_1430_p4;
wire   [0:0] tmp_314_fu_1452_p3;
wire   [0:0] xor_ln102_17_fu_1464_p2;
wire   [0:0] and_ln102_16_fu_1470_p2;
wire   [0:0] select_ln102_10_fu_1459_p3;
wire   [0:0] xor_ln102_18_fu_1485_p2;
wire   [0:0] or_ln102_6_fu_1491_p2;
wire   [0:0] xor_ln102_19_fu_1496_p2;
wire   [0:0] select_ln102_11_fu_1475_p3;
wire   [0:0] and_ln102_17_fu_1481_p2;
wire   [0:0] and_ln102_19_fu_1507_p2;
wire   [0:0] or_ln102_22_fu_1512_p2;
wire   [0:0] xor_ln102_20_fu_1518_p2;
wire   [0:0] and_ln102_18_fu_1501_p2;
wire   [0:0] and_ln102_20_fu_1524_p2;
wire   [0:0] or_ln102_7_fu_1529_p2;
wire   [31:0] select_ln102_12_fu_1535_p3;
wire   [31:0] select_ln102_13_fu_1543_p3;
wire   [53:0] shl_ln102_3_fu_1550_p3;
wire  signed [56:0] sext_ln102_13_fu_1558_p1;
wire   [1:0] tmp_223_fu_1585_p4;
wire   [2:0] tmp_224_fu_1601_p4;
wire   [31:0] zext_ln102_9_fu_1630_p1;
wire   [31:0] Axi_9_fu_1633_p2;
wire   [0:0] tmp_318_fu_1638_p3;
wire   [0:0] tmp_317_fu_1623_p3;
wire   [0:0] xor_ln102_21_fu_1646_p2;
wire   [0:0] and_ln102_21_fu_1652_p2;
wire   [0:0] tmp_319_fu_1658_p3;
wire   [0:0] xor_ln102_22_fu_1671_p2;
wire   [0:0] and_ln102_22_fu_1677_p2;
wire   [0:0] select_ln102_14_fu_1665_p3;
wire   [0:0] xor_ln102_23_fu_1694_p2;
wire   [0:0] or_ln102_8_fu_1700_p2;
wire   [0:0] xor_ln102_24_fu_1706_p2;
wire   [0:0] select_ln102_15_fu_1682_p3;
wire   [0:0] and_ln102_23_fu_1689_p2;
wire   [0:0] and_ln102_25_fu_1717_p2;
wire   [0:0] or_ln102_23_fu_1723_p2;
wire   [0:0] xor_ln102_25_fu_1729_p2;
wire   [0:0] and_ln102_24_fu_1711_p2;
wire   [0:0] and_ln102_26_fu_1735_p2;
wire   [0:0] or_ln102_9_fu_1740_p2;
wire   [31:0] select_ln102_16_fu_1746_p3;
wire  signed [53:0] shl_ln102_4_fu_1762_p3;
wire  signed [54:0] sext_ln102_16_fu_1769_p1;
wire  signed [54:0] sext_ln102_17_fu_1773_p1;
wire   [54:0] add_ln102_8_fu_1781_p2;
wire   [53:0] add_ln102_11_fu_1776_p2;
wire   [31:0] Axi_10_fu_1795_p4;
wire   [31:0] zext_ln102_11_fu_1813_p1;
wire   [0:0] xor_ln102_26_fu_1830_p2;
wire   [0:0] xor_ln102_27_fu_1840_p2;
wire   [0:0] or_ln102_24_fu_1845_p2;
wire   [0:0] xor_ln102_28_fu_1850_p2;
wire   [0:0] xor_ln102_30_fu_1860_p2;
wire   [0:0] or_ln102_10_fu_1866_p2;
wire   [0:0] xor_ln102_29_fu_1855_p2;
wire   [0:0] and_ln102_27_fu_1835_p2;
wire   [0:0] or_ln102_25_fu_1877_p2;
wire   [0:0] xor_ln102_31_fu_1882_p2;
wire   [0:0] and_ln102_28_fu_1871_p2;
wire   [0:0] and_ln102_29_fu_1888_p2;
wire   [0:0] or_ln102_11_fu_1893_p2;
wire   [31:0] select_ln102_18_fu_1899_p3;
wire   [31:0] select_ln102_19_fu_1907_p3;
wire  signed [53:0] shl_ln102_5_fu_1914_p3;
wire  signed [54:0] sext_ln102_20_fu_1922_p1;
wire  signed [54:0] sext_ln102_21_fu_1926_p1;
wire   [54:0] add_ln102_10_fu_1934_p2;
wire   [53:0] add_ln102_15_fu_1929_p2;
wire   [31:0] zext_ln102_13_fu_1966_p1;
wire   [31:0] Axi_13_fu_1969_p2;
wire   [0:0] tmp_327_fu_1974_p3;
wire   [0:0] xor_ln102_32_fu_1982_p2;
wire   [0:0] xor_ln102_33_fu_1993_p2;
wire   [0:0] or_ln102_26_fu_1998_p2;
wire   [0:0] xor_ln102_34_fu_2004_p2;
wire   [0:0] xor_ln102_36_fu_2014_p2;
wire   [0:0] or_ln102_12_fu_2020_p2;
wire   [0:0] xor_ln102_35_fu_2009_p2;
wire   [0:0] and_ln102_30_fu_1988_p2;
wire   [0:0] or_ln102_27_fu_2032_p2;
wire   [0:0] xor_ln102_37_fu_2038_p2;
wire   [0:0] and_ln102_31_fu_2026_p2;
wire   [0:0] and_ln102_32_fu_2044_p2;
wire   [0:0] or_ln102_13_fu_2049_p2;
wire   [31:0] select_ln102_20_fu_2055_p3;
wire  signed [53:0] shl_ln102_6_fu_2071_p3;
wire  signed [54:0] sext_ln102_23_fu_2078_p1;
wire  signed [54:0] sext_ln102_24_fu_2082_p1;
wire   [54:0] add_ln102_12_fu_2090_p2;
wire   [53:0] add_ln102_17_fu_2085_p2;
wire   [31:0] Axi_14_fu_2104_p4;
wire   [31:0] zext_ln102_15_fu_2122_p1;
wire   [0:0] xor_ln102_38_fu_2139_p2;
wire   [0:0] xor_ln102_39_fu_2149_p2;
wire   [0:0] or_ln102_28_fu_2154_p2;
wire   [0:0] xor_ln102_40_fu_2159_p2;
wire   [0:0] xor_ln102_42_fu_2169_p2;
wire   [0:0] or_ln102_14_fu_2175_p2;
wire   [0:0] xor_ln102_41_fu_2164_p2;
wire   [0:0] and_ln102_33_fu_2144_p2;
wire   [0:0] or_ln102_29_fu_2186_p2;
wire   [0:0] xor_ln102_43_fu_2191_p2;
wire   [0:0] and_ln102_34_fu_2180_p2;
wire   [0:0] and_ln102_35_fu_2197_p2;
wire   [0:0] or_ln102_15_fu_2202_p2;
wire   [31:0] select_ln102_22_fu_2208_p3;
wire   [31:0] select_ln102_23_fu_2216_p3;
wire  signed [53:0] shl_ln102_7_fu_2223_p3;
wire  signed [54:0] sext_ln102_26_fu_2231_p1;
wire  signed [54:0] sext_ln102_27_fu_2235_p1;
wire   [54:0] add_ln102_14_fu_2243_p2;
wire   [53:0] add_ln102_19_fu_2238_p2;
wire   [31:0] zext_ln102_17_fu_2275_p1;
wire   [31:0] Axi_17_fu_2278_p2;
wire   [0:0] tmp_335_fu_2283_p3;
wire   [0:0] xor_ln102_44_fu_2291_p2;
wire   [0:0] xor_ln102_45_fu_2302_p2;
wire   [0:0] or_ln102_30_fu_2307_p2;
wire   [0:0] xor_ln102_46_fu_2313_p2;
wire   [0:0] xor_ln102_48_fu_2323_p2;
wire   [0:0] or_ln102_16_fu_2329_p2;
wire   [0:0] xor_ln102_47_fu_2318_p2;
wire   [0:0] and_ln102_36_fu_2297_p2;
wire   [0:0] or_ln102_31_fu_2341_p2;
wire   [0:0] xor_ln102_49_fu_2347_p2;
wire   [0:0] and_ln102_37_fu_2335_p2;
wire   [0:0] and_ln102_38_fu_2353_p2;
wire   [0:0] or_ln102_17_fu_2366_p2;
wire   [31:0] select_ln102_24_fu_2358_p3;
wire  signed [31:0] trunc_ln109_1_fu_2380_p1;
wire  signed [31:0] sext_ln109_2_fu_2394_p1;
wire  signed [32:0] sext_ln109_fu_2397_p1;
wire  signed [32:0] sext_ln109_1_fu_2400_p1;
wire   [32:0] add_ln109_fu_2408_p2;
wire   [31:0] add_ln109_1_fu_2403_p2;
wire   [0:0] tmp_336_fu_2414_p3;
wire   [0:0] tmp_337_fu_2426_p3;
wire   [0:0] xor_ln109_fu_2434_p2;
wire   [0:0] and_ln109_fu_2440_p2;
wire   [0:0] xor_ln109_1_fu_2446_p2;
wire   [31:0] select_ln109_fu_2452_p3;
wire   [31:0] trunc_ln109_fu_2422_p1;
wire   [31:0] zi_1_fu_2460_p3;
wire   [31:0] sub_ln110_fu_2486_p2;
wire   [31:0] tmp_225_fu_2500_p3;
wire   [63:0] zext_ln110_fu_2517_p1;
wire   [63:0] zext_ln110_1_fu_2520_p1;
wire   [63:0] shl_ln110_fu_2523_p2;
wire   [62:0] lshr_ln_fu_2529_p4;
wire   [0:0] tmp_339_fu_2543_p3;
wire   [5:0] sub_ln110_1_fu_2559_p2;
wire   [10:0] select_ln110_1_fu_2551_p3;
wire  signed [10:0] sext_ln110_fu_2564_p1;
wire   [10:0] add_ln110_1_fu_2568_p2;
wire   [63:0] zext_ln110_2_fu_2539_p1;
wire   [11:0] tmp_13_fu_2574_p3;
wire   [0:0] or_ln108_fu_2614_p2;
wire   [0:0] xor_ln106_fu_2624_p2;
wire   [0:0] and_ln108_fu_2629_p2;
wire   [0:0] xor_ln110_fu_2639_p2;
wire   [0:0] and_ln110_1_fu_2644_p2;
wire   [24:0] zi_2_fu_2663_p11;
wire   [3:0] zi_2_fu_2663_p12;
wire   [24:0] zi_2_fu_2663_p13;
wire   [24:0] sub_ln119_fu_2687_p2;
wire   [32:0] shl_ln1_fu_2692_p3;
wire  signed [33:0] sext_ln119_1_fu_2703_p1;
wire  signed [33:0] sext_ln119_fu_2700_p1;
wire   [0:0] icmp_ln119_1_fu_2749_p2;
wire   [0:0] or_ln119_fu_2754_p2;
wire   [0:0] xor_ln119_fu_2759_p2;
wire   [0:0] icmp_ln119_fu_2744_p2;
wire   [0:0] xor_ln119_1_fu_2770_p2;
wire   [0:0] or_ln119_1_fu_2775_p2;
wire   [0:0] and_ln119_fu_2764_p2;
wire   [0:0] and_ln119_1_fu_2781_p2;
wire   [0:0] or_ln119_2_fu_2794_p2;
wire   [31:0] select_ln119_fu_2786_p3;
wire   [31:0] yi_fu_2741_p1;
wire   [31:0] shl_ln2_fu_2809_p3;
wire  signed [32:0] sext_ln121_fu_2816_p1;
wire  signed [32:0] sext_ln121_1_fu_2820_p1;
wire   [32:0] sub_ln121_fu_2824_p2;
wire   [0:0] tmp_342_fu_2830_p3;
wire   [0:0] tmp_343_fu_2842_p3;
wire   [0:0] xor_ln121_fu_2850_p2;
wire   [0:0] and_ln121_fu_2856_p2;
wire   [0:0] xor_ln121_1_fu_2862_p2;
wire   [31:0] select_ln121_fu_2868_p3;
wire   [31:0] trunc_ln121_1_fu_2838_p1;
reg   [4:0] grp_fu_556_opcode;
wire    ap_block_pp0_stage0_00001;
wire    ap_block_pp0_stage1_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter4_stage0;
reg    ap_idle_pp0_0to3;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [4:0] ap_NS_fsm;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage3_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [31:0] tmp_225_fu_2500_p0;
wire   [0:0] tmp_225_fu_2500_p2;
wire  signed [3:0] zi_2_fu_2663_p1;
wire   [3:0] zi_2_fu_2663_p3;
wire   [3:0] zi_2_fu_2663_p5;
wire   [3:0] zi_2_fu_2663_p7;
wire   [3:0] zi_2_fu_2663_p9;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 i_fu_198 = 9'd0;
#0 ap_done_reg = 1'b0;
end

ADMM_solver_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_p_ZL16A_sparse_indexes_0_ROM_ARg6 #(
    .DataWidth( 9 ),
    .AddressRange( 332 ),
    .AddressWidth( 9 ))
p_ZL16A_sparse_indexes_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL16A_sparse_indexes_0_address0),
    .ce0(p_ZL16A_sparse_indexes_0_ce0_local),
    .q0(p_ZL16A_sparse_indexes_0_q0)
);

ADMM_solver_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_p_ZL13A_sparse_data_0_ROM_AUTOShg #(
    .DataWidth( 24 ),
    .AddressRange( 332 ),
    .AddressWidth( 9 ))
p_ZL13A_sparse_data_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL13A_sparse_data_0_address0),
    .ce0(p_ZL13A_sparse_data_0_ce0_local),
    .q0(p_ZL13A_sparse_data_0_q0)
);

ADMM_solver_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_p_ZL16A_sparse_indexes_1_ROM_AThq #(
    .DataWidth( 9 ),
    .AddressRange( 332 ),
    .AddressWidth( 9 ))
p_ZL16A_sparse_indexes_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL16A_sparse_indexes_1_address0),
    .ce0(p_ZL16A_sparse_indexes_1_ce0_local),
    .q0(p_ZL16A_sparse_indexes_1_q0)
);

ADMM_solver_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_p_ZL13A_sparse_data_1_ROM_AUTOUhA #(
    .DataWidth( 26 ),
    .AddressRange( 332 ),
    .AddressWidth( 9 ))
p_ZL13A_sparse_data_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL13A_sparse_data_1_address0),
    .ce0(p_ZL13A_sparse_data_1_ce0_local),
    .q0(p_ZL13A_sparse_data_1_q0)
);

ADMM_solver_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_p_ZL16A_sparse_indexes_2_ROM_AVhK #(
    .DataWidth( 9 ),
    .AddressRange( 332 ),
    .AddressWidth( 9 ))
p_ZL16A_sparse_indexes_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL16A_sparse_indexes_2_address0),
    .ce0(p_ZL16A_sparse_indexes_2_ce0_local),
    .q0(p_ZL16A_sparse_indexes_2_q0)
);

ADMM_solver_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_p_ZL13A_sparse_data_2_ROM_AUTOWhU #(
    .DataWidth( 26 ),
    .AddressRange( 332 ),
    .AddressWidth( 9 ))
p_ZL13A_sparse_data_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL13A_sparse_data_2_address0),
    .ce0(p_ZL13A_sparse_data_2_ce0_local),
    .q0(p_ZL13A_sparse_data_2_q0)
);

ADMM_solver_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_p_ZL16A_sparse_indexes_3_ROM_AXh4 #(
    .DataWidth( 9 ),
    .AddressRange( 332 ),
    .AddressWidth( 9 ))
p_ZL16A_sparse_indexes_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL16A_sparse_indexes_3_address0),
    .ce0(p_ZL16A_sparse_indexes_3_ce0_local),
    .q0(p_ZL16A_sparse_indexes_3_q0)
);

ADMM_solver_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_p_ZL13A_sparse_data_3_ROM_AUTOYie #(
    .DataWidth( 26 ),
    .AddressRange( 332 ),
    .AddressWidth( 9 ))
p_ZL13A_sparse_data_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL13A_sparse_data_3_address0),
    .ce0(p_ZL13A_sparse_data_3_ce0_local),
    .q0(p_ZL13A_sparse_data_3_q0)
);

ADMM_solver_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_p_ZL16A_sparse_indexes_4_ROM_AZio #(
    .DataWidth( 9 ),
    .AddressRange( 332 ),
    .AddressWidth( 9 ))
p_ZL16A_sparse_indexes_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL16A_sparse_indexes_4_address0),
    .ce0(p_ZL16A_sparse_indexes_4_ce0_local),
    .q0(p_ZL16A_sparse_indexes_4_q0)
);

ADMM_solver_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_p_ZL13A_sparse_data_4_ROM_AUTO0iy #(
    .DataWidth( 26 ),
    .AddressRange( 332 ),
    .AddressWidth( 9 ))
p_ZL13A_sparse_data_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL13A_sparse_data_4_address0),
    .ce0(p_ZL13A_sparse_data_4_ce0_local),
    .q0(p_ZL13A_sparse_data_4_q0)
);

ADMM_solver_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_p_ZL16A_sparse_indexes_5_ROM_A1iI #(
    .DataWidth( 9 ),
    .AddressRange( 332 ),
    .AddressWidth( 9 ))
p_ZL16A_sparse_indexes_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL16A_sparse_indexes_5_address0),
    .ce0(p_ZL16A_sparse_indexes_5_ce0_local),
    .q0(p_ZL16A_sparse_indexes_5_q0)
);

ADMM_solver_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_p_ZL13A_sparse_data_5_ROM_AUTO2iS #(
    .DataWidth( 24 ),
    .AddressRange( 332 ),
    .AddressWidth( 9 ))
p_ZL13A_sparse_data_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL13A_sparse_data_5_address0),
    .ce0(p_ZL13A_sparse_data_5_ce0_local),
    .q0(p_ZL13A_sparse_data_5_q0)
);

ADMM_solver_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_p_ZL16A_sparse_indexes_6_ROM_A3i2 #(
    .DataWidth( 9 ),
    .AddressRange( 332 ),
    .AddressWidth( 9 ))
p_ZL16A_sparse_indexes_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL16A_sparse_indexes_6_address0),
    .ce0(p_ZL16A_sparse_indexes_6_ce0_local),
    .q0(p_ZL16A_sparse_indexes_6_q0)
);

ADMM_solver_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_p_ZL13A_sparse_data_6_ROM_AUTO4jc #(
    .DataWidth( 24 ),
    .AddressRange( 332 ),
    .AddressWidth( 9 ))
p_ZL13A_sparse_data_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL13A_sparse_data_6_address0),
    .ce0(p_ZL13A_sparse_data_6_ce0_local),
    .q0(p_ZL13A_sparse_data_6_q0)
);

ADMM_solver_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_p_ZL16A_sparse_indexes_7_ROM_A5jm #(
    .DataWidth( 9 ),
    .AddressRange( 332 ),
    .AddressWidth( 9 ))
p_ZL16A_sparse_indexes_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL16A_sparse_indexes_7_address0),
    .ce0(p_ZL16A_sparse_indexes_7_ce0_local),
    .q0(p_ZL16A_sparse_indexes_7_q0)
);

ADMM_solver_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_p_ZL13A_sparse_data_7_ROM_AUTO6jw #(
    .DataWidth( 23 ),
    .AddressRange( 332 ),
    .AddressWidth( 9 ))
p_ZL13A_sparse_data_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL13A_sparse_data_7_address0),
    .ce0(p_ZL13A_sparse_data_7_ce0_local),
    .q0(p_ZL13A_sparse_data_7_q0)
);

ADMM_solver_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_p_ZL16A_sparse_indexes_8_ROM_A7jG #(
    .DataWidth( 9 ),
    .AddressRange( 332 ),
    .AddressWidth( 9 ))
p_ZL16A_sparse_indexes_8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL16A_sparse_indexes_8_address0),
    .ce0(p_ZL16A_sparse_indexes_8_ce0_local),
    .q0(p_ZL16A_sparse_indexes_8_q0)
);

ADMM_solver_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_p_ZL13A_sparse_data_8_ROM_AUTO8jQ #(
    .DataWidth( 23 ),
    .AddressRange( 332 ),
    .AddressWidth( 9 ))
p_ZL13A_sparse_data_8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL13A_sparse_data_8_address0),
    .ce0(p_ZL13A_sparse_data_8_ce0_local),
    .q0(p_ZL13A_sparse_data_8_q0)
);

ADMM_solver_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_y_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 332 ),
    .AddressWidth( 9 ))
y_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(y_address0_local),
    .ce0(y_ce0_local),
    .we0(y_we0_local),
    .d0(yi_1_fu_2800_p3),
    .q0(y_q0)
);

ADMM_solver_dcmp_64ns_64ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 1 ))
dcmp_64ns_64ns_1_2_no_dsp_1_U118(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_556_p0),
    .din1(grp_fu_556_p1),
    .ce(1'b1),
    .opcode(grp_fu_556_opcode),
    .dout(grp_fu_556_p2)
);

ADMM_solver_mul_32s_24s_55_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 55 ))
mul_32s_24s_55_2_1_U121(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(x_q1),
    .din1(p_ZL13A_sparse_data_0_load_reg_2999),
    .ce(1'b1),
    .dout(grp_fu_570_p2)
);

ADMM_solver_ctlz_32_32_1_1 #(
    .din_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
ctlz_32_32_1_1_U124(
    .din(select_ln110_reg_3667),
    .dout(tmp_225_fu_2500_p3)
);

(* dissolve_hierarchy = "yes" *) ADMM_solver_sparsemux_11_4_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h8 ),
    .din0_WIDTH( 25 ),
    .CASE1( 4'h4 ),
    .din1_WIDTH( 25 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 25 ),
    .CASE3( 4'h1 ),
    .din3_WIDTH( 25 ),
    .CASE4( 4'h0 ),
    .din4_WIDTH( 25 ),
    .def_WIDTH( 25 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 25 ))
sparsemux_11_4_25_1_1_U125(
    .din0(trunc_ln105_reg_3698),
    .din1(25'd0),
    .din2(trunc_ln105_1_reg_3649_pp0_iter4_reg),
    .din3(select_ln110_2_reg_3709),
    .din4(select_ln112_reg_3714),
    .def(zi_2_fu_2663_p11),
    .sel(zi_2_fu_2663_p12),
    .dout(zi_2_fu_2663_p13)
);

ADMM_solver_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage4),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage4)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage0))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage0))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_fu_198 <= 9'd0;
    end else if (((icmp_ln99_reg_2898 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        i_fu_198 <= add_ln99_fu_738_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        Axi_11_reg_3542 <= Axi_11_fu_1816_p2;
        Axi_18_reg_3627 <= Axi_18_fu_2372_p3;
        Axi_4_reg_3364 <= {{add_ln102_2_fu_1136_p2[53:22]}};
        add_ln102_2_reg_3352 <= add_ln102_2_fu_1136_p2;
        icmp_ln102_3_reg_3369 <= icmp_ln102_3_fu_1169_p2;
        icmp_ln102_4_reg_3374 <= icmp_ln102_4_fu_1185_p2;
        icmp_ln102_5_reg_3381 <= icmp_ln102_5_fu_1191_p2;
        mul_ln102_6_reg_3386_pp0_iter2_reg <= mul_ln102_6_reg_3386;
        mul_ln102_7_reg_3397_pp0_iter2_reg <= mul_ln102_7_reg_3397;
        p_ZL13A_sparse_data_0_load_reg_2999 <= p_ZL13A_sparse_data_0_q0;
        p_ZL13A_sparse_data_1_load_reg_3009 <= p_ZL13A_sparse_data_1_q0;
        p_ZL13A_sparse_data_2_load_reg_3024 <= p_ZL13A_sparse_data_2_q0;
        p_ZL13A_sparse_data_3_load_reg_3034 <= p_ZL13A_sparse_data_3_q0;
        p_ZL13A_sparse_data_4_load_reg_3044 <= p_ZL13A_sparse_data_4_q0;
        p_ZL13A_sparse_data_5_load_reg_3054 <= p_ZL13A_sparse_data_5_q0;
        p_ZL13A_sparse_data_6_load_reg_3064 <= p_ZL13A_sparse_data_6_q0;
        p_ZL13A_sparse_data_7_load_reg_3074 <= p_ZL13A_sparse_data_7_q0;
        p_ZL13A_sparse_data_8_load_reg_3084 <= p_ZL13A_sparse_data_8_q0;
        p_ZL16A_sparse_indexes_2_load_reg_3019 <= p_ZL16A_sparse_indexes_2_q0;
        p_ZL16A_sparse_indexes_3_load_reg_3029 <= p_ZL16A_sparse_indexes_3_q0;
        p_ZL16A_sparse_indexes_4_load_reg_3039 <= p_ZL16A_sparse_indexes_4_q0;
        p_ZL16A_sparse_indexes_5_load_reg_3049 <= p_ZL16A_sparse_indexes_5_q0;
        p_ZL16A_sparse_indexes_6_load_reg_3059 <= p_ZL16A_sparse_indexes_6_q0;
        p_ZL16A_sparse_indexes_7_load_reg_3069 <= p_ZL16A_sparse_indexes_7_q0;
        p_ZL16A_sparse_indexes_8_load_reg_3079 <= p_ZL16A_sparse_indexes_8_q0;
        tmp_305_reg_3358 <= add_ln102_2_fu_1136_p2[32'd56];
        tmp_320_reg_3529 <= add_ln102_8_fu_1781_p2[32'd54];
        tmp_322_reg_3536 <= add_ln102_11_fu_1776_p2[32'd53];
        tmp_323_reg_3547 <= Axi_11_fu_1816_p2[32'd31];
        tmp_325_reg_3392_pp0_iter2_reg <= tmp_325_reg_3392;
        tmp_329_reg_3403_pp0_iter2_reg <= tmp_329_reg_3403;
        trunc_ln105_reg_3698 <= trunc_ln105_fu_2597_p1;
        trunc_ln109_1_reg_3638 <= {{trunc_ln109_1_fu_2380_p1[31:8]}};
        trunc_ln119_reg_3644 <= trunc_ln119_fu_2390_p1;
        trunc_ln119_reg_3644_pp0_iter4_reg <= trunc_ln119_reg_3644;
        y_load_reg_3633_pp0_iter4_reg <= y_load_reg_3633;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Axi_12_reg_3562 <= {{add_ln102_15_fu_1929_p2[53:22]}};
        Axi_5_reg_3418 <= Axi_5_fu_1216_p2;
        and_ln102_12_reg_3423 <= and_ln102_12_fu_1294_p2;
        and_ln110_2_reg_3729 <= and_ln110_2_fu_2649_p2;
        and_ln110_reg_3724 <= and_ln110_fu_2634_p2;
        icmp_ln110_reg_3656 <= icmp_ln110_fu_2472_p2;
        mul_ln102_8_reg_3433_pp0_iter2_reg <= mul_ln102_8_reg_3433;
        or_ln102_5_reg_3428 <= or_ln102_5_fu_1323_p2;
        select_ln110_2_reg_3709 <= select_ln110_2_fu_2601_p3;
        select_ln110_reg_3667 <= select_ln110_fu_2492_p3;
        select_ln112_reg_3714 <= select_ln112_fu_2607_p3;
        tmp_324_reg_3555 <= add_ln102_10_fu_1934_p2[32'd54];
        tmp_326_reg_3567 <= add_ln102_15_fu_1929_p2[32'd53];
        tmp_333_reg_3439_pp0_iter2_reg <= tmp_333_reg_3439;
        tmp_338_reg_3662 <= zi_1_fu_2460_p3[32'd31];
        trunc_ln105_1_reg_3649 <= trunc_ln105_1_fu_2468_p1;
        trunc_ln105_1_reg_3649_pp0_iter4_reg <= trunc_ln105_1_reg_3649;
        xor_ln108_reg_3719 <= xor_ln108_fu_2618_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        Axi_15_reg_3591 <= Axi_15_fu_2125_p2;
        Axi_1_reg_3182 <= Axi_1_fu_746_p2;
        Axi_8_reg_3502 <= {{add_ln102_6_fu_1562_p2[53:22]}};
        LD_reg_3683 <= LD_fu_2581_p5;
        add_ln102_6_reg_3490 <= add_ln102_6_fu_1562_p2;
        and_ln102_1_reg_3187 <= and_ln102_1_fu_803_p2;
        icmp_ln102_10_reg_3512 <= icmp_ln102_10_fu_1611_p2;
        icmp_ln102_11_reg_3519 <= icmp_ln102_11_fu_1617_p2;
        icmp_ln102_9_reg_3507 <= icmp_ln102_9_fu_1595_p2;
        icmp_ln106_reg_3247 <= icmp_ln106_fu_866_p2;
        icmp_ln106_reg_3247_pp0_iter1_reg <= icmp_ln106_reg_3247;
        icmp_ln106_reg_3247_pp0_iter2_reg <= icmp_ln106_reg_3247_pp0_iter1_reg;
        icmp_ln106_reg_3247_pp0_iter3_reg <= icmp_ln106_reg_3247_pp0_iter2_reg;
        icmp_ln108_reg_3254 <= icmp_ln108_fu_871_p2;
        icmp_ln108_reg_3254_pp0_iter1_reg <= icmp_ln108_reg_3254;
        icmp_ln108_reg_3254_pp0_iter2_reg <= icmp_ln108_reg_3254_pp0_iter1_reg;
        icmp_ln108_reg_3254_pp0_iter3_reg <= icmp_ln108_reg_3254_pp0_iter2_reg;
        mul_ln102_3_reg_3207 <= grp_fu_493_p_dout0;
        or_ln102_1_reg_3192 <= or_ln102_1_fu_826_p2;
        select_ln121_1_reg_3762 <= select_ln121_1_fu_2876_p3;
        tmp_311_reg_3212 <= grp_fu_493_p_dout0[32'd21];
        tmp_315_reg_3496 <= add_ln102_6_fu_1562_p2[32'd56];
        tmp_328_reg_3578 <= add_ln102_12_fu_2090_p2[32'd54];
        tmp_330_reg_3585 <= add_ln102_17_fu_2085_p2[32'd53];
        tmp_331_reg_3596 <= Axi_15_fu_2125_p2[32'd31];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Axi_16_reg_3611 <= {{add_ln102_19_fu_2238_p2[53:22]}};
        Axi_3_reg_3271 <= Axi_3_fu_940_p2;
        add_ln102_reg_3260 <= add_ln102_fu_906_p2;
        and_ln102_3_reg_3282 <= and_ln102_3_fu_960_p2;
        bitcast_ln758_reg_3693 <= bitcast_ln758_fu_2593_p1;
        i_3_reg_2891 <= ap_sig_allocacmp_i_3;
        icmp_ln102_1_reg_3294 <= icmp_ln102_1_fu_992_p2;
        icmp_ln102_2_reg_3301 <= icmp_ln102_2_fu_998_p2;
        icmp_ln102_reg_3289 <= icmp_ln102_fu_976_p2;
        icmp_ln99_reg_2898 <= icmp_ln99_fu_614_p2;
        icmp_ln99_reg_2898_pp0_iter1_reg <= icmp_ln99_reg_2898;
        icmp_ln99_reg_2898_pp0_iter2_reg <= icmp_ln99_reg_2898_pp0_iter1_reg;
        icmp_ln99_reg_2898_pp0_iter3_reg <= icmp_ln99_reg_2898_pp0_iter2_reg;
        mul_ln102_5_reg_3316_pp0_iter2_reg <= mul_ln102_5_reg_3316;
        select_ln102_17_reg_3524 <= select_ln102_17_fu_1754_p3;
        tmp_300_reg_3265 <= add_ln102_fu_906_p2[32'd56];
        tmp_303_reg_3276 <= Axi_3_fu_940_p2[32'd31];
        tmp_321_reg_3322_pp0_iter2_reg <= tmp_321_reg_3322;
        tmp_332_reg_3604 <= add_ln102_14_fu_2243_p2[32'd54];
        tmp_334_reg_3616 <= add_ln102_19_fu_2238_p2[32'd53];
        y_addr_reg_3622 <= zext_ln99_reg_2902_pp0_iter2_reg;
        y_addr_reg_3622_pp0_iter4_reg <= y_addr_reg_3622;
        zext_ln99_reg_2902[8 : 0] <= zext_ln99_fu_620_p1[8 : 0];
        zext_ln99_reg_2902_pp0_iter1_reg[8 : 0] <= zext_ln99_reg_2902[8 : 0];
        zext_ln99_reg_2902_pp0_iter2_reg[8 : 0] <= zext_ln99_reg_2902_pp0_iter1_reg[8 : 0];
        zext_ln99_reg_2902_pp0_iter3_reg[8 : 0] <= zext_ln99_reg_2902_pp0_iter2_reg[8 : 0];
        zext_ln99_reg_2902_pp0_iter4_reg[8 : 0] <= zext_ln99_reg_2902_pp0_iter3_reg[8 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        Axi_7_reg_3455 <= Axi_7_fu_1388_p2;
        Axi_reg_3126 <= {{grp_fu_570_p2[53:22]}};
        add_ln102_4_reg_3444 <= add_ln102_4_fu_1354_p2;
        add_ln110_reg_3678 <= add_ln110_fu_2511_p2;
        add_ln119_reg_3734 <= add_ln119_fu_2707_p2;
        and_ln102_15_reg_3466 <= and_ln102_15_fu_1408_p2;
        icmp_ln102_6_reg_3473 <= icmp_ln102_6_fu_1424_p2;
        icmp_ln102_7_reg_3478 <= icmp_ln102_7_fu_1440_p2;
        icmp_ln102_8_reg_3485 <= icmp_ln102_8_fu_1446_p2;
        select_ln102_21_reg_3573 <= select_ln102_21_fu_2063_p3;
        tmp_228_reg_3751 <= {{add_ln119_fu_2707_p2[33:32]}};
        tmp_296_reg_3131 <= grp_fu_570_p2[32'd21];
        tmp_298_reg_3136 <= grp_fu_570_p2[32'd53];
        tmp_310_reg_3449 <= add_ln102_4_fu_1354_p2[32'd56];
        tmp_313_reg_3460 <= Axi_7_fu_1388_p2[32'd31];
        tmp_340_reg_3739 <= add_ln119_fu_2707_p2[32'd33];
        tmp_341_reg_3745 <= add_ln119_fu_2707_p2[32'd31];
        tmp_reg_3119 <= grp_fu_570_p2[32'd54];
        trunc_ln110_reg_3673 <= trunc_ln110_fu_2507_p1;
        trunc_ln121_reg_3757 <= trunc_ln121_fu_2737_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        mul_ln102_1_reg_3142 <= grp_fu_489_p_dout0;
        tmp_301_reg_3147 <= grp_fu_489_p_dout0[32'd21];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        mul_ln102_2_reg_3197 <= grp_fu_489_p_dout0;
        tmp_306_reg_3202 <= grp_fu_489_p_dout0[32'd21];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mul_ln102_4_reg_3306 <= grp_fu_489_p_dout0;
        mul_ln102_5_reg_3316 <= grp_fu_485_p_dout0;
        tmp_316_reg_3311 <= grp_fu_489_p_dout0[32'd21];
        tmp_321_reg_3322 <= grp_fu_485_p_dout0[32'd21];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        mul_ln102_6_reg_3386 <= grp_fu_485_p_dout0;
        mul_ln102_7_reg_3397 <= grp_fu_481_p_dout0;
        tmp_325_reg_3392 <= grp_fu_485_p_dout0[32'd21];
        tmp_329_reg_3403 <= grp_fu_481_p_dout0[32'd21];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        mul_ln102_8_reg_3433 <= grp_fu_481_p_dout0;
        tmp_333_reg_3439 <= grp_fu_481_p_dout0[32'd21];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        tmp_226_reg_3703 <= grp_fu_556_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        y_load_reg_3633 <= y_q0;
    end
end

always @ (*) begin
    if (((icmp_ln99_reg_2898 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_condition_exit_pp0_iter0_stage4 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln99_reg_2898_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter4_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter4_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to3 = 1'b1;
    end else begin
        ap_idle_pp0_0to3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_3 = 9'd0;
    end else begin
        ap_sig_allocacmp_i_3 = i_fu_198;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_tmp_ce0_local = 1'b1;
    end else begin
        b_tmp_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_tmp_we0_local = 1'b1;
    end else begin
        b_tmp_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        current_state_ce0_local = 1'b1;
    end else begin
        current_state_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1_00001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_556_opcode = 5'd2;
        end else if (((1'b0 == ap_block_pp0_stage0_00001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_556_opcode = 5'd4;
        end else begin
            grp_fu_556_opcode = 'bx;
        end
    end else begin
        grp_fu_556_opcode = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_556_p0 = bitcast_ln758_reg_3693;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_556_p0 = bitcast_ln758_fu_2593_p1;
        end else begin
            grp_fu_556_p0 = 'bx;
        end
    end else begin
        grp_fu_556_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_556_p1 = 64'd4601177618959431074;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_556_p1 = 64'd13826801456134030639;
        end else begin
            grp_fu_556_p1 = 'bx;
        end
    end else begin
        grp_fu_556_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_562_p0 = sext_ln102_25_fu_1201_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_562_p0 = sext_ln102_22_fu_1017_p1;
        end else begin
            grp_fu_562_p0 = 'bx;
        end
    end else begin
        grp_fu_562_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_562_p1 = zext_ln102_19_fu_1197_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_562_p1 = zext_ln102_18_fu_1013_p1;
        end else begin
            grp_fu_562_p1 = 'bx;
        end
    end else begin
        grp_fu_562_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_566_p0 = sext_ln102_19_fu_1008_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_566_p0 = sext_ln102_15_fu_853_p1;
    end else begin
        grp_fu_566_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_566_p1 = sext_ln102_18_fu_1004_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_566_p1 = sext_ln102_14_fu_849_p1;
    end else begin
        grp_fu_566_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0_reg == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            grp_fu_574_p0 = sext_ln102_12_fu_844_p1;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_574_p0 = sext_ln102_6_fu_716_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_574_p0 = sext_ln102_3_fu_665_p1;
        end else begin
            grp_fu_574_p0 = 'bx;
        end
    end else begin
        grp_fu_574_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0_reg == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            grp_fu_574_p1 = sext_ln102_11_fu_840_p1;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_574_p1 = sext_ln102_5_fu_712_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_574_p1 = sext_ln102_2_fu_661_p1;
        end else begin
            grp_fu_574_p1 = 'bx;
        end
    end else begin
        grp_fu_574_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL13A_sparse_data_0_ce0_local = 1'b1;
    end else begin
        p_ZL13A_sparse_data_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL13A_sparse_data_1_ce0_local = 1'b1;
    end else begin
        p_ZL13A_sparse_data_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL13A_sparse_data_2_ce0_local = 1'b1;
    end else begin
        p_ZL13A_sparse_data_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL13A_sparse_data_3_ce0_local = 1'b1;
    end else begin
        p_ZL13A_sparse_data_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL13A_sparse_data_4_ce0_local = 1'b1;
    end else begin
        p_ZL13A_sparse_data_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL13A_sparse_data_5_ce0_local = 1'b1;
    end else begin
        p_ZL13A_sparse_data_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL13A_sparse_data_6_ce0_local = 1'b1;
    end else begin
        p_ZL13A_sparse_data_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL13A_sparse_data_7_ce0_local = 1'b1;
    end else begin
        p_ZL13A_sparse_data_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL13A_sparse_data_8_ce0_local = 1'b1;
    end else begin
        p_ZL13A_sparse_data_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL16A_sparse_indexes_0_ce0_local = 1'b1;
    end else begin
        p_ZL16A_sparse_indexes_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL16A_sparse_indexes_1_ce0_local = 1'b1;
    end else begin
        p_ZL16A_sparse_indexes_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL16A_sparse_indexes_2_ce0_local = 1'b1;
    end else begin
        p_ZL16A_sparse_indexes_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL16A_sparse_indexes_3_ce0_local = 1'b1;
    end else begin
        p_ZL16A_sparse_indexes_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL16A_sparse_indexes_4_ce0_local = 1'b1;
    end else begin
        p_ZL16A_sparse_indexes_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL16A_sparse_indexes_5_ce0_local = 1'b1;
    end else begin
        p_ZL16A_sparse_indexes_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL16A_sparse_indexes_6_ce0_local = 1'b1;
    end else begin
        p_ZL16A_sparse_indexes_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL16A_sparse_indexes_7_ce0_local = 1'b1;
    end else begin
        p_ZL16A_sparse_indexes_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL16A_sparse_indexes_8_ce0_local = 1'b1;
    end else begin
        p_ZL16A_sparse_indexes_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_address0_local = zext_ln102_16_fu_1022_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        x_address0_local = zext_ln102_12_fu_858_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        x_address0_local = zext_ln102_8_fu_730_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        x_address0_local = zext_ln102_4_fu_670_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        x_address0_local = zext_ln102_2_fu_647_p1;
    end else begin
        x_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0_reg == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            x_address1_local = zext_ln102_14_fu_862_p1;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            x_address1_local = zext_ln102_10_fu_734_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            x_address1_local = zext_ln102_6_fu_674_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            x_address1_local = zext_ln102_fu_642_p1;
        end else begin
            x_address1_local = 'bx;
        end
    end else begin
        x_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        x_ce0_local = 1'b1;
    end else begin
        x_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        x_ce1_local = 1'b1;
    end else begin
        x_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        y_address0_local = y_addr_reg_3622_pp0_iter4_reg;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        y_address0_local = zext_ln99_reg_2902_pp0_iter2_reg;
    end else begin
        y_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        y_ce0_local = 1'b1;
    end else begin
        y_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        y_we0_local = 1'b1;
    end else begin
        y_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Axi_10_fu_1795_p4 = {{add_ln102_11_fu_1776_p2[53:22]}};

assign Axi_11_fu_1816_p2 = (Axi_10_fu_1795_p4 + zext_ln102_11_fu_1813_p1);

assign Axi_13_fu_1969_p2 = (Axi_12_reg_3562 + zext_ln102_13_fu_1966_p1);

assign Axi_14_fu_2104_p4 = {{add_ln102_17_fu_2085_p2[53:22]}};

assign Axi_15_fu_2125_p2 = (Axi_14_fu_2104_p4 + zext_ln102_15_fu_2122_p1);

assign Axi_17_fu_2278_p2 = (Axi_16_reg_3611 + zext_ln102_17_fu_2275_p1);

assign Axi_18_fu_2372_p3 = ((or_ln102_17_fu_2366_p2[0:0] == 1'b1) ? select_ln102_24_fu_2358_p3 : Axi_17_fu_2278_p2);

assign Axi_1_fu_746_p2 = (Axi_reg_3126 + zext_ln102_1_fu_743_p1);

assign Axi_2_fu_919_p4 = {{add_ln102_fu_906_p2[53:22]}};

assign Axi_3_fu_940_p2 = (Axi_2_fu_919_p4 + zext_ln102_3_fu_937_p1);

assign Axi_5_fu_1216_p2 = (Axi_4_reg_3364 + zext_ln102_5_fu_1213_p1);

assign Axi_6_fu_1367_p4 = {{add_ln102_4_fu_1354_p2[53:22]}};

assign Axi_7_fu_1388_p2 = (Axi_6_fu_1367_p4 + zext_ln102_7_fu_1385_p1);

assign Axi_9_fu_1633_p2 = (Axi_8_reg_3502 + zext_ln102_9_fu_1630_p1);

assign LD_fu_2581_p5 = {{tmp_13_fu_2574_p3}, {zext_ln110_2_fu_2539_p1[51:0]}};

assign add_ln102_10_fu_1934_p2 = ($signed(sext_ln102_20_fu_1922_p1) + $signed(sext_ln102_21_fu_1926_p1));

assign add_ln102_11_fu_1776_p2 = ($signed(shl_ln102_4_fu_1762_p3) + $signed(mul_ln102_5_reg_3316_pp0_iter2_reg));

assign add_ln102_12_fu_2090_p2 = ($signed(sext_ln102_23_fu_2078_p1) + $signed(sext_ln102_24_fu_2082_p1));

assign add_ln102_14_fu_2243_p2 = ($signed(sext_ln102_26_fu_2231_p1) + $signed(sext_ln102_27_fu_2235_p1));

assign add_ln102_15_fu_1929_p2 = ($signed(shl_ln102_5_fu_1914_p3) + $signed(mul_ln102_6_reg_3386_pp0_iter2_reg));

assign add_ln102_17_fu_2085_p2 = ($signed(shl_ln102_6_fu_2071_p3) + $signed(mul_ln102_7_reg_3397_pp0_iter2_reg));

assign add_ln102_19_fu_2238_p2 = ($signed(shl_ln102_7_fu_2223_p3) + $signed(mul_ln102_8_reg_3433_pp0_iter2_reg));

assign add_ln102_2_fu_1136_p2 = ($signed(sext_ln102_7_fu_1132_p1) + $signed(mul_ln102_2_reg_3197));

assign add_ln102_4_fu_1354_p2 = ($signed(sext_ln102_10_fu_1350_p1) + $signed(mul_ln102_3_reg_3207));

assign add_ln102_6_fu_1562_p2 = ($signed(sext_ln102_13_fu_1558_p1) + $signed(mul_ln102_4_reg_3306));

assign add_ln102_8_fu_1781_p2 = ($signed(sext_ln102_16_fu_1769_p1) + $signed(sext_ln102_17_fu_1773_p1));

assign add_ln102_fu_906_p2 = ($signed(sext_ln102_4_fu_902_p1) + $signed(mul_ln102_1_reg_3142));

assign add_ln109_1_fu_2403_p2 = ($signed(Axi_18_reg_3627) + $signed(sext_ln109_2_fu_2394_p1));

assign add_ln109_fu_2408_p2 = ($signed(sext_ln109_fu_2397_p1) + $signed(sext_ln109_1_fu_2400_p1));

assign add_ln110_1_fu_2568_p2 = ($signed(select_ln110_1_fu_2551_p3) + $signed(sext_ln110_fu_2564_p1));

assign add_ln110_fu_2511_p2 = (trunc_ln110_fu_2507_p1 + 6'd22);

assign add_ln119_fu_2707_p2 = ($signed(sext_ln119_1_fu_2703_p1) + $signed(sext_ln119_fu_2700_p1));

assign add_ln99_fu_738_p2 = (i_3_reg_2891 + 9'd1);

assign and_ln102_10_fu_1260_p2 = (xor_ln102_12_fu_1254_p2 & icmp_ln102_3_reg_3369);

assign and_ln102_11_fu_1272_p2 = (icmp_ln102_4_reg_3374 & and_ln102_9_fu_1235_p2);

assign and_ln102_12_fu_1294_p2 = (xor_ln102_14_fu_1289_p2 & or_ln102_4_fu_1283_p2);

assign and_ln102_13_fu_1300_p2 = (tmp_308_fu_1221_p3 & select_ln102_7_fu_1265_p3);

assign and_ln102_14_fu_1318_p2 = (xor_ln102_15_fu_1312_p2 & tmp_305_reg_3358);

assign and_ln102_15_fu_1408_p2 = (xor_ln102_16_fu_1402_p2 & tmp_312_fu_1377_p3);

assign and_ln102_16_fu_1470_p2 = (xor_ln102_17_fu_1464_p2 & icmp_ln102_6_reg_3473);

assign and_ln102_17_fu_1481_p2 = (icmp_ln102_7_reg_3478 & and_ln102_15_reg_3466);

assign and_ln102_18_fu_1501_p2 = (xor_ln102_19_fu_1496_p2 & or_ln102_6_fu_1491_p2);

assign and_ln102_19_fu_1507_p2 = (tmp_313_reg_3460 & select_ln102_11_fu_1475_p3);

assign and_ln102_1_fu_803_p2 = (xor_ln102_1_fu_786_p2 & or_ln102_fu_797_p2);

assign and_ln102_20_fu_1524_p2 = (xor_ln102_20_fu_1518_p2 & tmp_310_reg_3449);

assign and_ln102_21_fu_1652_p2 = (xor_ln102_21_fu_1646_p2 & tmp_317_fu_1623_p3);

assign and_ln102_22_fu_1677_p2 = (xor_ln102_22_fu_1671_p2 & icmp_ln102_9_reg_3507);

assign and_ln102_23_fu_1689_p2 = (icmp_ln102_10_reg_3512 & and_ln102_21_fu_1652_p2);

assign and_ln102_24_fu_1711_p2 = (xor_ln102_24_fu_1706_p2 & or_ln102_8_fu_1700_p2);

assign and_ln102_25_fu_1717_p2 = (tmp_318_fu_1638_p3 & select_ln102_15_fu_1682_p3);

assign and_ln102_26_fu_1735_p2 = (xor_ln102_25_fu_1729_p2 & tmp_315_reg_3496);

assign and_ln102_27_fu_1835_p2 = (xor_ln102_26_fu_1830_p2 & tmp_322_reg_3536);

assign and_ln102_28_fu_1871_p2 = (xor_ln102_29_fu_1855_p2 & or_ln102_10_fu_1866_p2);

assign and_ln102_29_fu_1888_p2 = (xor_ln102_31_fu_1882_p2 & tmp_320_reg_3529);

assign and_ln102_2_fu_821_p2 = (xor_ln102_5_fu_815_p2 & tmp_reg_3119);

assign and_ln102_30_fu_1988_p2 = (xor_ln102_32_fu_1982_p2 & tmp_326_reg_3567);

assign and_ln102_31_fu_2026_p2 = (xor_ln102_35_fu_2009_p2 & or_ln102_12_fu_2020_p2);

assign and_ln102_32_fu_2044_p2 = (xor_ln102_37_fu_2038_p2 & tmp_324_reg_3555);

assign and_ln102_33_fu_2144_p2 = (xor_ln102_38_fu_2139_p2 & tmp_330_reg_3585);

assign and_ln102_34_fu_2180_p2 = (xor_ln102_41_fu_2164_p2 & or_ln102_14_fu_2175_p2);

assign and_ln102_35_fu_2197_p2 = (xor_ln102_43_fu_2191_p2 & tmp_328_reg_3578);

assign and_ln102_36_fu_2297_p2 = (xor_ln102_44_fu_2291_p2 & tmp_334_reg_3616);

assign and_ln102_37_fu_2335_p2 = (xor_ln102_47_fu_2318_p2 & or_ln102_16_fu_2329_p2);

assign and_ln102_38_fu_2353_p2 = (xor_ln102_49_fu_2347_p2 & tmp_332_reg_3604);

assign and_ln102_3_fu_960_p2 = (xor_ln102_6_fu_954_p2 & tmp_302_fu_929_p3);

assign and_ln102_4_fu_1044_p2 = (xor_ln102_7_fu_1038_p2 & icmp_ln102_reg_3289);

assign and_ln102_5_fu_1055_p2 = (icmp_ln102_1_reg_3294 & and_ln102_3_reg_3282);

assign and_ln102_6_fu_1075_p2 = (xor_ln102_9_fu_1070_p2 & or_ln102_2_fu_1065_p2);

assign and_ln102_7_fu_1081_p2 = (tmp_303_reg_3276 & select_ln102_3_fu_1049_p3);

assign and_ln102_8_fu_1098_p2 = (xor_ln102_10_fu_1092_p2 & tmp_300_reg_3265);

assign and_ln102_9_fu_1235_p2 = (xor_ln102_11_fu_1229_p2 & tmp_307_fu_1206_p3);

assign and_ln102_fu_765_p2 = (xor_ln102_fu_759_p2 & tmp_298_reg_3136);

assign and_ln108_fu_2629_p2 = (xor_ln106_fu_2624_p2 & icmp_ln108_reg_3254_pp0_iter3_reg);

assign and_ln109_fu_2440_p2 = (xor_ln109_fu_2434_p2 & tmp_337_fu_2426_p3);

assign and_ln110_1_fu_2644_p2 = (xor_ln110_fu_2639_p2 & tmp_226_reg_3703);

assign and_ln110_2_fu_2649_p2 = (and_ln110_1_fu_2644_p2 & and_ln108_fu_2629_p2);

assign and_ln110_fu_2634_p2 = (icmp_ln110_reg_3656 & and_ln108_fu_2629_p2);

assign and_ln119_1_fu_2781_p2 = (tmp_340_reg_3739 & or_ln119_1_fu_2775_p2);

assign and_ln119_fu_2764_p2 = (xor_ln119_fu_2759_p2 & or_ln119_fu_2754_p2);

assign and_ln121_fu_2856_p2 = (xor_ln121_fu_2850_p2 & tmp_343_fu_2842_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage4;

assign ap_ready = ap_ready_sig;

assign b_tmp_address0 = zext_ln99_reg_2902_pp0_iter4_reg;

assign b_tmp_ce0 = b_tmp_ce0_local;

assign b_tmp_d0 = select_ln121_1_reg_3762;

assign b_tmp_we0 = b_tmp_we0_local;

assign bitcast_ln758_fu_2593_p1 = LD_reg_3683;

assign current_state_address0 = zext_ln99_reg_2902_pp0_iter3_reg;

assign current_state_ce0 = current_state_ce0_local;

assign grp_fu_481_p_ce = 1'b1;

assign grp_fu_481_p_din0 = grp_fu_562_p0;

assign grp_fu_481_p_din1 = grp_fu_562_p1;

assign grp_fu_485_p_ce = 1'b1;

assign grp_fu_485_p_din0 = grp_fu_566_p0;

assign grp_fu_485_p_din1 = grp_fu_566_p1;

assign grp_fu_489_p_ce = 1'b1;

assign grp_fu_489_p_din0 = grp_fu_574_p0;

assign grp_fu_489_p_din1 = grp_fu_574_p1;

assign grp_fu_493_p_ce = 1'b1;

assign grp_fu_493_p_din0 = sext_ln102_9_fu_725_p1;

assign grp_fu_493_p_din1 = sext_ln102_8_fu_721_p1;

assign icmp_ln102_10_fu_1611_p2 = ((tmp_224_fu_1601_p4 == 3'd7) ? 1'b1 : 1'b0);

assign icmp_ln102_11_fu_1617_p2 = ((tmp_224_fu_1601_p4 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln102_1_fu_992_p2 = ((tmp_218_fu_982_p4 == 3'd7) ? 1'b1 : 1'b0);

assign icmp_ln102_2_fu_998_p2 = ((tmp_218_fu_982_p4 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln102_3_fu_1169_p2 = ((tmp_219_fu_1159_p4 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln102_4_fu_1185_p2 = ((tmp_220_fu_1175_p4 == 3'd7) ? 1'b1 : 1'b0);

assign icmp_ln102_5_fu_1191_p2 = ((tmp_220_fu_1175_p4 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln102_6_fu_1424_p2 = ((tmp_221_fu_1414_p4 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln102_7_fu_1440_p2 = ((tmp_222_fu_1430_p4 == 3'd7) ? 1'b1 : 1'b0);

assign icmp_ln102_8_fu_1446_p2 = ((tmp_222_fu_1430_p4 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln102_9_fu_1595_p2 = ((tmp_223_fu_1585_p4 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln102_fu_976_p2 = ((tmp_s_fu_966_p4 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln106_fu_866_p2 = ((i_3_reg_2891 < 9'd12) ? 1'b1 : 1'b0);

assign icmp_ln108_fu_871_p2 = ((i_3_reg_2891 > 9'd251) ? 1'b1 : 1'b0);

assign icmp_ln110_fu_2472_p2 = ((zi_1_fu_2460_p3 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln119_1_fu_2749_p2 = ((tmp_228_reg_3751 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln119_fu_2744_p2 = ((tmp_228_reg_3751 != 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln99_fu_614_p2 = ((ap_sig_allocacmp_i_3 == 9'd332) ? 1'b1 : 1'b0);

assign lshr_ln_fu_2529_p4 = {{shl_ln110_fu_2523_p2[63:1]}};

assign or_ln102_10_fu_1866_p2 = (xor_ln102_30_fu_1860_p2 | tmp_323_reg_3547);

assign or_ln102_11_fu_1893_p2 = (and_ln102_29_fu_1888_p2 | and_ln102_28_fu_1871_p2);

assign or_ln102_12_fu_2020_p2 = (xor_ln102_36_fu_2014_p2 | tmp_327_fu_1974_p3);

assign or_ln102_13_fu_2049_p2 = (and_ln102_32_fu_2044_p2 | and_ln102_31_fu_2026_p2);

assign or_ln102_14_fu_2175_p2 = (xor_ln102_42_fu_2169_p2 | tmp_331_reg_3596);

assign or_ln102_15_fu_2202_p2 = (and_ln102_35_fu_2197_p2 | and_ln102_34_fu_2180_p2);

assign or_ln102_16_fu_2329_p2 = (xor_ln102_48_fu_2323_p2 | tmp_335_fu_2283_p3);

assign or_ln102_17_fu_2366_p2 = (and_ln102_38_fu_2353_p2 | and_ln102_37_fu_2335_p2);

assign or_ln102_18_fu_775_p2 = (xor_ln102_2_fu_770_p2 | tmp_299_fu_751_p3);

assign or_ln102_19_fu_809_p2 = (tmp_299_fu_751_p3 | and_ln102_fu_765_p2);

assign or_ln102_1_fu_826_p2 = (and_ln102_2_fu_821_p2 | and_ln102_1_fu_803_p2);

assign or_ln102_20_fu_1086_p2 = (and_ln102_7_fu_1081_p2 | and_ln102_5_fu_1055_p2);

assign or_ln102_21_fu_1306_p2 = (and_ln102_13_fu_1300_p2 | and_ln102_11_fu_1272_p2);

assign or_ln102_22_fu_1512_p2 = (and_ln102_19_fu_1507_p2 | and_ln102_17_fu_1481_p2);

assign or_ln102_23_fu_1723_p2 = (and_ln102_25_fu_1717_p2 | and_ln102_23_fu_1689_p2);

assign or_ln102_24_fu_1845_p2 = (xor_ln102_27_fu_1840_p2 | tmp_323_reg_3547);

assign or_ln102_25_fu_1877_p2 = (tmp_323_reg_3547 | and_ln102_27_fu_1835_p2);

assign or_ln102_26_fu_1998_p2 = (xor_ln102_33_fu_1993_p2 | tmp_327_fu_1974_p3);

assign or_ln102_27_fu_2032_p2 = (tmp_327_fu_1974_p3 | and_ln102_30_fu_1988_p2);

assign or_ln102_28_fu_2154_p2 = (xor_ln102_39_fu_2149_p2 | tmp_331_reg_3596);

assign or_ln102_29_fu_2186_p2 = (tmp_331_reg_3596 | and_ln102_33_fu_2144_p2);

assign or_ln102_2_fu_1065_p2 = (xor_ln102_8_fu_1059_p2 | tmp_303_reg_3276);

assign or_ln102_30_fu_2307_p2 = (xor_ln102_45_fu_2302_p2 | tmp_335_fu_2283_p3);

assign or_ln102_31_fu_2341_p2 = (tmp_335_fu_2283_p3 | and_ln102_36_fu_2297_p2);

assign or_ln102_3_fu_1103_p2 = (and_ln102_8_fu_1098_p2 | and_ln102_6_fu_1075_p2);

assign or_ln102_4_fu_1283_p2 = (xor_ln102_13_fu_1277_p2 | tmp_308_fu_1221_p3);

assign or_ln102_5_fu_1323_p2 = (and_ln102_14_fu_1318_p2 | and_ln102_12_fu_1294_p2);

assign or_ln102_6_fu_1491_p2 = (xor_ln102_18_fu_1485_p2 | tmp_313_reg_3460);

assign or_ln102_7_fu_1529_p2 = (and_ln102_20_fu_1524_p2 | and_ln102_18_fu_1501_p2);

assign or_ln102_8_fu_1700_p2 = (xor_ln102_23_fu_1694_p2 | tmp_318_fu_1638_p3);

assign or_ln102_9_fu_1740_p2 = (and_ln102_26_fu_1735_p2 | and_ln102_24_fu_1711_p2);

assign or_ln102_fu_797_p2 = (xor_ln102_3_fu_791_p2 | tmp_299_fu_751_p3);

assign or_ln108_fu_2614_p2 = (icmp_ln108_reg_3254_pp0_iter3_reg | icmp_ln106_reg_3247_pp0_iter3_reg);

assign or_ln119_1_fu_2775_p2 = (xor_ln119_1_fu_2770_p2 | icmp_ln119_fu_2744_p2);

assign or_ln119_2_fu_2794_p2 = (and_ln119_fu_2764_p2 | and_ln119_1_fu_2781_p2);

assign or_ln119_fu_2754_p2 = (tmp_341_reg_3745 | icmp_ln119_1_fu_2749_p2);

assign p_ZL13A_sparse_data_0_address0 = zext_ln99_fu_620_p1;

assign p_ZL13A_sparse_data_1_address0 = zext_ln99_fu_620_p1;

assign p_ZL13A_sparse_data_2_address0 = zext_ln99_fu_620_p1;

assign p_ZL13A_sparse_data_3_address0 = zext_ln99_fu_620_p1;

assign p_ZL13A_sparse_data_4_address0 = zext_ln99_fu_620_p1;

assign p_ZL13A_sparse_data_5_address0 = zext_ln99_fu_620_p1;

assign p_ZL13A_sparse_data_6_address0 = zext_ln99_fu_620_p1;

assign p_ZL13A_sparse_data_7_address0 = zext_ln99_fu_620_p1;

assign p_ZL13A_sparse_data_8_address0 = zext_ln99_fu_620_p1;

assign p_ZL16A_sparse_indexes_0_address0 = zext_ln99_fu_620_p1;

assign p_ZL16A_sparse_indexes_1_address0 = zext_ln99_fu_620_p1;

assign p_ZL16A_sparse_indexes_2_address0 = zext_ln99_fu_620_p1;

assign p_ZL16A_sparse_indexes_3_address0 = zext_ln99_fu_620_p1;

assign p_ZL16A_sparse_indexes_4_address0 = zext_ln99_fu_620_p1;

assign p_ZL16A_sparse_indexes_5_address0 = zext_ln99_fu_620_p1;

assign p_ZL16A_sparse_indexes_6_address0 = zext_ln99_fu_620_p1;

assign p_ZL16A_sparse_indexes_7_address0 = zext_ln99_fu_620_p1;

assign p_ZL16A_sparse_indexes_8_address0 = zext_ln99_fu_620_p1;

assign select_ln102_10_fu_1459_p3 = ((and_ln102_15_reg_3466[0:0] == 1'b1) ? icmp_ln102_7_reg_3478 : icmp_ln102_8_reg_3485);

assign select_ln102_11_fu_1475_p3 = ((and_ln102_15_reg_3466[0:0] == 1'b1) ? and_ln102_16_fu_1470_p2 : icmp_ln102_7_reg_3478);

assign select_ln102_12_fu_1535_p3 = ((and_ln102_18_fu_1501_p2[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign select_ln102_13_fu_1543_p3 = ((or_ln102_7_fu_1529_p2[0:0] == 1'b1) ? select_ln102_12_fu_1535_p3 : Axi_7_reg_3455);

assign select_ln102_14_fu_1665_p3 = ((and_ln102_21_fu_1652_p2[0:0] == 1'b1) ? icmp_ln102_10_reg_3512 : icmp_ln102_11_reg_3519);

assign select_ln102_15_fu_1682_p3 = ((and_ln102_21_fu_1652_p2[0:0] == 1'b1) ? and_ln102_22_fu_1677_p2 : icmp_ln102_10_reg_3512);

assign select_ln102_16_fu_1746_p3 = ((and_ln102_24_fu_1711_p2[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign select_ln102_17_fu_1754_p3 = ((or_ln102_9_fu_1740_p2[0:0] == 1'b1) ? select_ln102_16_fu_1746_p3 : Axi_9_fu_1633_p2);

assign select_ln102_18_fu_1899_p3 = ((and_ln102_28_fu_1871_p2[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign select_ln102_19_fu_1907_p3 = ((or_ln102_11_fu_1893_p2[0:0] == 1'b1) ? select_ln102_18_fu_1899_p3 : Axi_11_reg_3542);

assign select_ln102_1_fu_888_p3 = ((or_ln102_1_reg_3192[0:0] == 1'b1) ? select_ln102_fu_881_p3 : Axi_1_reg_3182);

assign select_ln102_20_fu_2055_p3 = ((and_ln102_31_fu_2026_p2[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign select_ln102_21_fu_2063_p3 = ((or_ln102_13_fu_2049_p2[0:0] == 1'b1) ? select_ln102_20_fu_2055_p3 : Axi_13_fu_1969_p2);

assign select_ln102_22_fu_2208_p3 = ((and_ln102_34_fu_2180_p2[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign select_ln102_23_fu_2216_p3 = ((or_ln102_15_fu_2202_p2[0:0] == 1'b1) ? select_ln102_22_fu_2208_p3 : Axi_15_reg_3591);

assign select_ln102_24_fu_2358_p3 = ((and_ln102_37_fu_2335_p2[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign select_ln102_2_fu_1033_p3 = ((and_ln102_3_reg_3282[0:0] == 1'b1) ? icmp_ln102_1_reg_3294 : icmp_ln102_2_reg_3301);

assign select_ln102_3_fu_1049_p3 = ((and_ln102_3_reg_3282[0:0] == 1'b1) ? and_ln102_4_fu_1044_p2 : icmp_ln102_1_reg_3294);

assign select_ln102_4_fu_1109_p3 = ((and_ln102_6_fu_1075_p2[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign select_ln102_5_fu_1117_p3 = ((or_ln102_3_fu_1103_p2[0:0] == 1'b1) ? select_ln102_4_fu_1109_p3 : Axi_3_reg_3271);

assign select_ln102_6_fu_1248_p3 = ((and_ln102_9_fu_1235_p2[0:0] == 1'b1) ? icmp_ln102_4_reg_3374 : icmp_ln102_5_reg_3381);

assign select_ln102_7_fu_1265_p3 = ((and_ln102_9_fu_1235_p2[0:0] == 1'b1) ? and_ln102_10_fu_1260_p2 : icmp_ln102_4_reg_3374);

assign select_ln102_8_fu_1329_p3 = ((and_ln102_12_reg_3423[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign select_ln102_9_fu_1336_p3 = ((or_ln102_5_reg_3428[0:0] == 1'b1) ? select_ln102_8_fu_1329_p3 : Axi_5_reg_3418);

assign select_ln102_fu_881_p3 = ((and_ln102_1_reg_3187[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign select_ln109_fu_2452_p3 = ((and_ln109_fu_2440_p2[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign select_ln110_1_fu_2551_p3 = ((tmp_339_fu_2543_p3[0:0] == 1'b1) ? 11'd1023 : 11'd1022);

assign select_ln110_2_fu_2601_p3 = ((tmp_226_reg_3703[0:0] == 1'b1) ? 25'd31107755 : trunc_ln105_1_reg_3649);

assign select_ln110_fu_2492_p3 = ((tmp_338_fu_2478_p3[0:0] == 1'b1) ? sub_ln110_fu_2486_p2 : zi_1_fu_2460_p3);

assign select_ln112_fu_2607_p3 = ((grp_fu_556_p2[0:0] == 1'b1) ? 25'd1747627 : trunc_ln105_1_reg_3649);

assign select_ln119_fu_2786_p3 = ((and_ln119_fu_2764_p2[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign select_ln121_1_fu_2876_p3 = ((xor_ln121_1_fu_2862_p2[0:0] == 1'b1) ? select_ln121_fu_2868_p3 : trunc_ln121_1_fu_2838_p1);

assign select_ln121_fu_2868_p3 = ((and_ln121_fu_2856_p2[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign sext_ln102_10_fu_1350_p1 = $signed(shl_ln102_2_fu_1342_p3);

assign sext_ln102_11_fu_840_p1 = $signed(p_ZL13A_sparse_data_4_load_reg_3044);

assign sext_ln102_12_fu_844_p1 = $signed(x_q0);

assign sext_ln102_13_fu_1558_p1 = $signed(shl_ln102_3_fu_1550_p3);

assign sext_ln102_14_fu_849_p1 = $signed(p_ZL13A_sparse_data_5_load_reg_3054);

assign sext_ln102_15_fu_853_p1 = $signed(x_q1);

assign sext_ln102_16_fu_1769_p1 = shl_ln102_4_fu_1762_p3;

assign sext_ln102_17_fu_1773_p1 = mul_ln102_5_reg_3316_pp0_iter2_reg;

assign sext_ln102_18_fu_1004_p1 = $signed(p_ZL13A_sparse_data_6_load_reg_3064);

assign sext_ln102_19_fu_1008_p1 = $signed(x_q0);

assign sext_ln102_20_fu_1922_p1 = shl_ln102_5_fu_1914_p3;

assign sext_ln102_21_fu_1926_p1 = mul_ln102_6_reg_3386_pp0_iter2_reg;

assign sext_ln102_22_fu_1017_p1 = $signed(x_q1);

assign sext_ln102_23_fu_2078_p1 = shl_ln102_6_fu_2071_p3;

assign sext_ln102_24_fu_2082_p1 = mul_ln102_7_reg_3397_pp0_iter2_reg;

assign sext_ln102_25_fu_1201_p1 = $signed(x_q0);

assign sext_ln102_26_fu_2231_p1 = shl_ln102_7_fu_2223_p3;

assign sext_ln102_27_fu_2235_p1 = mul_ln102_8_reg_3433_pp0_iter2_reg;

assign sext_ln102_2_fu_661_p1 = $signed(p_ZL13A_sparse_data_1_load_reg_3009);

assign sext_ln102_3_fu_665_p1 = $signed(x_q0);

assign sext_ln102_4_fu_902_p1 = $signed(shl_ln_fu_894_p3);

assign sext_ln102_5_fu_712_p1 = $signed(p_ZL13A_sparse_data_2_load_reg_3024);

assign sext_ln102_6_fu_716_p1 = $signed(x_q0);

assign sext_ln102_7_fu_1132_p1 = $signed(shl_ln102_1_fu_1124_p3);

assign sext_ln102_8_fu_721_p1 = $signed(p_ZL13A_sparse_data_3_load_reg_3034);

assign sext_ln102_9_fu_725_p1 = $signed(x_q1);

assign sext_ln109_1_fu_2400_p1 = trunc_ln109_1_reg_3638;

assign sext_ln109_2_fu_2394_p1 = trunc_ln109_1_reg_3638;

assign sext_ln109_fu_2397_p1 = Axi_18_reg_3627;

assign sext_ln110_fu_2564_p1 = $signed(sub_ln110_1_fu_2559_p2);

assign sext_ln119_1_fu_2703_p1 = $signed(shl_ln1_fu_2692_p3);

assign sext_ln119_fu_2700_p1 = y_load_reg_3633_pp0_iter4_reg;

assign sext_ln121_1_fu_2820_p1 = $signed(yi_1_fu_2800_p3);

assign sext_ln121_fu_2816_p1 = $signed(shl_ln2_fu_2809_p3);

assign shl_ln102_1_fu_1124_p3 = {{select_ln102_5_fu_1117_p3}, {22'd0}};

assign shl_ln102_2_fu_1342_p3 = {{select_ln102_9_fu_1336_p3}, {22'd0}};

assign shl_ln102_3_fu_1550_p3 = {{select_ln102_13_fu_1543_p3}, {22'd0}};

assign shl_ln102_4_fu_1762_p3 = {{select_ln102_17_reg_3524}, {22'd0}};

assign shl_ln102_5_fu_1914_p3 = {{select_ln102_19_fu_1907_p3}, {22'd0}};

assign shl_ln102_6_fu_2071_p3 = {{select_ln102_21_reg_3573}, {22'd0}};

assign shl_ln102_7_fu_2223_p3 = {{select_ln102_23_fu_2216_p3}, {22'd0}};

assign shl_ln110_fu_2523_p2 = zext_ln110_fu_2517_p1 << zext_ln110_1_fu_2520_p1;

assign shl_ln1_fu_2692_p3 = {{sub_ln119_fu_2687_p2}, {8'd0}};

assign shl_ln2_fu_2809_p3 = {{trunc_ln121_reg_3757}, {8'd0}};

assign shl_ln_fu_894_p3 = {{select_ln102_1_fu_888_p3}, {22'd0}};

assign sub_ln110_1_fu_2559_p2 = (6'd10 - trunc_ln110_reg_3673);

assign sub_ln110_fu_2486_p2 = (32'd0 - zi_1_fu_2460_p3);

assign sub_ln119_fu_2687_p2 = (trunc_ln119_reg_3644_pp0_iter4_reg - zi_2_fu_2663_p13);

assign sub_ln121_fu_2824_p2 = ($signed(sext_ln121_fu_2816_p1) - $signed(sext_ln121_1_fu_2820_p1));

assign tmp_13_fu_2574_p3 = {{tmp_338_reg_3662}, {add_ln110_1_fu_2568_p2}};

assign tmp_218_fu_982_p4 = {{add_ln102_fu_906_p2[56:54]}};

assign tmp_219_fu_1159_p4 = {{add_ln102_2_fu_1136_p2[56:55]}};

assign tmp_220_fu_1175_p4 = {{add_ln102_2_fu_1136_p2[56:54]}};

assign tmp_221_fu_1414_p4 = {{add_ln102_4_fu_1354_p2[56:55]}};

assign tmp_222_fu_1430_p4 = {{add_ln102_4_fu_1354_p2[56:54]}};

assign tmp_223_fu_1585_p4 = {{add_ln102_6_fu_1562_p2[56:55]}};

assign tmp_224_fu_1601_p4 = {{add_ln102_6_fu_1562_p2[56:54]}};

assign tmp_299_fu_751_p3 = Axi_1_fu_746_p2[32'd31];

assign tmp_302_fu_929_p3 = add_ln102_fu_906_p2[32'd53];

assign tmp_303_fu_946_p3 = Axi_3_fu_940_p2[32'd31];

assign tmp_304_fu_1026_p3 = add_ln102_reg_3260[32'd54];

assign tmp_307_fu_1206_p3 = add_ln102_2_reg_3352[32'd53];

assign tmp_308_fu_1221_p3 = Axi_5_fu_1216_p2[32'd31];

assign tmp_309_fu_1241_p3 = add_ln102_2_reg_3352[32'd54];

assign tmp_312_fu_1377_p3 = add_ln102_4_fu_1354_p2[32'd53];

assign tmp_313_fu_1394_p3 = Axi_7_fu_1388_p2[32'd31];

assign tmp_314_fu_1452_p3 = add_ln102_4_reg_3444[32'd54];

assign tmp_317_fu_1623_p3 = add_ln102_6_reg_3490[32'd53];

assign tmp_318_fu_1638_p3 = Axi_9_fu_1633_p2[32'd31];

assign tmp_319_fu_1658_p3 = add_ln102_6_reg_3490[32'd54];

assign tmp_327_fu_1974_p3 = Axi_13_fu_1969_p2[32'd31];

assign tmp_335_fu_2283_p3 = Axi_17_fu_2278_p2[32'd31];

assign tmp_336_fu_2414_p3 = add_ln109_fu_2408_p2[32'd32];

assign tmp_337_fu_2426_p3 = add_ln109_1_fu_2403_p2[32'd31];

assign tmp_338_fu_2478_p3 = zi_1_fu_2460_p3[32'd31];

assign tmp_339_fu_2543_p3 = shl_ln110_fu_2523_p2[32'd54];

assign tmp_342_fu_2830_p3 = sub_ln121_fu_2824_p2[32'd32];

assign tmp_343_fu_2842_p3 = sub_ln121_fu_2824_p2[32'd31];

assign tmp_s_fu_966_p4 = {{add_ln102_fu_906_p2[56:55]}};

assign trunc_ln105_1_fu_2468_p1 = zi_1_fu_2460_p3[24:0];

assign trunc_ln105_fu_2597_p1 = current_state_q0[24:0];

assign trunc_ln109_1_fu_2380_p1 = y_q0;

assign trunc_ln109_fu_2422_p1 = add_ln109_fu_2408_p2[31:0];

assign trunc_ln110_fu_2507_p1 = tmp_225_fu_2500_p3[5:0];

assign trunc_ln119_fu_2390_p1 = Axi_18_fu_2372_p3[24:0];

assign trunc_ln121_1_fu_2838_p1 = sub_ln121_fu_2824_p2[31:0];

assign trunc_ln121_fu_2737_p1 = zi_2_fu_2663_p13[23:0];

assign x_address0 = x_address0_local;

assign x_address1 = x_address1_local;

assign x_ce0 = x_ce0_local;

assign x_ce1 = x_ce1_local;

assign xor_ln102_10_fu_1092_p2 = (or_ln102_20_fu_1086_p2 ^ 1'd1);

assign xor_ln102_11_fu_1229_p2 = (tmp_308_fu_1221_p3 ^ 1'd1);

assign xor_ln102_12_fu_1254_p2 = (tmp_309_fu_1241_p3 ^ 1'd1);

assign xor_ln102_13_fu_1277_p2 = (select_ln102_6_fu_1248_p3 ^ 1'd1);

assign xor_ln102_14_fu_1289_p2 = (tmp_305_reg_3358 ^ 1'd1);

assign xor_ln102_15_fu_1312_p2 = (or_ln102_21_fu_1306_p2 ^ 1'd1);

assign xor_ln102_16_fu_1402_p2 = (tmp_313_fu_1394_p3 ^ 1'd1);

assign xor_ln102_17_fu_1464_p2 = (tmp_314_fu_1452_p3 ^ 1'd1);

assign xor_ln102_18_fu_1485_p2 = (select_ln102_10_fu_1459_p3 ^ 1'd1);

assign xor_ln102_19_fu_1496_p2 = (tmp_310_reg_3449 ^ 1'd1);

assign xor_ln102_1_fu_786_p2 = (tmp_reg_3119 ^ 1'd1);

assign xor_ln102_20_fu_1518_p2 = (or_ln102_22_fu_1512_p2 ^ 1'd1);

assign xor_ln102_21_fu_1646_p2 = (tmp_318_fu_1638_p3 ^ 1'd1);

assign xor_ln102_22_fu_1671_p2 = (tmp_319_fu_1658_p3 ^ 1'd1);

assign xor_ln102_23_fu_1694_p2 = (select_ln102_14_fu_1665_p3 ^ 1'd1);

assign xor_ln102_24_fu_1706_p2 = (tmp_315_reg_3496 ^ 1'd1);

assign xor_ln102_25_fu_1729_p2 = (or_ln102_23_fu_1723_p2 ^ 1'd1);

assign xor_ln102_26_fu_1830_p2 = (tmp_323_reg_3547 ^ 1'd1);

assign xor_ln102_27_fu_1840_p2 = (tmp_322_reg_3536 ^ 1'd1);

assign xor_ln102_28_fu_1850_p2 = (tmp_320_reg_3529 ^ or_ln102_24_fu_1845_p2);

assign xor_ln102_29_fu_1855_p2 = (tmp_320_reg_3529 ^ 1'd1);

assign xor_ln102_2_fu_770_p2 = (tmp_298_reg_3136 ^ 1'd1);

assign xor_ln102_30_fu_1860_p2 = (xor_ln102_28_fu_1850_p2 ^ 1'd1);

assign xor_ln102_31_fu_1882_p2 = (or_ln102_25_fu_1877_p2 ^ 1'd1);

assign xor_ln102_32_fu_1982_p2 = (tmp_327_fu_1974_p3 ^ 1'd1);

assign xor_ln102_33_fu_1993_p2 = (tmp_326_reg_3567 ^ 1'd1);

assign xor_ln102_34_fu_2004_p2 = (tmp_324_reg_3555 ^ or_ln102_26_fu_1998_p2);

assign xor_ln102_35_fu_2009_p2 = (tmp_324_reg_3555 ^ 1'd1);

assign xor_ln102_36_fu_2014_p2 = (xor_ln102_34_fu_2004_p2 ^ 1'd1);

assign xor_ln102_37_fu_2038_p2 = (or_ln102_27_fu_2032_p2 ^ 1'd1);

assign xor_ln102_38_fu_2139_p2 = (tmp_331_reg_3596 ^ 1'd1);

assign xor_ln102_39_fu_2149_p2 = (tmp_330_reg_3585 ^ 1'd1);

assign xor_ln102_3_fu_791_p2 = (xor_ln102_4_fu_781_p2 ^ 1'd1);

assign xor_ln102_40_fu_2159_p2 = (tmp_328_reg_3578 ^ or_ln102_28_fu_2154_p2);

assign xor_ln102_41_fu_2164_p2 = (tmp_328_reg_3578 ^ 1'd1);

assign xor_ln102_42_fu_2169_p2 = (xor_ln102_40_fu_2159_p2 ^ 1'd1);

assign xor_ln102_43_fu_2191_p2 = (or_ln102_29_fu_2186_p2 ^ 1'd1);

assign xor_ln102_44_fu_2291_p2 = (tmp_335_fu_2283_p3 ^ 1'd1);

assign xor_ln102_45_fu_2302_p2 = (tmp_334_reg_3616 ^ 1'd1);

assign xor_ln102_46_fu_2313_p2 = (tmp_332_reg_3604 ^ or_ln102_30_fu_2307_p2);

assign xor_ln102_47_fu_2318_p2 = (tmp_332_reg_3604 ^ 1'd1);

assign xor_ln102_48_fu_2323_p2 = (xor_ln102_46_fu_2313_p2 ^ 1'd1);

assign xor_ln102_49_fu_2347_p2 = (or_ln102_31_fu_2341_p2 ^ 1'd1);

assign xor_ln102_4_fu_781_p2 = (tmp_reg_3119 ^ or_ln102_18_fu_775_p2);

assign xor_ln102_5_fu_815_p2 = (or_ln102_19_fu_809_p2 ^ 1'd1);

assign xor_ln102_6_fu_954_p2 = (tmp_303_fu_946_p3 ^ 1'd1);

assign xor_ln102_7_fu_1038_p2 = (tmp_304_fu_1026_p3 ^ 1'd1);

assign xor_ln102_8_fu_1059_p2 = (select_ln102_2_fu_1033_p3 ^ 1'd1);

assign xor_ln102_9_fu_1070_p2 = (tmp_300_reg_3265 ^ 1'd1);

assign xor_ln102_fu_759_p2 = (tmp_299_fu_751_p3 ^ 1'd1);

assign xor_ln106_fu_2624_p2 = (icmp_ln106_reg_3247_pp0_iter3_reg ^ 1'd1);

assign xor_ln108_fu_2618_p2 = (or_ln108_fu_2614_p2 ^ 1'd1);

assign xor_ln109_1_fu_2446_p2 = (tmp_337_fu_2426_p3 ^ tmp_336_fu_2414_p3);

assign xor_ln109_fu_2434_p2 = (tmp_336_fu_2414_p3 ^ 1'd1);

assign xor_ln110_fu_2639_p2 = (icmp_ln110_reg_3656 ^ 1'd1);

assign xor_ln119_1_fu_2770_p2 = (tmp_341_reg_3745 ^ 1'd1);

assign xor_ln119_fu_2759_p2 = (tmp_340_reg_3739 ^ 1'd1);

assign xor_ln121_1_fu_2862_p2 = (tmp_343_fu_2842_p3 ^ tmp_342_fu_2830_p3);

assign xor_ln121_fu_2850_p2 = (tmp_342_fu_2830_p3 ^ 1'd1);

assign yi_1_fu_2800_p3 = ((or_ln119_2_fu_2794_p2[0:0] == 1'b1) ? select_ln119_fu_2786_p3 : yi_fu_2741_p1);

assign yi_fu_2741_p1 = add_ln119_reg_3734[31:0];

assign zext_ln102_10_fu_734_p1 = p_ZL16A_sparse_indexes_5_load_reg_3049;

assign zext_ln102_11_fu_1813_p1 = tmp_321_reg_3322_pp0_iter2_reg;

assign zext_ln102_12_fu_858_p1 = p_ZL16A_sparse_indexes_6_load_reg_3059;

assign zext_ln102_13_fu_1966_p1 = tmp_325_reg_3392_pp0_iter2_reg;

assign zext_ln102_14_fu_862_p1 = p_ZL16A_sparse_indexes_7_load_reg_3069;

assign zext_ln102_15_fu_2122_p1 = tmp_329_reg_3403_pp0_iter2_reg;

assign zext_ln102_16_fu_1022_p1 = p_ZL16A_sparse_indexes_8_load_reg_3079;

assign zext_ln102_17_fu_2275_p1 = tmp_333_reg_3439_pp0_iter2_reg;

assign zext_ln102_18_fu_1013_p1 = p_ZL13A_sparse_data_7_load_reg_3074;

assign zext_ln102_19_fu_1197_p1 = p_ZL13A_sparse_data_8_load_reg_3084;

assign zext_ln102_1_fu_743_p1 = tmp_296_reg_3131;

assign zext_ln102_2_fu_647_p1 = p_ZL16A_sparse_indexes_1_q0;

assign zext_ln102_3_fu_937_p1 = tmp_301_reg_3147;

assign zext_ln102_4_fu_670_p1 = p_ZL16A_sparse_indexes_2_load_reg_3019;

assign zext_ln102_5_fu_1213_p1 = tmp_306_reg_3202;

assign zext_ln102_6_fu_674_p1 = p_ZL16A_sparse_indexes_3_load_reg_3029;

assign zext_ln102_7_fu_1385_p1 = tmp_311_reg_3212;

assign zext_ln102_8_fu_730_p1 = p_ZL16A_sparse_indexes_4_load_reg_3039;

assign zext_ln102_9_fu_1630_p1 = tmp_316_reg_3311;

assign zext_ln102_fu_642_p1 = p_ZL16A_sparse_indexes_0_q0;

assign zext_ln110_1_fu_2520_p1 = add_ln110_reg_3678;

assign zext_ln110_2_fu_2539_p1 = lshr_ln_fu_2529_p4;

assign zext_ln110_fu_2517_p1 = select_ln110_reg_3667;

assign zext_ln99_fu_620_p1 = ap_sig_allocacmp_i_3;

assign zi_1_fu_2460_p3 = ((xor_ln109_1_fu_2446_p2[0:0] == 1'b1) ? select_ln109_fu_2452_p3 : trunc_ln109_fu_2422_p1);

assign zi_2_fu_2663_p11 = 'bx;

assign zi_2_fu_2663_p12 = {{{{icmp_ln106_reg_3247_pp0_iter3_reg}, {xor_ln108_reg_3719}}, {and_ln110_reg_3724}}, {and_ln110_2_reg_3729}};

always @ (posedge ap_clk) begin
    zext_ln99_reg_2902[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln99_reg_2902_pp0_iter1_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln99_reg_2902_pp0_iter2_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln99_reg_2902_pp0_iter3_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln99_reg_2902_pp0_iter4_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
end

endmodule //ADMM_solver_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP
