// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================
`timescale 1 ns / 1 ps
(* DowngradeIPIdentifiedWarnings="yes" *) module ADMM_solver_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_p_ZL13A_sparse_data_6_ROM_AUTO4jc (
    address0, ce0, q0, 
    reset, clk);

parameter DataWidth = 24;
parameter AddressWidth = 9;
parameter AddressRange = 332;
 
input[AddressWidth-1:0] address0;
input ce0;
output reg[DataWidth-1:0] q0;

input reset;
input clk;

 
reg [DataWidth-1:0] rom0[0:AddressRange-1];


initial begin
     
    $readmemh("./ADMM_solver_ADMM_iteration_Pipeline_ADMM_IT_ZY_UPDATE_LOOP_p_ZL13A_sparse_data_6_ROM_AUTO4jc.dat", rom0);
end

  
always @(posedge clk) 
begin 
    if (ce0) 
    begin
        q0 <= rom0[address0];
    end
end


endmodule

