// Auto-generated by scripts/header_generator.py. Do not edit.
#ifndef ADMM_RUNTIME_CONFIG_H
#define ADMM_RUNTIME_CONFIG_H

#define ADMM_USE_FLOAT 0
#define ADMM_ITERATIONS 10

#endif // ADMM_RUNTIME_CONFIG_H
